xxubin04/README.md
xxubin04/구현/28278_stack2.py

https://www.acmicpc.net/problem/28278
5분
- 문제를 읽고 이해하면 쉽게 구현할 수 있는 문제이다. 2번에서 헷갈릴 수 있으니 예제를 잘 보자.
- 먼저, 반복할 횟수를 입력받고 for문을 만든다.
```python    
import sys
n = int(sys.stdin.readline())
stack = []
num = sys.stdin.readline().split()
```
- 명령 5가지를 충족하는 if문을 작성한다.
```python
if num[0] == "1":
stack.append(num[-1])
elif num[0] == "2":
if len(stack) != 0:
print(stack.pop(-1))
else:
print(-1)
elif num[0] == "3":
print(len(stack))
elif num[0] == "4":
if len(stack) == 0:
print(1)
else:
print(0)
elif num[0] == "5":
if len(stack) != 0:
print(stack[-1])
else:
print(-1)
```
- 1부터 5를 제외한 숫자가 num에 입력될 수 있으니 다음과 같이 지정한다.
```python
else:
break
```
- 전체 코드는 아래와 같다.
```python
import sys
n = int(sys.stdin.readline())
stack = []
num = sys.stdin.readline().split()
if num[0] …
```

1-xxubin04

---

9-kyo-hwang/README.md
9-kyo-hwang/다익스트라/22865 가장 먼 곳.txt

[22865 가장 먼 곳](https://www.acmicpc.net/problem/22865)
1시간
이번 차시의 문제는 최단 경로, 그 중에서 single-source 문제이다. 나는 이 문제를 Dijkstra 알고리즘을 이용해 해결했다.
하나의 출발 노드 s로부터 다른 모든 노드까지의 최단 경로를 찾는 'Single-source' 최단 경로 문제
- 입력: 음수 사이클이 없는 가중치 방향그래프 G=(V, E)와 출발 노드 s $\in$ V
- 목적: 각 노드 v $\in$ V에 대해서 다음을 계산한다.
- d[v]
- 처음에는 d[s] = 0, d[v] = $\infty$로 시작한다.
- 알고리즘이 진행됨에 따라서 감소해간다. 하지만 항상 d[v] $\ge \delta(s, v)$를 유지한다
- 최종적으로는 d[v] = $\delta(s, v)$가 된다.
- $\pi$[v]: s에서 v까지의 최단 경로 상에서 v의 직전 노드(predecessor)
- 그런 노드가 없는 경우 $\pi$[v] = NULL
**기본 연산: Relaxation**
- 대부분의 single-source 최단경로 알고리즘의 기본 구조
1. 초기화: d[s] = 0, 노드 v $\ne$ s에 대해 d[v] = $\infty$, $\pi$[v] = NULL
2. 엣지들에 대한 반복적인 relaxation.
- 알고리즘들 간의 차이는 어떤 엣지에 대해, 어떤 순서로 relaxation을 하느냐에 있음
- 음수 가정치가 없다고 가정한다.
- s로부터의 최단경로 길이를 이미 알아낸 노드들의 집합 S를 유지한다. 맨 처음엔 S = …

6-9kyo-hwang

---

9-kyo-hwang/README.md
9-kyo-hwang/백트래킹/16987 계란으로 계란치기.txt

[16987 계란으로 계란치기](https://www.acmicpc.net/problem/16987)
1시간
N개의 계란이 주어진다. 각 계란은 [내구도(S), 무게(W)]를 가지고 있다. 그리고 계란끼리 치면 무게만큼 내구도가 감소한다. 예를 들어
- 계란 1: 내구도 7, 무게 5 / 계란 2: 내구도 3, 무게 4
- 이 때 계란 1이 계란 2를 치면 
- 계란 2의 내구도는 3-5=-2로 감소하며 깨지고
- 계란 1은 내구도 7-4=3으로 감소한다.
다음과 같은 전략으로 퍼즐을 해결한다.
1. 가장 왼쪽 계란을 든다.
2. 손에 들고 있는 계란으로 깨지지 않은 다른 계란 중 하나를 친다. 단, 아래의 경우에는 계란을 치지 않고 넘어간다.
i. 손에 든 계란이 깨졌거나
ii. 깨지지 않은 다른 계란이 없거나
3. 가장 최근에 든 계란의 한 칸 오른쪽 계란을 손에 들고 2번 과정을 반복한다. 만약 가장 최근에 든 계란이 가장 오른쪽 계란이라면 진행을 멈춘다.
입력은 다음과 같이 주어진다.
- 계란 개수 $1 \le N \le 8$
- N개의 계란 정보(내구도 $1 \le S_i \le 300$, 무게 $1 \le W_i \le 300$)
1번 계란으로 2번 계란을 **치냐/안치냐** , 1번 계란으로 2번 ~ N번 계란 중 **어떤 걸 치냐** 에 따라서  많은 경우의 수가 갈라진다. 보통 이런 경우 재귀를 이용한 **백트래킹(Backtracking)** 전략이 사용되는데, 이 문제가 그렇다.
추가로, 계란 개수가 최대 **8개** 까지 밖에 주어지지 않는다. 개수가 보통 이렇게 적은 경우 **모든 …

8-9kyo-hwang

---

Dolchae/README.md
Dolchae/구현/1158 요세푸스 문제.py

[1158 요세푸스 문제](https://www.acmicpc.net/problem/1158)
40분
N명의 사람들이 원으로 앉아있고, 입력된 K번째 사람을 제거하는 순서를 출력하는 문제이다.
```python
input_ = open(0).readline
num, order = map(int,input_().split())
list = [i+1 for i in range(num)]
ans_list = []
count = 0
```
- num에 사람의 수와 order에 k번째의 k를 입력받는다.
- 1부터 num까지의 리스트를 list에 저장한다.
- 나중에 출력할 정답 리스트인 ans_list를 만든다.
- count는 list에서 pop하고 ans_list에 append 할, k번째 사람의 인덱스를 나타낼 변수이다.
<br>
```python
while True:
if len(list)==0:
break
count = (count+order-1)%len(list)
ans_list.append(list.pop(count))
print(f"<{', '.join(map(str,ans_list))}>")
```
- while문을 실행하며 list의 길이가 0이 되면 즉, 사람이 0명이 되면 break 되도록 한다.
- (count+order-1)의 연산으로 count는 제거해야 할 다음 인덱스를 가리키게 되고, %len(list)로 다음 인덱스가 리스트의 길이를 넘어갔을 때 다시 처음부터 시작될 수 있도록 한다.
- count를 list에서 pop하고 ans_list에 저장한다.
- 마지막으로 ans_list를 …

13-Dolchae

---

9-kyo-hwang/README.md
9-kyo-hwang/Tree/2023 KAKAO BLIND RECRUITMENT 표현 가능한 이진트리.cpp

2023 KAKAO BLIND RECRUITMENT 문제 4 - [표현 가능한 이진트리](https://school.programmers.co.kr/learn/courses/30/lessons/150367)
1시간 + a
다음과 같은 이진트리가 존재한다고 가정하자.
주어진 이진트리에 더미 노드를 추가해 포화 이진트리를 만들면 다음과 같다. 더미 노드는 점선으로 표시했으며, 노드 안의 숫자는 살펴보는 순서를 의미한다.
노드들을 왼쪽에 있는 순서대로 살펴보며 0(더미 노드), 1(실제 노드)을 사용해 문자열로 표현하면 "0111010"이 된다. 이 이진수를 십진수로 변환하면 58이다.
정수 배열 numbers가 주어졌을 때, 해당 수들을 이진트리로 표현할 수 있다면 1/없다면 0을 1차원 정수 배열에 담아 return하도록 solution 함수를 완성하라.
이진트리로 수를 표현하려면 0, 1로 이루어진 문자열이 필요하기 때문에, 우선 10진수를 2진수로 변환한다.
여러가지 방법이 있겠지만, 여기서는 C++이 제공하는 'bitset' 라이브러리를 사용하였다.
```cpp
string decimal_to_binary(int64& number) {  // using int64 = long long;
string s = bitset<64>(number).to_string();
s = s.substr(s.find('1'));
...
}
```
주어지는 수가 최대 $10^{15}$이라, int64 범위까지 확인해야 하기 때문에 64비트 길이로 정의한다.
예를 들어, 42이라는 숫자가 주어지면 …

24-9kyo-hwang

---

9-kyo-hwang/Brute Force/2024 KAKAO WINTER INTERSHIP 문제 3 주사위 고르기.cpp
9-kyo-hwang/README.md

[2024 KAKAO WINTER INTERSHIP 문제 3: 주사위 고르기](https://school.programmers.co.kr/learn/courses/30/lessons/258709)
2시간 + a?
n개의 주사위가 주어진다. 이를 A, B가 각각 n/2개씩 나눠 갖는다. 각각의 주사위를 모두 굴려, 나온 수들을 합해 점수를 비교한다. 둘 중 큰 쪽이 승리한다. 이 때 A가 승리할 확률이 가장 높은 주사위 조합을 찾아야 한다.
다음은 n = 4인 예시이다.
주사위 | 구성
-- | --
#1 | [1, 2, 3, 4, 5, 6]
#2 | [3, 3, 3, 3, 4, 4]
#3 | [1, 3, 3, 4, 4, 4]
#4 | [1, 1, 4, 4, 5, 5]
- 예를 들어 A가 주사위 1번과 2번을 가져간 뒤 6, 3을 굴리고, B가 주사위 3번과 4번을 가져간 뒤 4, 1을 굴린다면 A의 승리이다. (6 + 3 > 4 + 1)
A가 가져가는 주사위 조합에 따라, 주사위를 굴린 1296가지 경우의 승패 결과를 세어보면 아래 표와 같다.
A의 주사위 | 승 | 무 | 패
-- | -- | -- | --
#1, #2 | 596 | 196 | 504
#1, #3 | 560 | 176 | 560
#1, #4 | 616 | 184 | 496
#2, #3 | 496 | 184 | 616
#2, #4 | 560 | 176 | 560
#3, #4 | 504 | 196 | 596
A가 승리할 확률이 가장 높아지기 위해선 주사위 1번과 4번을 가져가야 한다.
크게 2가지를 확인해야 한다. 1. A가 가져갈 주사위 …

26-9kyo-hwang

---

xxubin04/Binary Search/2805_나무 자르기.py
xxubin04/README.md

2024-02-15 2805번_나무자르기
[2805번 : 나무 자르기🌳](https://www.acmicpc.net/problem/2805)
<br>
50분
<br>
**잘라야 하는 나무의 최소길이를 충족**하면서 **절단기에 설정할 수 있는 높이의 최댓값**을 구하자.
<br>
<br>
```python
tree_num, length = map(int, input().split())
trees = sorted(list(map(int, input().split())))
```
`tree_num` : 나무의 개수
`length` : 자른 나무 길이 총합의 최소 길이
`trees`에 나무들의 길이를 입력받는다.
<br>
```python
def binary_search(target, trees):
start = 0
end = trees[-1]
while start <= end:
mid = (start + end) // 2
cutted_trees = 0
for i in trees:
if (i-mid) >= 0:
cutted_trees += (i-mid)
if cutted_trees == target:
return mid
elif cutted_trees > target:
start = mid + 1 
else:
end = mid - 1
```
이 문제의 목적은 절단기의 최대 길이를 구하는 것이다. 따라서, **이진탐색** 방법을 사용하면 되겠다고 생각하였다.  
`cutted_trees`는 절단기로 잘랐을때, 잘린 나무들의 길이의 총합이다. 절단기의 높이보다 큰 나무만 잘리기 때문에 `i-mid`가 0보다 크거나 …

28-xxubin04

---

Dolchae/README.md
Dolchae/이진 탐색/6236 용돈 관리.py

[6236 용돈 관리](https://www.acmicpc.net/problem/6236)
50분 + a
- N일 동안 M번만 통장에서 돈을 빼서 쓴다.
- 통장에서 K원을 인출하고 이 돈으로 하루를 보낼 수 있다면 그대로 사용하고, 모자라면 남은 금액은 통장에 넣고 다시 K원을 인출한다. 
- 정확히 M번을 맞추기 위해 남은 금액이 사용할 금액보다 많아도 다시 집어넣고 K원을 인출할 수 있다.
- 여기서 최소 금액 K를 구하는 문제이다.
<br>
- 이분 탐색이란 정렬된 리스트에서 특정한 값의 위치를 찾는 알고리즘이다.
- 일반탐색보다 속도가 빠르다.
- 처음과 마지막의 중간값을 선택해 최종 찾아야하는 값과 크고 작음을 비교하는 방식을 반복하며 탐색한다.
<br>
```python
import sys
n, m = map(int, input().split())
money = []
money.append(int(input()))
start = max(money)  
end = sum(money)  
```
- n과 m을 입력받고 money에 각각의 날에 사용할 금액을 입력받아 리스트로 저장한다.
- 이분 탐색을 하기 위해 start와 end 변수를 만든다.
- start는 가장 작은 범위를 나타내는데, 적어도 돈의 최댓값은 쓸 것이므로 max(money)로 지정한다.
- end는 가장 큰 범위 끝을 나타내며 한번에 인출해 다 쓰는 경우가 이를 나타낸다.
<br>
```python
ans = 0
while start <= end: …
```

28-Dolchae

---

Dolchae/README.md
Dolchae/브루트포스/2961 도영이가 만든 맛있는 음식n.py
Dolchae/이진 탐색/6236 용돈 관리.py

[2961 도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
50분?
재료의 개수와 그 재료의 신맛과 쓴맛이 주어지면 신맛과 쓴맛의 차이가 가장 작은 요리의 차이를 출력하는 문제이다.
이때, 그 음식의 신맛은 사용한 재료의 신맛의 곱이고, 쓴맛의 합이다.
<br>
```python
import sys
from itertools import combinations
ingrid = [[0 for _ in range(2)] for _ in range(n)]
ingrid[i][0],ingrid[i][1] = map(int,input().split())
```
- 조합을 사용하기 위해 combinations를 import 해준다.
- 재료의 개수 n과 재료의 신맛과 쓴맛을 담은 리스트 ingrid를 저장한다.
- ingrid[.][0]에는 신맛이, ingrid[.][1]에는 쓴맛을 저장한다.
<br>
```python
ans = abs(ingrid[0][0] - ingrid[0][1])
for i in range(1,n+1): #1
for comb in combinations(ingrid,i): #2
print(comb)
sour, bitter = 1,0
for j in range(i): #3
sour *= comb[j][0]
bitter += comb[j][1]
now_diff = abs(sour-bitter)
if now_diff < ans: 
ans = …
```

29-Dolchae

---

9-kyo-hwang/Graph Traversal/1039 교환.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/SWEA 5644 무선 충전.cpp

[SWEA 5644 무선 충전](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRDL1aeugDFAUo&categoryId=AWXRDL1aeugDFAUo&categoryType=CODE&problemTitle=5644&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1)(회원가입 필요)
총 2시간...?
위와 같은 (10 x 10) 크기의 맵에 유저 A는 (1, 1) 위치에서 출발하고, 유저 B는 (10, 10) 위치에서 출발해 매 초마다 북, 동, 남, 서 중 한 방향으로 각각 이동한다. 맵의 곳곳에 배터리 차저(BC)가 존재하는데, 해당 차저의 커버리지(색칠된 영역)에 들어서면 해당 차저의 성능만큼 유저의 스마트폰이 충전된다.
- 이 때 유저 A, B가 같은 배터리 차저 커버리지에 존재할 수 있는데, 이 경우에는 해당 차저 충전량이 A, B에게 **균등하게 반반씩 분배되어** 들어간다. 
- 위 그림에서 T=11의 경우 유저 A는 BC 1과 BC 3 커버리지에 존재하고, 유저 B는 BC 1 커버리지에 존재한다. 이 때 A와 B 모두 BC 1을 이용하면 A 차저의 충전량(100)을 반반씩(50씩) 나눠갖지만, A는 BC 3(충전량 70)을 이용하고 B는 BC 1을 이용하면 A는 70, B는 100만큼 충전해 이 방법이 더 효율적이다.
BC 정보와 유저 A, B의 이동 정보가 주어졌을 때 모든 사용자가 충전한 양의 …

28-9kyo-hwang

---

Dolchae/DFS&BFS/2644 촌수계산.py
Dolchae/README.md

[2644 촌수계산](https://www.acmicpc.net/problem/2644)
1시간
주어진 두 사람의 촌수를 계산하는 문제이다. 
- 부모와 자식 사이가 1촌으로 정의되므로 나와 할아버지는 2촌, 아버지 형제들과 할아버지는 1촌, 나와 아버지 형제들은 3촌이 된다.
입력
- 첫째 줄에 전체 사람 수, 둘째 줄에 촌수를 계산해야 하는 두 사람의 번호(a,b), 셋째 줄에 관계의 수 m, 넷째 줄부터는 부모 자식 간의 관계 두 번호 x,y가 나온다.
- 이때 x가 y의 부모가 된다.
출력
- a,b의 촌수를 계산해 출력하면 되는데, 친척 관계가 전혀 없을 경우에는 -1을 출력한다.
예제 1)
<br>
```python
a,b = map(int, input().split())
node_num = int(input())
graph = [[] for _ in range(n+1)]
visited = [False] * (n+1)
result = []
```
- 첫째 줄에 전체 사람 수(n), 둘째 줄에 촌수를 계산해야 하는 두 사람의 번호(a,b), 셋째 줄에 관계의 수(node_num)를 입력받는다.
- 관계들을 저장할 graph 2차원 배열과 방문 여부를 확인할 visited, 결과를 저장할 result 리스트를 선언한다.
<br>
```python
for _ in range(node_num):
x, y = map(int, input().split())
graph[x].append(y)
graph[y].append(x)
```
- 관계의 수만큼 for문을 반복하며 x와 y를 …

30-Dolchae

---

xxubin04/README.md
xxubin04/그리디/134_Gas Station.py

[134: Gas Station](https://leetcode.com/problems/gas-station/description/?envType=study-plan-v2&envId=top-interview-150)
<br>
1시간 + α
<br>
<br>
**주어지는 주유소를 전부 순회할 수 있는 시작 주유소 번호를 반환하는 문제**이다.
`주유소 번호 = 인덱스 번호`라는 것을 주의하자.
<br>
`Ex1`에서의 gas = [1, 2, 3, 4, 5], cost = [3, 4, 5, 1, 2]이다. 
(`gas[i]` = 각 주유소에서 얻는 가스양, `cost[i]` = 각 주유소로 가기 위해 쓰는 가스양)
3번 주유소(인덱스 = 3)에서 시작해보자. 
탱크에 가스를 저장한다고 치기 위해 변수 `tank`를 만들자. 그리고 탱크는 처음에 비어있기에 `tank = 0`으로 지정해준다.
- gas = 4, cost = 1, index = 3
- 3번 주유소 -> tank += 4 (4) -> 4번 주유소로 가기 -> tank -= 1 (3) 
- gas = 5, cost = 2, index = 4
- 4번 주유소 -> tank += 5 (8) -> 0번 주유소로 가기 -> tank -= 2 (6)
- gas = 1, cost = 3, index = 0
- 0번 주유소 -> tank += 1 (7) -> 1번 주유소로 가기 -> tank -= 3 (4)
- gas = 2, cost = 4, index = 1
- 1번 주유소 -> tank += 2 (6) -> 2번 주유소로 가기 -> tank -= 4 (2) …

31-xxubin04

---

9-kyo-hwang/Greedy/23296 엘리베이터 조작.cpp
9-kyo-hwang/README.md

[23296 엘리베이터 조작](https://www.acmicpc.net/problem/23296)
약 3시간
1명만 태울 수 있는 엘리베이터가 있다. 이 엘리베이터는 관리실에서만 조작 가능하며, **1층에서 출발**한다.
위와 같이 한 층 당 한 명씩 기다리고 있을 때, 사람들을 모두 원하는 층에 내려주기 위해 **버튼을 눌러야 하는 최소 횟수와 눌러야하는 버튼 순서**를 출력하라. 
알고리드미 디코 지박령 @pknujsp @tgyuuAn 이 막 얘기하고 있길래 뭔가 하고 봤는데
나도 당해버렸다.
위상정렬 문제라길래 그거를 고려해서 코드를 막 짰었는데, 솔직히 위상정렬 아닌 것 같다. 사실상 그리디 문제라고 생각된다.
원하는 층에 내려주기 위해 눌러야 하는 버튼 횟수를 최소로 만드는 것이 목적이다. 위의 예시를 다시 한 번 확인해보자.
1층 사람은 4층, 2층 사람은 4층, 3층 사람은 1층, 4층 사람은 5층, 5층 사람은 2층을 가야 한다.
만약 1층부터 각 사람마다 원하는 층을 바로바로 데려다 준다고 하면, 버튼은 4 - 2 - 4 - 3 - 1 - 4 - 5 - 2 이렇게 눌러져야 할 것이다.
- 1층에서 출발하는데, 1층 사람은 4층을 가야하므로 4룰 눌러 4층으로 보냄. 그 후 2층으로 가기 위해 다시 2를 누름
- 2층 사람은 4층으로 가야하므로 4를 눌러 4층으로 보냄. 그 후 3층으로 가기 위해 3을 누름
- 3층 사람은 1층으로 가야하므로 1를 눌러 1층으로 보냄. 그 후 4창으로 가기 위해 4를 누름
- 4층 사람은 5층으로 가야하므로 5를 눌러 5층으로 보냄. 바로 5층이므로 5층 …

30-9kyo-hwang

---

xxubin04/README.md
xxubin04/수학/172_Factorial Trailing Zeroes.py

[172번: Factorial Trailing Zeroes](https://leetcode.com/problems/factorial-trailing-zeroes/)
<br>
15분
<br>
> **Trailing zeroes의 개수**를 반환하는 문제
여기서 주의해야 하는 것이 **Trailing Zeroes**이다. 
나도 단순히 팩토리얼의 0의 개수를 반환하는 문제인줄 알았는데 계속 틀리길래 Trailing Zeroes를 검색해보고 나서 알았다. 
**Trailing Zeroes**은 뒤에 붙은 0을 말한다.
예시를 보면 더 이해하기 쉬울 것이다.
123**000** -> Trailing Zeroes의 개수는 **3**
12003**0** -> Trailing Zeores의 개수는 **1**
102003 -> Trailing Zeroes의 개수는 **0**
<br>
Trailing Zeroes가 뭔지 알고있다면 코드로 구현하는 것은 매우 쉬울 것이다.
생각보다 쉽게 풀려 PR 올려도 되나 고민하긴 했습니다....
```python
class Solution(object):
def trailingZeroes(self, n):
total = 1
while n >= 2:
total *= n
n -= 1
cnt = 0
for i in reversed(list(str(total))):
if i == '0':
cnt += 1
else:
break
return cnt
```
팩토리얼 n! 에서의 n은 주어지므로 `while n >= 2`로 팩토리얼 n!을 구하여 total에 저장한다.
total의 각 자릿수를 …

32-xxubin04

---

gjsk132/Prefix Sum/21758 꿀 따기.py
gjsk132/README.md

[백준 21758 : 꿀 따기](https://www.acmicpc.net/problem/21758)
70분
🎯 문제 이해
---
**알고리즘 유형 : 누적 합 (Prefix Sum)**
> **문제 요약**
> 각 칸마다 얻을 수 있는 꿀이 있다.
> 칸 중에서 서로 다른 2칸에 벌들 놓고, 또 다른 칸에는 벌통을 놓는다.
> 벌은 벌통이 있는 방향으로 가면서, 각 칸에 얻을 수 있는 꿀을 얻는다.
>
> 벌이 있는 칸은 꿀을 얻을 수 없고, 벌통이 있는 칸은 꿀을 얻을 수 있다.
>
> 예시
> <img src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/b600bddc-1fd1-44d7-a2bd-6b94c377cef3" width = 300 >
> 위에 연한 회색에 벌이 있고, 진한 회색에 벌통이 있다고 했을 때,
> 각각의 벌은 ( 9 + 4 + 4 + 9 + 9 = 35 ) ( 4 + 9 + 9 = 22 )의 꿀을 벌통을 가지고 오는 걸 알 수 있다.
**유형 접근**
**누적 합 (Prefix Sum)** : 벌이 지나온 길을 다 더하는 문제이기 때문에 리스트의 구간합을 구하는 누적합을 사용하기 좋다
**문제 접근**
3가지 케이스에서 확인해야 하지만, 크게 보면 2가지 케이스로 나뉠 수 있다.
1. 벌통이 가운데 있을 때
2. 벌통이 맨 끝에 있을 때 ( 왼쪽 / 오른쪽 )
**벌통이 가운데 있는 경우**에는 벌은 양쪽 끝에 있어야 가장 많은 꿀을 얻을 수 있다.
> 벌통 왼쪽에 꿀이 많으면 그쪽에 벌을 2마리 둬야하는거 …

25-gjsk132

---

Dolchae/README.md
Dolchae/정렬/1431 시리얼 번호.py

[1431 시리얼 번호](https://www.acmicpc.net/problem/1431)
1시간
시리얼 번호를 정렬하는 프로그램을 구현하는 문제이다. 정렬은 다음과 같이 이루어진다.
1. 길이는 짧은 것이 먼저(앞에) 온다.
2. 길이가 같다면 각 모든 자릿수의 합이 작은 것이 먼저 온다.(숫자인 것만 더함)
3. 1,2로도 비교할 수 없다면 사전순으로 비교한다. 이때 숫자가 알파벳보다 사전순으로 더 앞이다.
<br>
```python
import sys
n = int(input().strip())
serial = []
serial.append(input().strip())
```
n에 시리얼 번호의 개수, serial 리스트에 시리얼 번호를 모두 저장한다.
<br>
```python
def get_number_sum(s):
number_sum = 0
for char in s:
if char.isdigit():
number_sum += int(char)
return number_sum
```
후의 정렬에서 각 번호의 숫자합을 구할 때 쓸 함수이다. 문자열 s를 받아 문자 char가 정수라면 그 값을 number_sum에 저장한 후 이 값을 넘긴다.
<br>
```python
for i in range(n-1):
for j in range(i+1, n):
if len(serial[i]) > len(serial[j]): #1
serial[j], serial[i] = serial[i], serial[j]
elif …
```

33-Dolchae

---

9-kyo-hwang/Greedy/2023 KAKAO BLIND RECRUITMENT 미로 탈출 명령어.cpp
9-kyo-hwang/Greedy/23296 엘리베이터 조작.cpp
9-kyo-hwang/README.md

[2023 KAKAO BLIND RECRUITMENT 미로 탈출 명령어](https://school.programmers.co.kr/learn/courses/30/lessons/150365)
거의 3시간?
n x m 격자 미로에서, (x, y)에서 출발해 (r, c)로 이동해야 한다. 단,
1. 격자의 바깥으로는 나갈 수 없다.
2. 인접한 상, 하, 좌, 우 격자로 한 칸씩 이동할 수 있다.
3. (x, y)에서 (r, c)까지 **이동하는 거리가 총 k여야 한다**. 이때, (x, y)와 (r, c)격자를 포함해 같은 격자를 **두 번 이상 방문해도 된다.**
4. 미로에서 탈출한 경로를 문자열로 나타냈을 때, **문자열이 사전 순으로 가장 빠른 경로**로 탈출해야 한다.
예를 들어 다음과 같이 3 x 4 격자가 있다고 가정해보자.
```
....
..S.
E...
```
미로의 좌측 상단은 (1, 1)이고 우측 하단은 (3, 4)이다. .은 빈 공간, S는 출발 지점, E는 탈출 지점을 의미한다.
이동 경로를 다음과 같이 문자열로 바꿀 수 있다고 할 때,
- l: 왼쪽으로 한 칸 이동
- r: 오른쪽으로 한 칸 이동
- u: 위쪽으로 한 칸 이동
- d: 아래쪽으로 한 칸 이동
이동해야 하는 거리 k가 5라면 다음과 같은 경로로 탈출할 수 있다.
1. lldud
2. ulldd
3. rdlll
4. dllrl
5. dllud
6. ...
이때 dllrl보다 사전 순으로 빠른 경로로 탈출할 수는 없으므로, "dllrl"을 return 한다.
만약 위 조건대로 미로를 탈출할 수 없는 경우 …

31-9kyo-hwang

---

xxubin04/Heap/1715_카드 정렬하기.py

[백준 1715번 : 카드 정렬하기](https://www.acmicpc.net/problem/1715)
<br>
15분
<br>
카드가 10장, 20장, 40장 있다면, (10 + 20) + (30 + 40) = 100번의 비교로 카드를 정리하게 된다.
처음 10장과 20장을 비교할 때, 30번의 비교를 하게 된다.
그리고 30장과 40장의 카드를 비교할 때, 70번의 비교를 하게 된다.
-> 총 30번 + 70번 = **100번**의 비교
하지만, 10장과 40장을 먼저 비교하게 되면 50번의 비교를 하게 된다.
그리고 20장과 50장의 카드를 비교할 때, 70번의 비교를 하게 된다.
-> 총 50번 + 70번 = **120번**의 비교
그러므로, 총 30번 + 70번 = 100번의 비교가 최소의 비교 횟수이다.
<br>
위의 예시를 보면, 간단한 규칙을 알 수 있다.
> 카드의 장수가 작은 것들부터 비교를 해주게 되면 비교횟수가 최소가 된다.
왜냐하면 10장, 20장, 40장의 카드가 있을 때, (10 + 20) + (30 + 40) = 100이다.
이때, 30은 10 + 20이므로 맨 처음 비교해서 합친 카드들은 40장의 카드와 합칠 때, 다시 한번 비교하게 된다. 그러므로, 적은 장수의 카드들을 여러 번 비교할 수록 최소한의 비교횟수를 가질 수 있다.
<br>
```python
from heapq import heapify, heappush, heappop
input = open(0).readline 
num = []
total = 0
heapify(num)
for i in range(n := …
```

36-xxubin04

---

Dolchae/README.md
Dolchae/수학/11653 소인수분해.py

[11653 소인수분해](https://www.acmicpc.net/problem/11653)
15분
하나의 정수 N을 입력 받고 소인수분해한 결과를 출력하는 문제이다.
<br>
```python
for i in range(2, n+1):
while True:
if not n%i == 0:
break
print(i)
n /= i
```
n을 입력 받고 2~n까지 for문을 진행한다.
n이 i로 나눠지지 않을 때까지 while문을 진행하며 i(소인수)를 출력하고, n을 i로 나누어준다.
<br> 
6개월 전에 C로 풀었다가 시간초과 났던 문제인데 파이썬으로 다시 풀어보았다. 오늘..은 조금 쉬어가겠습니다......🥲 상대적으로 쉬운 문제인만큼 시간 효율이 중요한 것 같은데 더 잘하시는 우리 팀원 분들이 더 좋은 코드로 올려주시면 좋을 것 같아요☺️👍

37-Dolchae

---

Dolchae/README.md
Dolchae/수학/2407 조합.py
Dolchae/힙/11286 절댓값 힙.py

[2407 조합](https://www.acmicpc.net/problem/2407)
30분
n과 m이 주어질 때 nCm을 출력하는 문제이다.
<br>
<br>
```python
import sys
n,m = map(int,input().split())
def factorial(num):
result = 1
for i in range(1,num+1):
result *= i
return result
print(factorial(n)//(factorial(n-m)*factorial(m)))
```
n과 m을 입력받고, 팩토리얼을 계산하는 함수를 구현한다. 그리고 조합의 공식에 따라 factorial함수를 이용해 값을 프린트해준다.
<br>
늦어서 죄송합니다...🥲

40-Dolchae

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/README.md

[16934 게임 닉네임](https://acmicpc.net/problem/16934)
30분
$1 \le N \le 100,000$개의 문자열이 들어온다. 이 문자열은 알파벳 소문자로만 이루어져 있으며, 길이는 10을 넘지 않는다.
이 문자열들을 이용해 내부에 저장할 별칭을 만들고자 한다. 별칭은 다음과 같은 규칙으로 구성한다.
- 별칭은 문자열 접두사(Prefix) 중 가장 길이가 짧은 것을 사용한다. 이 때, 접두사가 이전에 등장한 문자열의 접두사가 아니어야 한다. 
- 가능한 별칭이 없는 경우, 해당 문자열이 들어온 시점까지 들어온 같은 문자열 수 x를 계산해 이용한다. x가 1인 경우 문자열을 별칭으로 사용하고, 2 이상인 경우에는 문자열 뒤에 x를 붙여 별칭으로 사용한다.
예를 들어 $N = 5$이고 문자열들이 ["baekjoon", "startlink", "bakejoon", "beakjoon", "baekjoon"] 주어졌다면
- "baekjoon"의 별칭은 "b"가 된다.
- "startlink"의 별칭은 "s"가 된다.
- "bakejoon"의 별칭은 "bak"이 된다.
- "beakjoon"의 별칭은 "be"가 된다.
- "baekjoon"의 별칭은 "baekjoon2"가 된다.
N개의 문자열이 주어졌을 때, 들어온 순서대로 별칭을 한 줄에 하나씩 출력하라.
설명만 보면 [Trie 자료구조](https://velog.io/@kimdukbae/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-%ED%8A%B8%EB%9D%BC%EC%9D%B4-Trie)를 사용하는 것이 가장 …

54-9kyo-hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp

[15681 트리와 쿼리](https://acmicpc.net/problem/15681)
40분
간선에 가중치와 방향성이 없는 임의의 루트 있는 트리가 주어졌을 때, 다음 쿼리를 수행하는 프로그램을 작성하라.
- 정점 U를 루트로 하는 서브트리에 속한 정점의 수를 출력한다.
- 트리 정점의 수 $2 \le N \le 10^5$
- 루트 번호 $1 \le R \le N$
- 쿼리 수 $1 \le Q \le 10^5$
쿼리 수가 많기 때문에 매 쿼리마다 서브 트리에 속한 정점 수를 구할 수는 없다. 
결국 미리 계산해서 결과를 캐싱해놔야 하는데, 이런 식의 아이디어가 적용된 문제를 보통 "트리 DP"란 유형으로 묶인다.
기본적으로는 DFS 순회이다. 굳이 트리 자료구조를 구현하지 않더라도, **방문 처리**만 해준다면 트리를 순회하는 것과 같은 효과를 얻을 수 있다. 
즉 루트에서 DFS 함수를 호출하면, 리프 노드까지 내려갔다가 올라오면서 부모 노드들의 값을 처리하는 형태를 띄게 된다.
문제에서 주어진 입력은 루트가 5번이고, 엣지 정보가 다음과 같다.
```
1 3
4 3
5 4
5 6
6 7
2 3
9 6
6 8
```
이 정보를 통해 인접 리스트를 구성하면 다음과 같다.
```
node[1] - 
node[2] -
node[3] - [1] - [2]
node[4] - [3]
node[5] - [4] - [6]
node[6] - [5] - [7] - [9] - [8]
node[7] -
node[8] -
node[9] -
```
이제 5번 노드부터 탐색을 시작해 방문 처리를 하며 값을 구한 뒤, 그 값을 …

56 9kyo hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Dynamic Programming/17070 파이프 옮기기 1.cpp
9-kyo-hwang/Graph Traversal/무인도 여행.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/Implementation/테이블 해시 함수.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp
9-kyo-hwang/Trie/14725 개미굴.cpp

10분
1 x 1크기의 사각형들로 이루어진 직사각형 격자 형태의 지도 정보가 주어진다. 격자의 각 칸에는 'X' 또는 1에서 9 사이의 자연수가 적혀있다.
지도의 각 칸에서 상, 하, 좌, 우로 연결되는 칸에 적힌 숫자를 모두 합한 값들을 구하고자 한다.
예를 들어, `["X591X","X1X5X","X231X", "1XXX1"]`와 같이 문자열로 주어진다면 이는 다음과 같은 지도를 나타내는 것이다.
연결된 칸들의 값을 합치면 다음과 같으며
이는 `[1, 1, 27]`로 저장할 수 있다.
지도를 나타내는 문자열 배열 maps가 매개변수로 주어질 때, 숫자 칸들을 연결해 얻을 수 있는 숫자들을 배열에 오름차순으로 담아 return 하는 solution 함수를 완성하라. 만약 숫자 칸이 존재하지 않는다면 -1을 배열에 담아 return 하라.
그래프 연결 요소 관련 문제임을 알 수 있다. 연결요소 관련된 문제는 여러 유형이 있으며, 여기서는 각 연결요소의 '크기'를 구하는 문제로 해석할 수 있다.
각 칸(즉, 그래프 노드)의 크기가 1 ~ 9 사이이고, 상/하/좌/우로 노드가 연결된 그래프로 해석할 수 있다.
문제 해석이 완료됐다면, 코드는 쉽게 구현할 수 있다.
```cpp
vector<int> DaysofStay;
for(int i = 0; i < Maps.size(); ++i)
{
for(int j = 0; j < Maps[0].size(); ++j)
{
if(Maps[i][j] != 'X')
{
DaysofStay.emplace_back(Merge(Maps, i, j));
}
}
}
```
무인도가 아닌 …

62-9kyo-hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Dynamic Programming/17070 파이프 옮기기 1.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp
9-kyo-hwang/Trie/14725 개미굴.cpp

현재 나와 엘리베이터는 `storey`($1 \le storey \le 100,000,000$) 층에 있다. $-1, +1, -10, +10, -100, +100, ...$과 같이 절대값이 $10^c$($c \ge 0$) 형태인 정수들이 적힌 버튼 엘리베이터를 통해 0층으로 가고자 한다.
해당 버튼을 누르면 현재 층 수에 버튼에 적혀 있는 값을 더한 층으로 이동하게 되는데, 엘리베이터가 위치해 있는 층과 버튼의 값을 더한 결과가 0보다 작으면 엘리베이터는 움직이지 않는다.
엘리베이터를 움직이기 위해서 버튼 한 번당 마법의 돌 한 개를 사용한다. 
- 예를 들어, 16층에서 0층으로 가려면 -1이 적힌 버튼을 6번, -10이 적힌 버튼을 1번 눌러 마법의 돌 7개를 소모하여 0층으로 갈 수 있다.
- 하지만, +1이 적힌 버튼을 4번, -10이 적힌 버튼 2번을 누르면 마법의 돌 6개를 소모하여 0층으로 갈 수 있다. 
이와 같이 어떤 층에서 엘리베이터를 타고 0층으로 내려가는데 필요한 **마법의 돌의 최소 개수**를 알고자 한다.
현재 층을 나타내는 정수 `storey`가 주어졌을 때, 0층으로 가기 위해 필요한 마법의 돌의 최소값을 return 하도록 solution 함수를 완성하라.
처음에 문제를 딱 보자마자 [1로 만들기](https://www.acmicpc.net/problem/1463) 문제나 [숨바꼭질](https://www.acmicpc.net/problem/1697) 거의 비슷해 보여서 거리 테이블과 queue를 이용한 BFS로 풀려고 했으나...
<details><summary>BFS 시도 …

59-9kyo-hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Dynamic Programming/17070 파이프 옮기기 1.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp
9-kyo-hwang/Trie/14725 개미굴.cpp

1시간 조금 넘게...?
과제 수행에 대한 정보가 [name, start, playtime] 형태로 주어진다. name은 과제 이름, start는 `hh:mm` 형태의 시작 시각 문자열, playtime은 과제를 완료하는 데 걸리는 시간이다.
시간 순서에 맞게 과제를 시작하는데, 다음과 같은 규칙이 존재한다.
- 과제를 진행하는 도중에 새로운 과제를 시작해야 하는 시각이 되면, 기존 과제는 중단하고 새로운 과제를 시작한다.
- 진행 중이던 과제를 끝냈을 때, 잠시 중단했던 과제가 있다면 해당 과제를 마저 한다. 단 이 때 새로운 과제가 존재한다면, 중단했던 과제를 하지 않고 새로운 과제를 먼저 한다.
- 중단했던 과제가 여러 개라면 가장 최근에 멈춘 과제부터 시작한다.
과제를 끝낸 순서대로 이름을 배열에 담아 return하라.
문제에서 제시한 로직을 차분히 코드로 구현하면 되는 문제다.
```cpp
class FPlan
{
public:
string Name;
int Start;
int Playtime;
FPlan() {}
FPlan(const string& InName, const string& InStart, const string& InPlaytime)
{
Name = InName;
Start = stoi(InStart.substr(0, 2)) * 60 + stoi(InStart.substr(3, 2));
Playtime = stoi(InPlaytime);
}
const bool operator<(const FPlan& Rhs) const
{
return Start < Rhs.Start;
}
}; …
```

60-9kyo-hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Dynamic Programming/17070 파이프 옮기기 1.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/Implementation/테이블 해시 함수.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp
9-kyo-hwang/Trie/14725 개미굴.cpp

15분
2차원 행렬로 표현되는 테이블이 주어진다. 각각의 열은 컬럼, 행은 튜플을 나타내며, 첫 번째 컬럼은 모든 튜플에 대해 그 값이 중복되지 않도록 보장된다.
이 테이블에 대한 해시 함수를 다음과 같이 정의한다.
1. 해시 함수는 `col`, `row_begin`, `row_end`를 입력받는다.
2. 테이블의 튜플을 `col`번째 컬럼 값 기준으로 오름차순 정렬한다. 단, 그 값이 동일한 경우 기본키인 첫 번째 컬럼 값을 기준으로 내림차순 정렬한다.
3. 정렬된 데이터에서 $S_i$를 i번째 행 튜플에 대해 각 컬럼 값을 i로 나눈 나머지들의 합으로 정의한다.
$S_i =$ data[i][0] $mod \space i$ + data[i][1] $mod \space i$ + ...
4. `row_begin` $\le i \le$ `row_end`인 모든 $S_i$를 누적하여 bitwise XOR한 값을 해시 값으로 반환한다.
테이블의 해시 값을 return하라.
- $1 \le$ `data` 길이 $\le 2,500$
- $1 \le$ `data`의 원소 길이 $\le 500$
- $1 \le$ `data[i][j]` $\le 1,000,000$, `data[i][j]`는 $i+1$번째 튜플 $j+1$번째 컬럼 값
- $1 \le col \le$ `data`의 원소 길이
- $1 \le$ `row_begin` $\le$ `row_end` $\le$ `data` 길이
문제에서 설명한 대로 구현하면 되는 쉬운 문제이다.
```cpp
sort(Data.begin(), Data.end(), [&](const …
```

61 9kyo hwang

---

9-kyo-hwang/Binary Search/13397 구간 나누기 2.cpp
9-kyo-hwang/Graph Traversal/무인도 여행.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/Implementation/테이블 해시 함수.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Trie/14725 개미굴.cpp

1시간 트라이하고 레퍼런스 확인 
N개의 수로 이루어진 1차원 배열이 있다. 이 배열을 M개 이하의 구간으로 나누어서 구간의 점수의 최댓값을 최소로 하려고 한다. 구간은 다음과 같은 조건을 만족해야 한다.
1. 하나의 구간은 하나 이상의 연속된 수들로 이루어져 있다.
2. 배열의 각 수는 모두 하나의 구간에 포함되어 있어야 한다.
구간의 점수란 구간에 속한 수의 최댓값과 최솟값의 차이이다.
예를 들어, 배열이 [1, 5, 4, 6, 2, 1, 3, 7] 이고, M = 3인 경우가 있다.
이때, [1, 5], [4, 6, 2], [1, 3, 7]로 구간을 나누면 각 구간의 점수는 4, 4, 6점이 된다. 이때, 최댓값은 6점이다.
만약, [1, 5, 4], [6, 2, 1], [3, 7]로 구간을 나누었다면, 각 구간의 점수는 4, 5, 4점이 되고, 이때 최댓값은 5점이 된다.
두 경우 중에서 최댓값이 최소인 것은 5점인 것이고, 5점보다 최댓값을 작게 만드는 방법은 없다.
배열과 M이 주어졌을 때, 구간의 점수의 최댓값의 최솟값을 구하는 프로그램을 작성하시오.
M개 이하의 구간으로 배열을 나눠야 하는데, 이를 무식하게 다 다루기엔 경우의 수가 너무 많다. 단순히 M이 최대 N까지 가기도 하고, 심지어 M "이하"이기 때문에 경우의 수는 폭발적으로 늘어난다.
문제에서 구하고자 하는 건 구간 점수 최대값 중 최소값인데, 여기서 구간 점수(해당 구간의 최대값 - 최소값)에 주목한다. 
이 점수 차이를 탐색의 key로 하여, "전체 배열을 M개 이하로 분할할 수 있는" 것들 중 가장 작은 점수를 구해내면 …

63-9kyo-hwang

---

9-kyo-hwang/Binary Search/13397 구간 나누기 2.cpp
9-kyo-hwang/Binary Search/징검다리.cpp
9-kyo-hwang/Graph Traversal/무인도 여행.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/Implementation/테이블 해시 함수.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Trie/14725 개미굴.cpp

직전 PR에서 이진 탐색 문제를 풀었는데, 그 때 프로그래머스 고득점 Kit에서 이분탐색 카테고리 문제 하나를 안 풀었던 기억이 나서 이 문제로 선정했다.
그런데 운 좋게도(?) 접근 방식이 거의 동일하다. 그래서 별도의 레퍼런스 참고 없이 해결할 수 있었다 :D
도착지점까지의 거리가 최대 **10억**이라 선형 탐색으로는 해결할 수 없다. 즉 이진 탐색을 적용해야 하는데, 지난번과 비슷한 접근법을 적용한다.
distance의 하한(low)을 1, 상한을 distance(high)로 설정한다. 이 범위 사이에 있는 값을 가지고 추정을 하는데, 여기서 추정 거리값은 "모든 돌은 최소한 이 거리만큼 떨어져있다"로 간주한다. 
첫 번째 예시를 들어보자: [2, 14, 11, 21, 17], distance=25.
- distance까지 돌 지점에 추가한 뒤 정렬을 하면 다음과 같다: [2, 11, 14, 17, 21, 25]
- 추정 거리의 하한은 1, 상한은 25로 설정한다.
그러면 탐색은 다음과 같이 진행한다.
1. 첫 번째 추측값은 (1 + 25) / 2 = 13이다. 이제 위치 0에서 시작해서 각 돌 간 간격을 확인한다.
2. 두 번째 추측값은 (1 + 12) / 2 = 6이다. 위와 같은 과정으로 상한이 감소한다.
3. 세 번째 추측값은 (1 + 5) / 2 = 3이다.
...
이런 식으로 하한이 증가할 때 조건을 만족하는 것이므로 값을 기록한다.
```cpp
#include <string>
#include <algorithm>
using namespace std;
int …
```

64-9kyo-hwang

---

9-kyo-hwang/Binary Search/13397 구간 나누기 2.cpp
9-kyo-hwang/Binary Search/징검다리.cpp
9-kyo-hwang/Graph Traversal/무인도 여행.cpp
9-kyo-hwang/Greedy/디펜스 게임.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/Implementation/테이블 해시 함수.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Trie/14725 개미굴.cpp

최대 $1,000,000$ 라운드에 걸쳐 적들이 들어온다. 그리고 최대 $500,000$라운드를 `무적권`을 사용해 병사 소모를 0으로 만들 수 있다.
백트래킹 등을 이용해 모든 경우의 수를 구하기에는 숫자가 너무 크다. 라운드가 최대 $1,000,000$이기 때문에 $O(N^2)$ 풀이법도 불가능하다. 즉 $O(N logN)$ 풀이법을 사용해야 한다.
직관적으로 생각했을 때는, 무적권은 가능한 "적의 수가 많은 라운드"에 사용하는 것이 좋다. 그러나 이러한 방법은 "선형탐색"으론 불가능하고, 그렇다고 위에서 언급한 것처럼 모든 경우의 수를 다 확인할 수는 없다.
따라서 여기서는 **우선순위 큐**를 사용한다. 원리는 간단하다.
1. 일단은 매 라운드마다 등장하는 적 수에 맞게 병사를 소모한다. 그리고 동시에 적 수를 **MaxHeap**에 기록한다.
2. 만약 남은 병사가 존재한다면 이어서 라운드를 진행한다.
3. 남은 병사가 하나도 없다면 아래 로직을 수행한다.
i. 만약 더 이상 무적권을 사용할 수 없다면 라운드를 중단한다.
ii. 아니라면 MaxHeap에서 지난 라운드 중 가장 적이 많았던 라운드의 적 수를 pop해 그 수 만큼 병사 수를 복원시키고 남은 무적권 횟수를 1 차감시킨다.
이런 식으로 MaxHeap을 사용하면 $O(logN)$ 시간복잡도로 지난 라운드 중 가장 적이 많은 라운드 정보를 얻어올 수 있게 된다.
```cpp
#include <string>
#include <queue>
using namespace std;
int solution(int N, …
```

65-9kyo-hwang

---

9-kyo-hwang/Binary Search/13397 구간 나누기 2.cpp
9-kyo-hwang/Binary Search/징검다리.cpp
9-kyo-hwang/Graph Traversal/무인도 여행.cpp
9-kyo-hwang/Greedy/디펜스 게임.cpp
9-kyo-hwang/Greedy/마법의 엘리베이터.cpp
9-kyo-hwang/Implementation/과제 진행하기.cpp
9-kyo-hwang/Implementation/테이블 해시 함수.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Sliding Window/할인 행사.cpp
9-kyo-hwang/Trie/14725 개미굴.cpp

10일 동안 회원 자격이 부여된다. 회원은 매일 한 가지 제품을 할인받을 수 있다. 제품은 하루에 하나만 구매할 수 있다.
예를 들어, 14일간 [치킨, 사과, 사과, 바나나, 쌀, 사과, 돼지고기, 바나나, 돼지고기, 쌀, 냄비, 바나나, 사과, 바나나] 순서대로 제품을 할인한다고 하자. 나는 바나나 3개, 사과 2개, 쌀 2개, 돼지고기 2개, 냄비 1개를 할인해서 사고 싶다.
1.  첫째 날부터 열흘 간에는 냄비가 할인하지 않기 때문에 첫째 날에는 회원가입을 하지 않는다.
2. 둘째 날부터 열흘 간에는 바나나를 원하는 만큼 할인구매할 수 없기 때문에 둘째 날에도 회원가입을 하지 않는다.
3. 셋째 날, 넷째 날, 다섯째 날부터 각각 열흘은 원하는 제품과 수량이 일치한다.
원하는 제품을 모두 할인 받을 수 있는 날짜는 셋째 날, 넷째 날, 다섯째 날로 총 3일이다.
이와 같이 회원등록시 원하는 제품을 모두 할인 받을 수 있는 회원등록 날짜의 총 일수를 return 하는 solution 함수를 완성해야 한다. 가능한 날이 없으면 0을 return 한다.
주어지는 총 제품 개수가 최대 100,000개이기 때문에, 매번 10일 간 할인하는 품목 수량을 계산하기엔 시간이 너무 오래 걸린다.
할인 기간이 "10일"로 고정되어 있기 때문에, 여기서는 [**슬라이딩 윈도우**](https://www.geeksforgeeks.org/window-sliding-technique/) 기법을 사용하는 것이 적절하다.
단, 여기서는 문자열 원소를 카운팅해야 하기 때문에 **map** 자료구조를 사용해 응용한다.
```cpp …
```

66-9kyo-hwang

---

9-kyo-hwang/Binary Search/징검다리.cpp
9-kyo-hwang/Graph Traversal/퍼즐 조각 채우기.cpp
9-kyo-hwang/Greedy/2024 KAKAO WINTER INTERNSHIP n + 1 카드게임.cpp
9-kyo-hwang/Greedy/디펜스 게임.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Sliding Window/할인 행사.cpp

1 ~ `n` 사이 수가 적인 카드가 하나씩 있는 카드 뭉치와 동전 `coin`개를 가지고 있다. 다음과 같은 순서로 게임을 진행한다.
1. 처음에 카드 뭉치에서 `n/3`장을 뽑아 모두 가진다. `n`은 6의 배수이다.
2. 1라운드부터 진행하며, 각 라운드가 시작할 때마다 카드 2장을 뽑는다. 카드 뭉치에 남은 카드가 없다면 게임은 종료된다. 뽑은 카드 한 장 당 동전을 하나 소모해 가지거나, 동전을 소모하지 않고 버릴 수 있다.
3. 카드에 적힌 수의 합이 `n+1`이 되도록 카드 2장을 내고 다음 라운드를 진행할 수 있다. 만약 카드 2장을 낼 수 없다면 게임은 종료된다.
<details><summary>예시 설명</summary>
<p>
예를 들어 `n` = 12, `coin` = 4이고 [3, 6, 7, 2, 1, 10, 5, 9, 8, 12, 11, 4] 순서대로 카드를 뽑도록 카드 뭉치가 주어진다.
처음에 3, 6, 7, 2 카드 4장(= `n/3`)과 동전 4개(= `coin`)를 가지고 시작한다. 다음 라운드로 진행하기 위해 내야 할 카드 두 장에 적힌 수의 합은 13(= `n+1`)이다. 다음과 같은 방법으로 최대 5라운드까지 도달할 수 있다.
1. 1라운드에서 뽑은 카드 1, 10을 동전 두 개를 소모해서 모두 가진다. 카드 3, 10을 내고 다음 라운드로 진행한다. 이때 손에 남은 카드는 1, 2, 6, 7이고 동전이 2개 남는다.
2. 2라운드에서 뽑은 카드 5, 9를 동전을 소모하지 않고 모두 버린다. 카드 6, 7을 내고 다음 라운드로 진행한다. 이때 손에 남은 카드는 1, 2고 …

68-9kyo-hwang

---

gjsk132/Implementation/1034 램프.py
gjsk132/README.md

[백준1034  : 램프](https://www.acmicpc.net/problem/1034)
20분
🎯 문제 이해
---
> **문제 요약**
> 탁자의 가로 세로가 주어지고, 그 위에 전구가 켜졌는지 아닌지를 주어진다.
> 스위치를 켜고 끄는데, 주어진 횟수만큼 한 열의 스위치 상태를 반대로 바꾼다.
> 전구가 모두 켜져있는 행의 최대값을 구하면 된다.
한 번 바꿀 때, 하나의 열의 모든 전구의 상태가 바뀐다.
로직을 알고나면 간단하게 풀 수 있다.
열의 상태가 다르면, 전구를 몇 번 키더라도 둘 다 켜지는 상태가 될 수 없다.
쉽게 말해
[1, 0, 0]과 [0,1,0]이 있을 때,
하나를 [1,1,1]로 만들면 다른 하나는 다 킬 수 없다는 말이다.
따라서, 열의 상태가 같은 것들끼리 묶어서 확인하면 된다.
그 후에 갯수가 많은 것부터 확인하면서, 해당 상태가 횟수를 다 썼을 때, 전원 다 킬 수 있는지만 확인하면 된다.
🔍코드 설명
---
```py
table = defaultdict(int)
row = input().rstrip()
table[row] += 1
```
각 열 정보를 받고, 열을 key로 하는 dict의 value에 +1 해주어, 상태를 카운트해준다.
```py
table = list(table.items())
table.sort(key=lambda x: -x[1])
```
dict를 list로 바꾸고, 빈도가 더 높은 순서대로 정렬해준다.
```py
for row, cnt in table:
need_switch_on = m - …
```

42-gjsk132

---

9-kyo-hwang/Graph Traversal/사라지는 발판.cpp
9-kyo-hwang/Graph Traversal/퍼즐 조각 채우기.cpp
9-kyo-hwang/Greedy/2024 KAKAO WINTER INTERNSHIP n + 1 카드게임.cpp
9-kyo-hwang/Greedy/디펜스 게임.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Sliding Window/할인 행사.cpp

플레이어 A와 B가 게임을 진행하는데, 양 플레이어가 캐릭터를 몇 번 움직이게 될 지 예측하고자 한다.
발판이 있는 부분과 없는 부분으로 이루어진 최대 5 x 5 크기의 격자 보드에서 캐릭터를 움직인다. 최초의 캐릭터 위치는 반드시 발판 위에 있으며, 캐릭터는 상하좌우로 인접한 4칸 중 발판이 있는 곳으로만 이동한다. 밟고 있던 발판은 다른 곳으로 이동할 때 사라진다.
게임이 종료되는 조건은 아래와 같이 2가지이다.
1. 움직일 차례인데 상하좌우 주변 4칸 모두 발판이 없거나 보드 밖이라 이동할 수 없을 때
2. 두 캐릭터가 같은 발판 위에 있을 때, 상대 캐릭터가 다른 발판으로 이동해 자신 캐릭터가 서있던 발판이 사라졌을 때
항상 플레이어 A가 먼저 시작하며, 두 플레이어는 "최적의 플레이"를 수행한다. 최적의 플레이는 다음을 의미한다.
- 이길 수 있는 플레이어(실수만 하지 않으면 항상 이기는 플레이어)는 최대한 빨리 승리하도록 플레이한다.
- 질 수 밖에 없는 플레이어(최선을 다해도 상대가 실수하지 않으면 항상 질 수 밖에 없는 플레이어)는 최대한 오래 버티도록 플레이한다.
게임 보드의 초기 상태를 나타내는 2차원 정수 배열 `board`와 플레이어 A의 캐릭터 초기 위치를 나타내는 정수 배열 `aloc`, 플레이어 B의 캐릭터 초기 위치를 나타내는 정수 배열 `bloc`이 매개변수로 주어진다. 양 플레이어가 최적의 플레이를 했을 때, 두 캐릭터가 움직인 횟수의 합을 return 하도록 solution 함수를 완성하라.
보드 크기가 작기 때문에, 모든 경우를 다 확인하면서 최선의 경우일 때의 움직임 …

69-9kyo-hwang

---

9-kyo-hwang/Graph Traversal/매출 하락 최소화.cpp
9-kyo-hwang/Graph Traversal/사라지는 발판.cpp
9-kyo-hwang/Graph Traversal/퍼즐 조각 채우기.cpp
9-kyo-hwang/Greedy/2024 KAKAO WINTER INTERNSHIP n + 1 카드게임.cpp
9-kyo-hwang/Greedy/디펜스 게임.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Sliding Window/할인 행사.cpp

"카카오상사"는 다음과 같은 조직 구성도를 갖는다. 
원 안에 적힌 두 개의 숫자는 직원의 정보를 의미한다. 왼쪽 숫자는 직원번호이며 직원을 식별할 수 있도록 1번부터 순서대로 발급되는 일련번호이며, 오른쪽 숫자는 해당 직원의 하루평균 매출액을 나타낸다. 위 그림에서 1번 직원은 14원을, 9번 직원은 28원의 하루평균 매출액을 기록하고 있다.
화살표가 시작되는 쪽의 직원은 팀장, 화살표를 받는 쪽의 직원은 팀원을 의미한다. 
- 직원번호 1번은 회사의 CEO로 고정되어 있으며, CEO는 항상 팀장이고 팀원일 수 없어 화살표를 받는 쪽이 될 수 없다.
- CEO를 제외한 나머지 모든 직원들은 다른 누군가로부터 정확히 1개의 화살표를 받는다.
한 직원은 최대 2개의 팀에 소속될 수 있지만, 팀장을 겸임하거나 두 개의 팀에서 팀원이 될 수는 없다.
- 10번 직원은 D팀의 팀장이면서 동시에 5번 직원이 팀장으로 있는 C팀에 속한 팀원이다.
- 5번, 9번, 10번 직원은 받는 쪽의 화살표와 시작하는 화살표가 모두 있으므로 팀장인 동시에 팀원이다.
- 2번, 3번, 4번, 6번, 7번, 8번 직원은 시작하는 화살표가 없고 받는 쪽의 화살표만 있으므로 팀장이 아니며 오직 팀원이다.
- 1번 직원인 CEO는 받는 쪽의 화살표가 없고 시작하는 화살표만 있으며 항상 팀원이 아닌 팀장이다.
그림의 조직도에는 A, B, C, D 총 4개의 팀이 존재하며, 각각 1번, 9번, 5번, 10번 직원이 팀장 직위를 담당한다.
이러한 구성에서, 하루 일정으로 워크숍을 계획하고 있다. 단, 모든 직원을 참석시킬 수 없어 아래와 같은 …

70-9kyo-hwang
