AlgoLeadMe/AlgoLeadMe-3

xxubin04/README.md
xxubin04/구현/18310_antena.py

2023-11-10 안테나
https://www.acmicpc.net/problem/18310
40분
- 우선, 규칙을 찾고자 하여 직접 여러 경우의 거리를 계산해보았다. 
- 같은 거리의 경우에는 문제에서 주어진 조건 '여러 개의 값이 도출될 경우 가장 작은 값을 출력한다.'를 참고한다.
- 그림에서 볼 수 있듯이, 최소거리의 위치는 집들의 중앙값이다.
- 집의 개수가 짝수인 경우에는 중앙값보다 왼쪽에 있는 집이다.
- 집의 개수를 N에 입력받고, 집들의 위치를 a에 담는다.
```python
import sys
N = int(sys.stdin.readline())
a = list(map(int, sys.stdin.readline().split()))
```
- a를 정렬하고 중앙값을 mid로 정해준다.
- 집의 개수를 짝수, 홀수의 경우로 나누어준다.
```python
a.sort()
mid = N//2
if N%2 == 0:
print(a[mid-1])
else:
print(a[mid])
```
- 전체 코드는 다음과 같다.
```python
import sys
N = int(sys.stdin.readline())
a = list(map(int, sys.stdin.readline().split()))
a.sort()
mid = N//2
if N%2 == 0:
print(a[mid-1])
else:
print(a[mid])
```
이러한 문제 유형을 '그리디'라고 하는 것을 알았다.
문제만 봤을 때는 어렵다고 느껴졌는데, 규칙만 찾으면 코드는 간결하게 쓸 수 있는 것 같다.

2-xxubin04

---

9-kyo-hwang/README.md
9-kyo-hwang/위상정렬/동굴 탐험.cpp

[동굴 탐험](https://school.programmers.co.kr/learn/courses/30/lessons/67260)
- 이 문제를 풀게 된 계기: 프로그래밍 경진대회 4번 문제 틀린 것에 대한 후회, 분노, 반성의 의미.
- "위상 정렬" 문제를 찾다가 발견하게 됨.
- 1시간 30분
- 위에서 언급했듯, 이 문제는 "위상정렬(Topology Sort)"을 이용해 풀 수 있다.
- 위키백과: 방향 그래프의 정점들을 엣지 방향을 거스르지 않도록 나열하는 것
- 대학교의 '선수과목' 개념을 생각하면 이해하기 쉽다.
- 즉, '선후 관계'가 정의된 그래프 구조 상에서선후 관계에 따라 정렬하기 위해 사용된다.
- 여기서 어떤 노드로부터 들어오는 화살표의 개수를 "진입차수(indegree)", 나가는 화살표의 개수를 "진출차수(outdegree)"라고 한다.
- 위상정렬을 수행하기 위해선 사이클이 없는 방향 그래프, 즉 DAG(Directed Acyclic Graph)여야 한다.
- 다음과 같이 사이클이 존재하는 그래프를 가정해보자.
- 진입차수가 0인 A가 먼저 제거되고, 그래프는 다음과 같이 변화한다.
- 사이클에 의해, 현재 남은 노드 중 진입차수가 0인 노드는 하나도 존재하지 않게 된다. 따라서 위상 정렬을 진행할 수 없다.
- 여기까지의 대략적인 사전지식을 갖고, 이제 문제를 들여다보자.
- 문제에서 "모든 방을 적어도 한 번은 방문해야 합니다.", "특정 방은 방문하기 전에 반드시 먼저 방문할 방이 정해져 있습니다." 문구를 보면 알 수 있듯, 위상 정렬을 사용하면 풀 수 있을 것 같다는 …

2-9kyo-hwang

---

xxubin04/README.md
xxubin04/스택/2841_alienStack.py

https://www.acmicpc.net/problem/2841
2시간
<조건>
- 하나의 줄에서 여러 프렛을 누르고 있더라도 가장 높은 프렛의 음만 난다.
- 한 번 누르거나 떼는 것 -> 손가락 움직임 +1
```python
stack = [[] for _ in range(7)]
num = 0
a, b = map(int, stdin.readline().split())
```
- 2차원 배열을 이용하여 7개의 리스트가 들어있게 만든다.
- 줄이 1-6이므로, 직관성을 높이기 위해 stack 안의 리스트를 0-6까지 만든다.
(인덱스를 줄 번호 그대로 쓸 수 있도록)
- 이제, 입력받은 줄에 프렛이 존재하지 않는 경우와 존재하는 경우로 나누어 구현한다.
```python
for i in range(a):
line, pret = map(int, stdin.readline().split())
if not stack[line]:
stack[line].append(pret)
num += 1
```
- 첫 줄에서 입력받은 a만큼 반복해주어야 하므로 for문 처리해준다.
- 입력받은 줄의 리스트(stack)에 아무것도 없다면, 바로 그 줄에 해당 프렛을 추가하고 num변수에 1을 더한다.
- 이미 프렛이 있는 경우에서 새로운 프렛이 추가될 때, 3가지 경우로 또 나누어 준다.
- 큰 프렛 존재
- 같은 프렛 존재
- 작은 프렛 존재
```python
else:
for j in range(len(stack[line])):
if stack[line][-1] > pret:    # …
```

3-xxubin04

---

xxubin04/README.md
xxubin04/수학/1105_8.py

2023-11-15 팔
[1105번: 팔](https://www.acmicpc.net/problem/1105)
40분
<조건>
- L <= R
- L <= `숫자` <= R
- `숫자`에 올 수 있는 자연수 중 8이 가장 적게 들어갈 수 있는 자연수의 8의 개수 출력
```python
L, R = stdin.readline().split()
List_L = list(L); List_R = list(R)
cnt = 0
```
- L과 R로 숫자를 입력받는다.
- 8의 개수를 cnt 변수로 받는다.
- 숫자의 자릿수대로 비교할 수 있도록 list로 만든다.
(자릿수 - 1의 자리, 10의 자리, ...)
- L과 R의 자릿수가 다르다면, 무조건 8의 개수가 가장 적은 수는 0일 수 밖에 없다.
- L = 99, R = 100 -> cnt = 0
- 따라서, L과 R의 자릿수가 다른 경우와 같은 경우로 나누어준다.
```python
if len(List_L) != len(List_R):
print(0)
else:
for j in range(len(List_R)):
if List_L[j] == List_R[j]:
if List_L[j] == '8':
cnt += 1
else:
break
print(cnt)
```
- 자릿수대로 비교하기 위해  `for j in range(len(List_R)):` 반복문을 써준다.
- L과 R의 동일한 자릿수에서 둘 다 동일한 수이고 그 수가 8로 같다면, 무조건 8을 가질 수 밖에 없다.
- 위의 경우와 아닌 경우로 나누어준다.
- 아닌 …

4-xxubin04

---

9-kyo-hwang/README.md
9-kyo-hwang/트라이/5052 전화번호 목록.cpp

[5052 전화번호 목록](https://www.acmicpc.net/problem/5052)
40분
- 사실 이 문제는 예전에 다른 방식으로 한 번 풀었었다.
- 다만 트라이를 사용할 만한 문제를 찾아보니, 이 문제가 입문하기 좋다고 해서 이 문제를 트라이로 다시 한 번 풀어봤다.
- k-진(k-ary) 검색 트리(search tree)의 일종으로, 주로 문자열을 검색할 때 빠른 속도로 찾을 수 있는 자료 구조이다.
- 만약 키(key)를 이진 검색 트리(binary search tree: BST)에 저장한다면, 균형잡힌 BST의 경우 O(MlogN) 시간에 키를 검색할 수 있다. 이 때 M은 문자열의 최대 길이, N은 트리에 존재하는 키 개수이다.
- 하지만 Trie를 이용하면 O(M) 시간에 키를 검색할 수 있다.
- 예를 들어, Trie에 "and", "ant", "dad", "do" 문자열을 넣으면 다음과 같이 저장된다.
- 이런 식으로 문자열의 문자 별로 분기하며 저장된다.
- 그 후 다시 검색할 때는 문자 하나씩 순서대로 찾아간다. 
- 이러한 시작 문자열을 접두어(prefix)라고 한다.
- 예시를 보자.
- 전화번호가 "911", "97625999", "91125426" 이런 식으로 주어진다.
- 911이 저장된 상태에서, 91125426을 검색하면 9 -> 1 -> 1 식으로 찾아 들어가다가 이미 저장된 911에 의해 바로 전화가 걸린다.
- 따라서 이 목록은 "일관성이 없다"
- 원리가 딱 Trie를 활용하면 좋을 듯 하다.
```cpp
int main() { …
```

4-9kyo-hwang

---

xxubin04/README.md
xxubin04/해시맵/1620_pokemon.py

2023-11-17 나는야 포켓몬 마스터 이다솜
[1620번: 나는야 포켓몬 마스터 이다솜](https://www.acmicpc.net/problem/1620)
40분
- 첫 줄에 N, M 입력받는다.
- N : 도감에 입력할 포켓몬 수
- M : 맞춰야 하는 문제 수
```python
N, M = map(int, stdin.readline().split())
dic1 = {}; dic2 = {}
```
- 입력하는 순서대로 포켓몬의 번호가 된다.
- 맞춰야 하는 문제에서 포켓몬을 입력하면 번호가 나와야 하고, 번호를 입력하면 포켓몬이 나와야 한다.
- key와 value로 번호와 포켓몬을 정리할 수 있기에 dictionary를 이용한다. (시간초과도 막을겸..)
```python
for i in range(1, N+1):
n = stdin.readline().strip()
dic1[i] = n
dic2[n] = str(i)
```
- key값에 따라 value값을 출력할 수 있도록, dictionary 2개로 만든다.
- `dic1` : key값이 번호
- `dic2` : key값이 포켓몬 
- n에 포켓몬을 입력받고나면, 개행문자가 포함된 상태로 문자열이 저장되므로 `strip()`을 해준다.
```python
for j in range(M):
m = stdin.readline().strip()
if m.isdigit() == True:
print(dic1[int(m)])
else:
print(dic2[m])
```
- 문제 개수인 M만큼 반복문을 반복한다.
- …

5-xxubin04

---

9-kyo-hwang/README.md
9-kyo-hwang/플로이드-워셜/1613 역사.cpp

[1613 역사](https://www.acmicpc.net/problem/1613)
30분
- 오늘 풀어볼 주제는 "최단거리", 그 중에서 "플로이드-워셜"이다.
- 들어가기에 앞서, 최단 경로 문제에 대해 간략하게 알아보자.
- 가중치 (방향) 그래프 G = (V, E), 즉 모든 엣지에 가중치가 있는 그래프에서 정의된다.
- 경로 p=($v_0, v_1, ..., v_k$)의 길이는 경로 상 모든 엣지의 "가중치 합"으로 정의한다.
- 노드 u에서 v로 가는 최단 경로의 길이를 $\delta{(u, v)}$라고 표시하자.
- Single-source:
- 하나의 출발 노드 s로부터 다른 모든 노드까지의 최단 경로 찾기
- 예: Dijkstra 알고리즘
- Single-destination:
- 모든 노드로부터 한 목적지 노드까지의 최단 경로 찾기
- Single-source 문제와 동일
- Single-pair:
- 주어진 한 출발 노드 s로부터 한 목적지 노드 t까지의 최단 경로 찾기
- 최악의 경우, 시간 복잡도에서 Single-source 문제보다 나은 알고리즘이 없음
- All-pairs:
- 모든 노드 쌍에 대해 최단 경로 찾기
- 예: Floyd-Warshall 알고리즘
- 최단 경로 상에 존재하는 모든 부분 경로 또한 최단 경로이다.
- 음수 사이클이 없는 가정 하에, 최단 경로는 사이클을 포함하지 않는다.
- 이정도만 알아보고, 문제를 확인해보자.
- 문제만 읽어보면, "이게 어떻게 최단경로 문제인 거지?" 싶다.
- 하지만 이 문구를 통해 이 문제는 최단경로, 그 중에서 …

5-9kyo-hwang

---

xxubin04/README.md
xxubin04/그리디/1049_guitarString.py

2023-11-20 기타줄
[1049번: 기타줄](https://www.acmicpc.net/problem/1049)
20분 
- N : 끊어진 기타줄의 개수
- M : 기타줄 브랜드
- 적어도 N개 사기 위해 필요한 돈의 최솟값 구하기  
- 나올 수 있는 가격의 경우의 수에는 크게 4가지 경우로 나눌 수 있다.
- 세트로만 구매
- 낱개로만 구매
- 같은 브랜드의 세트와 낱개를 함께 구매
- 최소 가격의 세트와 최소 가격의 낱개를 함께 구매  
```python
money = []; setList = []; singList = []
N, M = map(int, stdin.readline().split())
num = N // 6
```  
- 나올 수 있는 가격의 경우의 수를 `money`에 넣을 수 있도록 한다.
- `setList`에는 세트의 가격, `singList`에는 낱개의 가격을 넣을 수 있도록 한다.   
```python
for n in range(M):
SET, SIN = map(int, stdin.readline().split())
setList.append(SET); singList.append(SIN)
```
- 브랜드 수 M번만큼 `SET`, `SIN`에 세트와 낱개의 가격을 입력받는다.
- 세트와 낱개 리스트에 각각의 세트와 낱개 가격을 추가한다.
- 최소가격의 세트와 낱개를 도출해내기 위해     
```python
if N % 6 != 0:
money.append(SET * (num+1))  # 세트로만
else: …
```

6-xxubin04

---

9-kyo-hwang/README.md
9-kyo-hwang/분리 집합/10775 공항.txt

[10775 공항](https://www.acmicpc.net/problem/10775)
30분
- 1번부터 G번까지 게이트가 있는 공항에, P개의 비행기가 들어온다. 
- i번째 비행기를 $g_i(1 \le g_i \le G)$ 번째 게이트 중 하나에 도킹한다. 더 이상 도킹할 수 있는 게이트가 없다면 공항은 폐쇄된다.
- 비행기를 최대 몇 대 도킹시킬 수 있는가?
한번 2번 예시를 보자:
- 게이트는 1번부터 4번까지 총 4개다.
- 비행기는 6대 들어온다. 
- 다음과 같이 진행된다.
- 최초 상태에는 게이트가 다음과 같이 비어있다
- 2번 비행기가 들어온다. 2번 비행기는 1번 게이트 ~ 2번 게이트 중 한 곳에 도킹시킬 수 있다. 2번 게이트에 도킹시켜보자.
- 2번 비행기가 또 들어온다. 2번 게이트는 이미 비행기가 존재하므로, 1번 게이트에 도킹시킨다.
- [2][1][ ][ ]
- 3번 비행기가 들어온다. 1번 ~ 3번 게이트 중 한 곳에 가능한데, 1번과 2번은 안되므로 3번에 도킹시킨다.
- [2][1][3][ ]
- 3번 비행기가 또 들어온다. 1번 ~ 3번 게이트 중 어느 곳에도 도킹시킬 수 없으므로 공항은 폐쇄된다.
- 최종적으로 비행기는 3대까지 도킹시킬 수 있다.
예시를 보면, 다음과 같은 룰을 적용할 수 있을 것 같다.
1. G번 게이트에는 G번 비행기를 배정한다.
2. 만약 G번 게이트에 다른 비행기가 존재한다면, 배정 가능한 게이트가 나올 때까지 다음 왼쪽 게이트를 확인한다.
3. 만약 1번 게이트까지 배정할 수 있는 게이트가 없다면, 그 공항은 폐쇄된다.
이러한 상황에서 …

7-9kyo-hwang

---

xxubin04/README.md
xxubin04/스택/17952_taskFinish.py

2023-11-22 과제는 끝나지 않아!
[17952번: 과제는 끝나지 않아!](https://www.acmicpc.net/problem/17952)
<br>
25분
<br>
<조건>
- 최근에 나온 순서대로 과제를 하고, 받으면 바로 시작한다.
- 새로운 과제가 나온다면, 하던 과제를 멈추고 새로운 과제를 한다.
- 가장 최근의 과제가 끝났다면, 그 다음으로 최근인 과제를 이어서 한다.
**예제 2)** 
- 5분동안 1분, 3분, 4분일때 새로운 과제가 주어진다.
- 1분 : 과제1 (T=2)
- 2분 : 과제1 (T=1)
- 3분 : 과제2 (T=1)
- 4분 : 과제3 (T=0) -> 20점 획득
- 5분 : 과제2 (T=0) -> 100점 획득
- T=0이 되면, 과제가 끝나 점수를 얻게 된다.
```python
score = 0; stack = []
N = int(stdin.readline())
```
- N에 학기가 몇 분인지를 나타내는 정수를 입력받는다.
- 총 성적을 도출하기 위해, `score`변수와 과제들을 스택으로 쌓을 `stack` 리스트를 만들어준다.
- 가장 최근의 과제를 하는 조건이 있으므로, 과제들을 스택으로 구현한다.
```python
for n in range(N):
aList = list(map(int, stdin.readline().split()))
```
- for문으로 N번만큼 입력받도록 한다.
```python
if aList[0] == 1:
if aList[2] == 1:
score += aList[1]
aList.pop() …
```

7-xxubin04

---

xxubin04/README.md
xxubin04/구현/2563_paper.py

2023-11-24 색종이
[2563: 색종이](https://www.acmicpc.net/problem/2563)
<br>
30분
<br>
- 색종이의 크기는 무조건 100(10 x 10)이므로 색종이의 개수인 n에서 겹치는 넓이만큼을 빼주면 된다고 생각하였다. 그런데 1번만 겹치는게 아니고 3번, 4번 .... 겹치게 되면 복잡해지기 떄문에 이 방법은 좋지 못한 것 같다.
- 따라서 2차원 배열을 통해, 색종이가 있는 위치에만 1로 표시하자.
- 색종이의 유무에 따라 0과 1로 나뉘어지게 된다면, 겹치는 부분은 신경 쓸 필요없이 1의 개수 즉, 2차원 배열 속의 모든 값들을 더하면 색종이의 넓이를 구할 수 있다.
```python
array = [[0] * 101 for _ in range(101)]
```
- 2차원 배열을 선언하자.
- 101 * 101의 크기로 하는 이유는 x=0, y=0의 경우도 고려해야 하기 때문이다.
```python
x, y = map(int, stdin.readline().split())
for row in range(x, x+10):
for col in range(y, y+10):
array[row][col] = 1
```
- for문을 통해 n번만큼 x와 y의 값을 입력받자.
- 입력받은 x와 y에서 각각의 변의 길이가 10이 될 수 있도록 `range(x, x+10)`, `range(y, y+10)`으로 범위를 지정하여 그 안의 배열을 전부 1로 바꾼다.
```python
for j in array:
total += sum(j)
``` …

8-xxubin04

---

Dolchae/README.md
Dolchae/구현/7568 덩치.py

[7568 덩치](https://www.acmicpc.net/problem/7568)
20분
- 자신보다 몸무게와 키가 모두 큰 사람이 나보다 덩치가 큰 사람이 몇 명인지 알아내면 나의 덩치 등수를 바로 알 수 있다.
<br>
```python
big_list = []
big_list = [list(map(int, input().split())) for _ in range(n)]
```
- n에 전체 사람 수를 받는다.
- big_list(2차원 리스트)에 사람들 각각의 몸무게와 키를 저장한다.
- big_list[i][0]에는 몸무게가, big_list[i][1]에는 키가 저장된다.
<br>
```python
rank = 1
for j in range(n):
if big_list[i][0] < big_list[j][0] and big_list[i][1] < big_list[j][1]:
rank += 1
print(rank,end=" ")
```
- for문으로 배열을 하나씩 방문한다.
- rank(덩치 등수)는 매번 1로 초기화한다.
- 이중 for문으로 다른 사람들의 덩치를 나의 덩치와 비교해본다.
- 만약 다른 사람의 키와 몸무게가 모두 나보다 클 경우에 나의 등수는 내려가므로 rank에 1을 더한다.
- 나와 다른 사람 모두를 비교했다면 print하고 다음 나(for문의 i를 +1)로 넘어간다.
- 모든 사람의 덩치를 반복한 후 빠져나간다.
<br>
<br>
- 전체 코드
```python
big_list …
```

10-Dolchae

---

Dolchae/README.md
Dolchae/수학/1735 분수 합.py

[1735 분수 합](https://www.acmicpc.net/problem/1735)
40분
두 개의 분수의 합을 구해 기약분수로 나타내는 문제이다.
```python
import math as m
n1_high, n1_low = map(int,input().split())
n2_high, n2_low = map(int,input().split())
```
- 분자를 hign, 분모를 low로 하여 n1과 n2의 두 개의 분수를 입력 받는다.
<br>
```python
ans_low = m.lcm(n1_low,n2_low)
ans_high = (ans_low//n1_low)*n1_high + (ans_low//n2_low)*n2_high
```
- 실제로 통분하여 분수의 합을 계산하는 것처럼 구현하였다.
- 통분을 하기 위해 ans(두 분수의 합) 분모에 n1과 n2 분모의 최소공배수를 구한다.
- ans의 분자에는 최소공배수를 n1의 분모로 나눈 값에 n1의 분자를 곱하고 n2도 같은 방법으로 구해 둘을 더한다.
<br>
```python
gcd = m.gcd(ans_low,ans_high)
ans_low //= gcd
ans_high //= gcd
print(ans_high,ans_low)
```
- 약분을 하기 위해 gcd에 ans의 분모와 분자의 최대공약수를 저장한다.
- ans와 분모와 분자를 최대공약수로 각각 나누면 기약분수로 만들 수 있다.
<br>
<br>
- 전체코드
```python
import math as m
input = …
```

11-Dolchae

---

xxubin04/README.md
xxubin04/구현/11536_line.py

2023-12-25 줄 세우기
[11536번 - 줄 세우기](https://www.acmicpc.net/problem/11536)
<br>
20분
<br>
- INCREASING : 오름차순으로 정렬되어 있는 경우
- DECREASING : 내림차순으로 정렬되어 있는 경우
- NEITHER : 위의 두 가지에 해당하지 않는 경우
```python
num = int(input())
arrName = []
for i in range(num):
name = input()
arrName.append(name)
```
- `num`에 입력받을 이름의 개수를 입력받는다.
- `arrName`에 입력받은 순서대로 저장한다.
- for문을 통해 선수들의 이름을 차례대로 입력받는다.
```python
if arrName == sorted(arrName):
print("INCREASING")
elif arrName == sorted(arrName, reverse=True):
print("DECREASING")
else:
print("NEITHER")
```
- 입력받은 순서를 저장하고 있는 arrName과 정렬한 arrName을 비교해준다.
- sorted(arrName)과 같은 경우 : 오름차순 -> INCREASING
- sorted(arrName, reverse=True)과 같은 경우 : 내림차순 -> DECREASING
- 그 외의 경우 -> NEITHER
- 전체 코드
```python
num = int(input())
arrName = []
for i in range(num):
name = input() …
```

11-xxubin04

---

9-kyo-hwang/DFS, BFS/22352 항체 인식.cpp
9-kyo-hwang/README.md

[22352 항체 인식](https://www.acmicpc.net/problem/22352)
한 30분 정도 걸렸나
집에서 누워서 유튜브 보고 있었는데, [가장 빠르고 똑똑한 쥐(로봇)들의 미로 경주!](https://www.youtube.com/watch?v=MseWQvUw8_M) 이 영상이 뜨길래 봤다. 그런데 미로의 최단 경로를 찾는 알고리즘으로 **Flood Fill** 이란 것을 소개하길래 찾아봤는데 재밌어보여서 이거 관련 문제 풀어볼까? 하다가 찾은 문제다.
> 다차원 [배열](https://ko.wikipedia.org/wiki/%EB%B0%B0%EC%97%B4)의 어떤 칸과 [연결](https://ko.wikipedia.org/wiki/%EC%97%B0%EA%B2%B0_%EA%B7%B8%EB%9E%98%ED%94%84)된 영역을 찾는 [알고리즘](https://ko.wikipedia.org/wiki/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98)이다. 이 알고리즘은 [그림 프로그램](https://ko.wikipedia.org/w/index.php?title=%EB%9E%98%EC%8A%A4%ED%84%B0_%EA%B7%B8%EB%9E%98%ED%94%BD_%ED%8E%B8%EC%A7%91%EA%B8%B0&action=edit&redlink=1)에서 연결된 비슷한 색을 가지는 영역에 "채우기" 도구에 사용되며, [바둑](https://ko.wikipedia.org/wiki/%EB%B0%94%EB%91%91)이나 [지뢰 …

12-9kyo-hwang

---

xxubin04/README.md
xxubin04/해시맵/9375_fashionKing.py

2023-12-27 패션왕 신해빈
[9375번 - 패션왕 신해빈](https://www.acmicpc.net/problem/9375)
<br>
15분
<br>
📢조건
- 최소한 1개 이상 입어야 한다. (종류 상관없이 모든 의상에서)
- 한 종류의 의상에서는 최대한 하나만 입을 수 있다.      
```python
case = int(input())
for i in range(case):
total = 0; multi = 1; dic = {}
num = int(input())
for j in range(num):
cloth, kind = input().split()
if kind in dic.keys():
dic[kind] += 1
else:
dic[kind] = 1
```
- `case`변수에 테스트 케이스 횟수를 입력받는다.
- 테스트 케이스가 한 번 진행되고 나서 다른 케이스가 진행되려면, `total`, `multi`, `dic`을 갱신시켜야 계산이 이상하게 되지 않으므로 for문 안에 입력해준다.
- 입력받는 의상의 종류를 `dic`의 key로 지정해준다.
- 옷의 이름은 필요없으므로 알기 쉽게 같은 종류인 의상의 개수를 value로 세어준다.
- 이미 `dic`안에 있는 종류라면, value에 1을 더해준다.
- `dic`안에 없는 종류라면, value를 1로 지정해준다.
```python
for k in dic.keys():
multi *= (dic[k] + 1)
total = multi - 1
print(total)
```
경우의 수 계산방법
- 한 종류에 n개의 의상이 있다면 의상을 입을 …

12-xxubin04

---

Dolchae/README.md
Dolchae/스택/1406 에디터.py

[1406 에디터](https://www.acmicpc.net/problem/1406)
1시간
- 주어진 명령대로 커서를 움직이고 삭제 및 추가를 하면 되는 문제이다. 
- 제한 시간이 일반적인 문제보다 짧기 때문에 일반적인 구현 방법이 아닌 스택을 2개 만드는 방법으로 구현해야 한다.
- 커서를 중간에 두고 left와 right의 스택 2개를 만든다.
- 이때 right 스택은 방향을 뒤집어둔다.
<br>
- 처음에 문장을 입력받는다. 커서는 문장의 맨 마지막에 위치한다.
<br>
- "P X" 명령을 실행하면 X 원소가 추가된다. 
- 커서의 왼쪽에 추가되는 것이므로 left에 append해준다.
<br>
- 명령 "L"을 실행하면 커서가 왼쪽으로 이동한다.
- 커서의 왼쪽인 left에서 맨 마지막 원소를 pop하고 right에 append 한다.
- right 리스트는 뒤집혀 있으므로 pop과 append로 해결할 수 있다.
<br>
- 이와 반대로 명령 "D"가 실행되면 right에서 맨 마지막 원소를 pop하고 left에 append 해주면 된다.
<br>
- 명령 "B"를 실행하면 커서 왼쪽의 문자가 삭제되어야 하므로 left에서 pop한다.
<br>
```python
left = list(input())
right = []
```
- 처음 입력되는 문장은 전부 커서 왼쪽에 있으므로 left에 문장을 입력 받는다.
- right 스택도 만든다.
<br>
```python
for _ in range(int(input())):
command = …
```

12-Dolchae

---

xxubin04/README.md
xxubin04/정렬/7795_some.py

2023-12-29 먹을 것인가 먹힐 것인가
[7795번 - 먹을 것인가 먹힐 것인가](https://www.acmicpc.net/problem/7795)
<br>
30분
<br>
- A의 수가 B의 수보다 큰 경우의 수를 세어주는 문제이다.
> 2 -> 테스트 케이스 
> 5 3 -> 1번째 테스트 케이스 - A, B 안의 요소 개수
> 8 1 7 3 1 -> A의 요소들
> 3 6 1 -> B의 요소들
> 3 4 -> 2번째 테스트 케이스 - A, B 안의 요소 개수
> 2 13 7 -> A의 요소들
> 103 11 290 215 -> B의 요소들
```python
test = int(stdin.readline())
for _ in range(test):
A_num, B_num = map(int, stdin.readline().split())
A = list(map(int, stdin.readline().split()))
B = list(map(int, stdin.readline().split()))
A.sort()
B.sort()
pair = 0
B_index = 0
```
- test에 테스트 케이스 개수를 입력받는다.
- 위에서 입력받은 테스트 케이스 개수만큼 for문을 실행하게 된다.
- A_num, B_num에 A와 B의 각각의 요소 개수를 입력받는다.
- A와 B 안의 각각의 요소들을 입력받는다.
- A와 B를 정렬해준다.
- 쌍(A의 요소가 B의 요소보다 큰 경우)을 이루는 경우를 pair 변수로 세어준다.
```python
for a in A: …
```

13-xxubin04

---

9-kyo-hwang/DFS, BFS/11112 Eight puzzle.cpp
9-kyo-hwang/README.md

[11112 Eight puzzle](https://www.acmicpc.net/problem/11112)
1시간 + a
사실 이 문제는 게임 제작에서 자주 사용되는 A* 알고리즘을 공부하고자 찾은 문제다.
그 전에 한 번 도전이나 해보자는 생각으로 도전해봤는데, 처참하게 부서져버렸다…
이러한 3 x 3 보드에서, 빈 칸에 인접한 숫자 조각들을 움직일 수 있다.
숫자들을 적절히 움직여서, 위와 같은 형태를 만들어내야 한다.
이 때, 숫자 조각들을 움직이는 횟수의 최소값을 구하는 프로그램을 작성하는 것이 이 문제이다.
입력은 다음과 같이 주어진다.
```
2    // 테스트 케이스 개수
// 공백이 존재한다
123  // 첫 번째 테스트 케이스
4#5  // 공백은 '#'으로 표시한다.
786
123
456
87#
```
다음과 같이 출력한다.
```
2           // 첫 번째 테스트 케이스에 대한 결과
impossible  // 두 번째 테스트 케이스는 목표하는 형태를 만들 수 없다.
```
도대체 이걸 어떻게 건드려야 하지? 하면서 한참을 멍때렸다.
다른 미로 탐색처럼 2차원 배열에 저장해서 옮기는 방식으로 해봤는데, 고려해야 할 케이스가 너무 많아서 빙빙 돌다가 다 갈아엎었다.
낑낑대다가 다른 사람의 풀이를 봤는데, 전혀 다른 방식으로 푸는 거 보고 허탈해졌다.
차근차근 코드로 설명하겠다.
```cpp
#include <iostream>
#include <string>
#include <queue>
#include <tuple>
#include …
```

14-9kyo-hwang

---

xxubin04/README.md
xxubin04/스택/2257_chemical.py

2024-01-03 화학식량
[2257번 화학식량](https://www.acmicpc.net/problem/2257)
<br>
1시간
<br>
📢 조건
- 단순히 화학식량을 구하는 문제이다.
- 화학식을 구성하고 있는 화학원소는 [H, C, O]뿐이다.
- 화학원소를 해당하는 질량으로 바꿔주면 되지만,` H2O`와 같은 경우에는 `H * 2 + O`로 계산해주어야 한다.   <br>
📢 코드(예제 2를 적용하여 설명)
```python
dic = {'H':1, 'C':12, 'O':16}
chemList = list(stdin.readline().rstrip())
```
(div속 값들은 전부 str이지만, 가독성을 높이기 위해 따옴표 생략)
```python
div = []; box = []
for j in chemList:
total = 0
if j == '(':
div.append(j)
elif j in dic:
div.append(dic[j])
elif j == ')':
while True:
n = div.pop()
if n == '(':
break
total += n
if total != 0:
div.append(total)
else:
num = div.pop(-1) * int(j)
div.append(num)
```
- 딕셔너리를 이용하여 화학원소를 key로, 질량을 value로 지정한다.
- chemList에 리스트 형태로 입력받는다.
- ` ) `가 나올때까지 질량으로 바꾼 값을 div에 추가한다.( ` ( `는 그대로 추가)
- ` ) `가 나올때까지의 div는 [12, 1, (, 12, …

14-xxubin04

---

Dolchae/README.md
Dolchae/구현/1138 한 줄로 서기.py
Dolchae/정렬/3273 두 수의 합.py

[3273 두 수의 합](https://www.acmicpc.net/problem/3273)
40분 + α
주어진 리스트에서 2개를 뽑아 더해서 x를 만들 수 있는 쌍이 몇 개인지 구하는 문제이다.
<br>
```python
input_ = open(0).readline
num = int(input_())
nlist = list(map(int, input_().split()))
x = int(input_())
nlist.sort()
```
- num와 nlist에 각각 수열의 크기와 수열을 입력받는다.
- 두 수의 합이 되어야 할 x를 입력받는다.
- 정렬된 상태에서 for문을 반복하기 위해 nlist를 정렬해준다.
<br>
```python
ans = 0
left = 0
right = num-1
while left < right:
if nlist[left] + nlist[right] == x:
ans += 1
left += 1
elif nlist[left] + nlist[right] < x:
left += 1
else:
right -= 1
print(ans)
```
- 쌍의 개수를 저장할 ans와 인덱스의 처음과 끝 부분을 담당하며 조정할 left와 right를 만든다.
- while문은 left와 right가 같아질 때(인덱스가 교차될 때)까지 반복한다.
- 두 수의 합이 x와 같다면 ans를 하나 추가시키고, left를 한 칸 옆으로 옮긴다.
- 두 수의 합이 x보다 작다면 더 큰 수를 더해야 한다는 뜻이므로 left를 +1한다.
- 두 수의 합이 x보다 크다면 더 작은 수를 더해야 한다는 뜻이므로 …

15-Dolchae

---

xxubin04/README.md
xxubin04/수학/2839_sugarDelivery.py

2024-01-05 설탕 배달
[2839번 : 설탕 배달](https://www.acmicpc.net/problem/2839)
<br>
40분
<br>
- 주어진 설탕을 5kg와 3kg 봉지로 배달할 수 있다.
- 이때, 상근이가 배달하는 봉지의 최소 개수를 도출해야 한다.
- 봉지의 최소 개수 = (설탕의 무게 // 5kg) + (나머지 // 3kg)     
<br>
```python
kilo = int(input())
num = 0; ans = False
remain = kilo % 5
num += kilo // 5
```
- `kilo`에 배달해야하는 설탕의 무게를 입력받는다.
- `remain`을 kilo를 5로 나눈 나머지 값으로 지정한다.
-  `num`을 kilo를 5로 나는 몫 즉, 5kg 봉지의 최대 개수로 지정한다.    
<br>
```python
if remain % 3 == 0:
num += remain // 3
print(num); ans = True
```
- 5로 나눈 나머지인 remain이 3의 배수라면, num에 remain을 3으로 나눈 나머지를 더해준다.
<br>
```python
else:
num = 0
for i in range(kilo // 5, -1, -1):
if (kilo - 5 * i) % 3 == 0:
num = i + ((kilo - 5 * i) // 3); ans = True
print(num)
break
else:
pass
```
- remain이 3의 배수가 아닌 경우에는 num을 0으로 초기화 시켜준다. …

15-xxubin04

---

Dolchae/README.md
Dolchae/구현/1244 스위치 켜고 끄기.py

[1244 스위치 켜고 끄기](https://www.acmicpc.net/problem/1244)
50분
주어진 조건에 따라 스위치를 on 혹은 off 하면 되는 문제이다. 조건은 다음과 같다.
- 남학생: 받은 수의 배수에 해당하는 모든 스위치를 현재의 반대로 만든다.
- 여학생: 받은 수를 중심으로 좌우(대칭으로) 서로 다른 상태일 때까지 모든 스위치를 반대로 만든다.
<br>
```python
import sys
countSwitch = int(sys.stdin.readline())
switches = list(sys.stdin.readline().split())
students = int(sys.stdin.readline())
```
- countSwitch에 스위치를 저장한다.
- switches에 스위치의 현재 상태를 리스트로 저장한다.
- students에 입력될 학생의 수를 저장한다.
<br>
```python
for _ in range(students):
studentState = (list(map(int, sys.stdin.readline().split())))
now = studentState[1]
if studentState[0] == 1:
for i in range(now-1, countSwitch, now):
if switches[i] == '1':
switches[i] = '0'
else:
switches[i] = '1'
else:
i = 0
while(now-i-1 >= 0 and now+i-1 < countSwitch):
if switches[now-i-1] == …
```

16-Dolchae

---

xxubin04/DFS/1743_foodTrash.py
xxubin04/README.md

2024-01-08 1743_음식물 피하기
[1743번 - 음식물 피하기](https://www.acmicpc.net/problem/1743)
<br>
2시간
<br>
<br>
- 떨어진 음식물들은 **상하좌우에 위치**한 음식물들과 뭉치게 된다.
- N(col)에 통로의 세로 길이, M(row)에 통로의 가로 길이, K(num)에 음식물 쓰레기의 개수를 입력받는다.
<br>
- 상하좌우에 위치한 음식물들과 뭉친 최대의 크기를 출력해야 하므로 DFS(깊이 우선 탐색)를 사용한다.
<br>
<br>
[[출처 : 깊이 우선 탐색(Depth First Search)](https://velog.io/@zz1996zz/%EA%B9%8A%EC%9D%B4-%EC%9A%B0%EC%84%A0-%ED%83%90%EC%83%89Depth-First-Search)]
<br>
- 그래프 탐색 알고리즘의 한 종류로, 깊이 우선 탐색(Depth First Search)이라 하며 정점의 자식들을 먼저 탐색하는 알고리즘이다.
- 큐와 스택을 활용하거나 재귀함수를 통해 구현 가능하다.
- `앞으로 찾아서 가야 할 노드`와 `이미 방문한 노드`를 기준으로 데이터를 탐색한다.
- `앞으로 찾아서 가야 할 노드` : 계속 검색
- `이미 방문한 노드` : 무시하거나 따로 저장
<br>
- 위의 그림과 같이, A의 자식들에 B, C가 있다면 A를 visited에 넣어주고 B와 C를 검색한다.
- B의 자식들에 D, C의 자식들에 G, H, I가 있으므로 B와 C를 visited에 넣어주고 그 다음 자식들을 검색한다.
- `앞으로 찾아서 가야 할 …

16-xxubin04

---

xxubin04/DFS/18126_raccoon99.py
xxubin04/README.md

[18126번 - 너구리 구구](https://www.acmicpc.net/problem/18126)
<br>
1시간
<br>
: 집 입구에서부터 가장 멀리 있는 방까지 이동하는 거리를 구해야 한다.
<br>
- 이미 방문한 곳은 방문하지 않아야 하고, 도착한 방에서 다른 방으로 재귀적으로 거리를 더해야 하므로 DFS를 사용해야겠다고 생각했다.
- 그림을 보고 오해의 여지가 있을 것 같다는 생각이 갑자기 들었다. 예제를 기반으로 하였을 때는 방의 번호에 따라서 입구에서부터 점점 멀어진다고 이해해도 전혀 문제가 없다. 하지만, 문제에서는 방의 번호에 따라서 입구에서부터 멀어진다는 말이 없으므로 주의하자.
<br>
--- 
```python
N = int(input())
route = [[] for _ in range(N + 1)]
visited = [0 for _ in range(N + 1)]
dist = [0 for _ in range(N + 1)]
num = 1
for i in range(N - 1):
A, B, C = map(int, input().split())
route[A].append([B, C])
route[B].append([A, C])
```
- `N`에 방의 개수를 입력받는다.
- `N-1` 개의 줄에 집의 정보를 정수 A, B, C로 입력받는다.
- 각각의 줄에 입력받은 `[A, B, C]`는 route안에 추가한다.
- 이미 방문한 노드와 방문하지 않는 노드를 구분하기 위해 visited를 만들어준다.
<br>
- route에 각각의 방의 리스트에 입력받은 A, B, C에서 갈 수 있는 …

17-xxubin04

---

gjsk132/DP/1149 RGB거리.py
gjsk132/README.md

[백준 1149 : RGB거리](https://www.acmicpc.net/problem/1149)
25분
**요점 : DP를 이용한 최소 비용 구하기**
**구하고자 하는 결과**
- 집을 R, G, B 값으로 칠했을 때 들 수 있는 최솟값
1. 같은 색상을 연속으로 색칠할 수 없다.
2. 다음 집이 R, G, B 값이 작은지 큰지에 따라 달라지기 때문에 색칠할 때마다의 최소 비용이 필요.
**DP인 이유**
1. 반복 -> 이전의 각 색상별 최소 비용을 사용하여 구하는게 반복
2. 정답이 일정함 -> 집의 색상별 비용이 정해져 있어서 최소 비용도 일정
위 과정을 마지막 집까지 반복해준다.
``home`` : 총 색칠할 집의 수
``dp``
입력 -> 집이 각 색으로 칠할 때의 정보
결과 -> 이전 집의 색을 고려했을 때 각 색을 칠하는 최소비용
우선 입력값을 저장해준다.
```py
home = int(input())
dp = [list(map(int,input().split())) for i in range(home)]
```
문제 이해에서 설명했던 것처럼
맨 처음 집의 색부터 시작해서 각 색을 칠하는데 드는 최소비용을 저장한다.
```py
for i in range(1,home):
dp[i][0] += min(dp[i-1][1], dp[i-1][2])
dp[i][1] += min(dp[i-1][0], dp[i-1][2])
dp[i][2] += min(dp[i-1][0], dp[i-1][1])
```
마지막 집에서의 최소값을 출력해준다.
```py …
```

11-gjsk132

---

Dolchae/DFS&BFS/1260 DFS와 BFS.py
Dolchae/README.md

[1260 DFS와 BFS](https://www.acmicpc.net/problem/1260)
1시간
- 깊이 우선 탐색으로, 그래프에서 깊은 부분을 우선적으로 탐색하는 알고리즘이다.
- 스택 자료나 재귀 함수를 이용한다.
1. 탐색 시작 노드를 스택에 삽입하고 방문처리
2. 스택의 최상단 노드에 방문하지 않은 인접한 노드가 하나라도 있다면 그 노드를 스택에 넣고 방문처리한다. 방문하지 않은 인접 노드가 없다면 스택에서 최상단 노드를 꺼낸다.
3. 더 이상 2번 과정을 수행할 수 없을 때까지 반복한다.
- 너비 우선 탐색으로, 그래프에서 가까운 노드부터 우선적으로 탐색하는 알고리즘이다.
- 큐 자료를 이용한다.
1) 시작 노드를 큐에 삽입하고 방문 처리한다.
2) 큐에서 노드를 꺼낸 뒤에 해당 노드의 인접 노드 중 방문하지 않은 노드를 모두 큐에 삽입하고 방문처리한다.
3. 더 이상 2번의 과정을 수행할 수 없을 때까지 반복한다.
<br>
- 주어진 입력에 따른 그래프를 DFS와 BFS로 탐색한 순서를 출력하는 문제이다.
<br>
```python
n,m,v = map(int,input().split())
graph = [[0]*(n+1) for _ in range(n+1)]
for i in range (m):
a,b = map(int,input().split())
graph[a][b] = graph[b][a] = 1
```
- 정점의 개수 n, 간선의 개수 m, 탐색 시작 노드 v를 입력받는다.
- 문제에서 정점 번호가 1~N까지인데 파이썬의 인덱스는 0부터 시작하므로 직관적인 처리를 위해 (n+1)의 …

17-Dolchae

---

9-kyo-hwang/DFS, BFS/1167 트리의 지름.cpp
9-kyo-hwang/README.md

[1167 트리의 지름](https://acmicpc.net/problem/1167)
15분?
트리 정보가 주어졌을 때, **트리의 지름** 을 구하는 프로그램을 작성해야 한다.
**1. 트리(tree)**
트리는 연결된(connected) 사이클이 없는(acyclic) 무방향 그래프이다.
트리에서는 어떤 두 노드를 선택해도 둘 사이에 경로가 항상 하나만 존재한다.
**2. 트리의 지름(diameter of a tree)**
트리에서 어떤 두 노드를 선택해 양쪽으로 잡아 당겼을 때, 가장 길게 늘어나는 경우가 있을 것이다. 
이럴 때 트리의 모든 노드들은 이 두 노드를 지름의 끝 점으로 하는 원 안에 들어가게 된다.
이런 두 노드 사이의 경로 길이를 트리의 지름이라고 한다. 
다시 말해, 트리에서 **가장 멀리 떨어져 있는 두 노드 사이의 거리** 를 트리의 지름이라고 부른다.
트리의 지름은 루트 노드를 지날 수도, 지나지 않을 수도 있다. 
왼쪽은 루트를 경유해야 최대 길이가 나오고, 오른쪽은 루트를 경유하지 않아야 최대 길이가 나온다.
트리의 지름을 구하는 방법은 간단하다.
1. 임의의 정점(x)으로부터 가장 먼 정점(y)을 구한다.
2. 1.에서 구한 정점(y)으로부터 가장 먼 정점(z)을 구한다.
3. 1.에서 구한 정점(y)과 2.에서 구한 정점(z)의 거리가 트리의 지름이다.
**증명**
[참고 사이트](https://johoonday.tistory.com/217)
정점 y와 정점 z를 잇는 경로가 트리의 지름이 된다는 건, 임의의 정점 x에서 가장 멀리 떨어진 정점 y는 트리의 지름 양 끝 중 …

17-9kyo-hwang

---

gjsk132/DP/17485 진우의 달 여행 (Large).py
gjsk132/README.md

[백준 17485 : 진우의 달 여행 (Large)](https://www.acmicpc.net/problem/17485)
캬캬 풀었습니당~
1시간 30분
**요점 : DP를 이용한 최소 비용 구하기**
**구하고자 하는 결과**
- 우주선이 지구에서 달까지 사용하는 연료의 최솟값
1. 우주선이 움직일 수 있는 방향이 정해져있다.<img src="https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/47236246-2161-410d-bec6-fdb3b934e445" width=75%>
2. 우주선은 같은 방향으로 연속되게 움직일 수 없다.
( 어느 방향에서 왔는지에 대한 정보가 필요하다. )
**DP인 이유**
1. 반복 > 이전의 방향을 판단하여 해당 위치에서의 최소비용을 구하는게 반복
2. 정답이 일정 > 연료 비용이 변하지 않고, 방향도 규칙이 정해져있어 일정
이미지와 아래 코드의 약간 다른 점이 방향에 따라 저장하는 index 위치가 약간 달라요!
왼쪽 ( -1 )이 리스트 제일 마지막에 있습니다. ( 자세한건 아래 설명 통해 보시면 될 것 같습니다. )
``dp`` 입력 : 경로 비용 / 결과 : 해당 위치까지 방향에 따른 최소비용
우선 입력값을 저장한다.
```py
N, M = map(int,input().split())
dp = [[[i]*3 for i in map(int,input().split())] for _ in range(N)]
```
여기서 경로 비용(dp)를 저장할 때 ``i``가 아닌 ``[i]*3``라고 해주는 이유는 방향에 …

12-gjsk132

---

9-kyo-hwang/DFS, BFS/1167 트리의 지름.cpp
9-kyo-hwang/Dynamic Programming/2096 내려가기.cpp
9-kyo-hwang/README.md

[2096 내려가기](https://www.acmicpc.net/problem/2096)
40분
(N x 3) 숫자 표가 있다. 각각의 칸에는 0 이상 9 이하 숫자가 적혀있다.
첫 줄에서 시작해서 마지막 줄까지 내려가는데, 아래와 같은 규칙을 적용한다.
- 첫 번째 줄에서는 세 개의 숫자 중 하나를 고른다.
- 두 번째 줄부터 내려갈 때는 바로 아래 수 또는 아래 수와 붙어 있는 수로 이동한다.
위 조건을 그림으로 나타내면 다음과 같다. 현재 위치를 별표, 갈 수 있는 위치를 파란 동그라미, 갈 수 없는 위치를 빨간 가위표로 표시한다.
숫자 표가 주어졌을 때, 얻을 수 있는 최대 점수/최소 점수를 각각 출력하는 프로그램을 작성하라.
[나영쿤의 PR](https://github.com/AlgoLeadMe/AlgoLeadMe-3/pull/61)
이걸 봐서 그런 지 '거의 똑같은 문제 아닌가? 왜 골드 5지?'하고 냅다 돌진했다가 생각보다 시간을 많이 날렸다.
**원래 접근한 방식**
```cpp
#include <algorithm>
#include <iostream>
using namespace std;
int main() {
ios_base::sync_with_stdio(false);
cin.tie(nullptr);
int N;
cin >> N;
vector v(N + 1, vector(3, 0));
for (int i = 1; i <= N; ++i) {
for (int j = 0; j < 3; ++j) {
cin >> v[i][j];
}
}
vector maxi(N + 1, …
```

18 9kyo hwang

---

Dolchae/README.md
Dolchae/수학/2331 반복수열.py

[2331 반복수열](https://www.acmicpc.net/problem/2331)
40분
- 각 자리의 숫자를 P번 곱한 수들의 합을 수열로 만들어서 반복되는 부분을 제외하고 남은 수열의 개수를 출력하는 문제이다.
```python
input_ = open(0).readline()
first, multiple = map(int, input_.split())
list = []
```
- first에 수열의 첫 번째 수를 저장하고, multiple에 몇 번 곱할지 (=P)를 저장한다.
- 수열을 저장할 list를 만든다.
<br>
```python
def repeated(n):
num=0
for i in [int(digit) for digit in str(n)]:
i = int(i)
num += i ** multiple
if num in list:
print(list.index(num))
exit(0)
list.append(num)
repeated(num)
```
- num은 새롭게 리스트에 저장될 수이다.
- for문은 n의 각 자릿수를 i에 저장하며 반복한다.
- i를 다시 int로 만들어주고, num에 i의 multiple 제곱을 더해서 수열의 다음 요소를 만든다.
- 만약 num이 list 안에 있다면 반복되는 구간의 시작을 찾은 것이므로 list에서 num의 인덱스를 출력하고, 종료시킨다.
- list.index(num)은 반복이 시작되는 즉, 이 인덱스부터 제외시켜야 한다는 뜻인데 우리는 남은 수열의 개수를 출력하면 되고 인덱스 번호가 0부터 시작하므로 그대로 num의 인덱스를 출력하면 정답이 …

18-Dolchae

---

xxubin04/Heap/17503_beerFestival.py
xxubin04/README.md

2024-01-12  17503_맥주축제
[17503번 맥주 축제](https://www.acmicpc.net/problem/17503)
<br>
1시간
<br>
전씨의 간 레벨의 최솟값을 구하자.
<br>
<br>
조건
- `전씨의 간 레벨 >= 맥주 도수` 여야 한다. 그렇지 않으면 전씨는 맥주병이 와 기절하고 만다.
- `마시는 맥주 N개의 선호도 합 >= M` 이어야 한다. 
- `전씨의 간 레벨이 될 수 있는 값 중 최솟값`을 구한다.
<br>
- 처음에는 선호도 오름차순 기준으로 K이상을 만족하는 요소들을 추려 도수 레벨을 따져볼까 고민했었다. 그런데 너무 복잡해지는 듯해 어떻게 푸는지 찾아봤는데 다들 힙을 사용하는 것을 보고 힙에 대해서 공부해보았다.
<br>
---
[[출처 : https://www.geeksforgeeks.org/heap-data-structure/minheapandmaxheap/](https://www.geeksforgeeks.org/heap-data-structure/minheapandmaxheap/)]
- **최댓값과 최솟값**을 찾는 연산을 빠르게 하기 위해 고안된 완전 이진트리를 기본으로 한다.
- **최소 힙** : 부모 노드의 키 값 < 자식 노드의 키 값
- **최대 힙** : 부모 노드의 키 값 > 자식 노드의 키 값
- heap 모듈은 최소 힙을 지원하므로 최대 힙을 구현하려면 따로 구현해주어야 한다.
<br>
[[출처 : https://littlefoxdiary.tistory.com/3)](https://littlefoxdiary.tistory.com/3)] …

18-xxubin04

---

Dolchae/DFS&BFS/1389 케빈 베이컨의 6단계 법칙.py
Dolchae/README.md

[1389 케빈 베이컨의 6단계 법칙](https://www.acmicpc.net/problem/1389)
1시간 + α
- 입력된 유저들의 관계에 따라 케빈 베이컨 수를 계산했을 때 가장 작은 사람을 출력하는 문제이다.
- 케빈 베이컨은 주어진 두 사람의 관계가 몇 단계를 거쳐야 하는 지 나타낸다.
<br>
```python
from collections import deque
user_num, relation_num = map(int,input().split())
relations = [[] for _ in range(user_num+1)]
bacon_list = []
```
- 유저의 수와 친구 관계의 수를 각각 user_name, relation_num에 저장한다.
- 후에 입력될 유저들의 관계를 나타내기 위한 relations 리스트를 선언한다.
- 각 유저들의 케빈 베이컨 수를 저장할 bacon_list를 선언한다.
<br>
```python
def bacon(i):
visited = [0] * (user_num+1)
queue = deque()
queue.append(i)
visited[i] = 1
while queue:
v = queue.popleft()
for k in relations[v]:
if not visited[k]:
visited[k] = visited[v]+1
queue.append(k)
return sum(visited)
```
- 한 유저의 케빈 베이컨 수를 계산하는 함수이다.
- 방문 노드를 기록하기 위한 visited를 전부 …

19-Dolchae

---

gjsk132/README.md
gjsk132/그리디/1931 회의실 배정.py

[백준 1931 : 회의실 배정](https://www.acmicpc.net/problem/1931)
2시간
(시간 초과한 문제를 붙잡다가 포기하고 사이트 참고했습니다.)
_사이트 보고 후회..._
**요점 : lambda를 사용한 정렬**
이 문제는 코드 자체는 단순할 수 있지만, 어떻게 정렬하느냐에 따라 문제를 엄청 헤맬 수도 있다. _그게 접니다._
한 회의를 시작하기 위해서는 이전의 하던 회의가 우선적으로 끝나야 다음 회의를 진행할 수 있다. 따라서 기본적으로 **끝나는 순서를 기준**으로 정렬되어 있어야한다.
<image src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/918709e4-def2-41e6-b40c-b8482825cccd" width = 80%>
여기서 아래와 같은 조건을 만족하는 케이스를 주의해야 한다.
1. 시작과 끝나는 시간이 동일
2. 끝나는 시간이 동일한 회의가 여러 개일 경우
아래 이미지와 같이 ``3 5``와 ``5 5``의 순서에 따라 결과값이 바뀌는 걸 알아야 한다.
<image src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/1aa3d549-dab1-4cbf-ad5f-54edba9032d2" width = 80%>
<image src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/d4d7381c-6e9e-4faf-83d1-b88a9aecd465" width = …

13-gjsk132

---

xxubin04/README.md
xxubin04/스택/4949_균형잡힌 세상.py

2024-01-15 4949_균형잡힌 세상
[4949번: 균형잡힌 세상](https://www.acmicpc.net/problem/4949)
<br>
30분
<br>
괄호 `(` , `)` , `[` , `]`가 균형잡힌 경우에는 `yes`를, 아닌 경우에는 `no`를 출력한다.
<br>
1) `(  [ ]  )` , `[  (  (  )  )  ]`, `......` , `.` 등과 같이 좌우가 균형을 이룬다면 yes 인 경우이다.
2) `(  [  )  ]` , `[  )`, `(  )  ]` 등과 같이 좌우가 균형을 이루지 않는다면 no 인 경우이다.
```python
while True:
string = input()
bracket = []
if string == ".":
break
```
- . 하나만 찍히는 경우에만 while문을 탈출할 수 있으므로 string에 문자열을 입력받고 string이 '.'인 경우에는 break로 while문을 탈출한다.
<br>
```python
for i in string:
if i == "(" or i == "[":
bracket.append(i)
elif i == ")":
if len(bracket) != 0 and bracket[-1] == "(":
bracket.pop()
else:
bracket.append(i)
break
elif i == "]":
if len(bracket) != 0 and bracket[-1] == "[":
bracket.pop()
else:
bracket.append(i)
break
```
- 입력받은 string을 for문을 통해 …

19-xxubin04

---

Dolchae/DFS&BFS/1926 그림.py
Dolchae/README.md

[1926 그림](https://www.acmicpc.net/problem/1926)
1시간
가로나 세로가 1로 연결된 것(대각선으로는 불가)을 그림이라고 하고, 그림의 넓이는 그림에 포함된 1의 개수이다.
이때 그림의 개수와 가장 넓은 그림의 넓이를 출력하는 문제이다. (그림이 없을 때 가장 넓은 그림의 넓이는 0)
<br>
```python
from collections import deque
height, width = map(int,input().split())
paint = [list(map(int, input().split())) for _ in range(height)]
```
- 도화지의 세로와 가로를 height와 width에 입력받는다.
- paint에 문제에서 주어지는 그림의 정보를 저장한다.
<br>
```python
def bfs(graph,a,b):
queue = deque()
queue.append((a,b))
graph[a][b] = 0
count = 1
while queue:
x,y = queue.popleft()
for dx,dy in [(-1, 0), (0, 1), (1, 0), (0, -1)]:
nx, ny = x+dx, y+dy
if nx<0 or nx>=height or ny<0 or ny >= width:
continue
if graph[nx][ny] == 1:
graph[nx][ny] = 0
queue.append((nx,ny))
count += 1
return count
```
- graph에는 그림의 …

20-Dolchae

---

xxubin04/DP/14430_자원 캐기.py
xxubin04/README.md

2024-01-17 14430번_자원 캐기
[14430번: 자원 캐기](https://www.acmicpc.net/problem/14430)
<br>
40분
<br>
로봇 WOOK이 (N, M)크기만큼 자원을 탐색할 때, 탐색 가능한 자원의 최대 수를 구하는 것이다.
<br>
- 동적 계획법, 다이나믹 프로그래밍, DP라고 불리는 알고리즘이다.
- DP를 사용하기 위해서 다음 두 가지 조건을 만족해야 한다.
- **최적 부분 구조** : 문제를 해결하는 모든 단계에 대해 해당 단계의 최적해가 도출되어야 한다.
- **겹치는 부분 문제** : 메모이제이션을 하여 작은 문제를 재사용할 수 있어야 한다. (ex. 피보나치 수열)
<br>
(메모이제이션 : 중복되는 문제의 값을 매번 구하는 것의 비효율성 문제를 해결하기 위함이다. 정답을 한 번 구하면 그 정답을 캐시에 메모해둠으로써 다음에 필요할 때, 다시 사용하게 된다.)
<br>
> DP 구현법
> 
> 1. Top-down : 큰 문제를 작은 문제로 쪼개면서 해결, 재귀로 구현한다.
> 2. Bottom-up : 작은 문제부터 차례대로 해결, 반복문으로 구현한다.
<br>
[[참고 : https://c4u-rdav.tistory.com/37](https://c4u-rdav.tistory.com/37)]
<br>
<br>
<br>
- 로봇 WOOK은 한 번에 오른쪽 한 칸, 아래쪽 한 칸으로만 이동할 수 있다.
- (0, 0)에서 시작하여 (N, M)에 도달하였을 때 모든 지점을 탐색한 상태로 만든다.
- 0 : 자원 X, 1 : 자원 O
<br>
**DP의 …

20-xxubin04

---

Dolchae/DFS&BFS/2667 단지번호붙이기.py
Dolchae/README.md

[2667 단지번호붙이기](https://www.acmicpc.net/problem/2667)
_허나영 선배님의 추천 문제!_
30분
저번 PR에서 올린 [1926 그림](https://www.acmicpc.net/problem/1926)과 매우 유사한 문제로, 집이 있는 곳(1이 연결되어 있는)을 각각 단지로 정의하여 단지수와 각 단지에 속하는 집의 수를 오름차순으로 출력하는 문제이다.
<br>
저번 PR과 비교했을 때 변수명과 입력방식, 출력값 정도만 달라졌다.
```python
from collections import deque
map_size = int(input())
map_list = [list(map(int, (input().strip()))) for _ in range(map_size)]
```
- map_size에 지도의 크기를 입력받는다.(2차원 배열의 크기)
- map_list에 집의 정보를 입력받아 이차원 리스트로 저장한다.
- 입력이 공백 없이 주어지므로 strip()을 사용해주었다.
<br>
```python
def bfs(graph,a,b):
queue = deque()
queue.append((a,b))
graph[a][b] = 0
count = 1
while queue:
x,y = queue.popleft()
for dx,dy in [(-1, 0), (0, 1), (1, 0), (0, -1)]:
nx, ny = x+dx, y+dy
if nx < 0 or nx >= map_size or ny < 0 or ny >= map_size: …
```

21-Dolchae

---

xxubin04/README.md
xxubin04/Sieve of Eratosthenes/6588_골드바흐의 추측.py

2024-01-19 6588번 골드바흐의 추측
[6588번 - 골드바흐의 추측](https://www.acmicpc.net/problem/6588)
<br>
20분 
<br>
주어지는 숫자를 두 소수의 합의 식으로 나타내라. 
두 소수의 합으로 나타낼 수 없다면, "Goldbach's conjecture is wrong."을 출력한다.
<br>
<br>
소수를 찾는 알고리즘 중 하나로, 특정 범위 내의 모든 소수를 판별하는 방법이다. 
<br>
- 2부터 소수를 구하고자 하는 구간의 모든 수를 나열한다.
- 0과 1은 소수가 아니므로 소수에서 제외시킨다.
- 2는 소수이므로 자기 자신을 제외한 2의 배수를 모두 지운다.
- 3은 소수이므로 자기 자신을 제외한 남은 수 가운데 3의 배수를 모두 지운다.
- 남아있는 수들 중 5는 소수이므로 자기 자신을 제외한 5의 배수를 모두 지운다.
- 위의 과정을 반복하면 구하고자 하는 구간의 모든 소수가 남게 된다.
<br>
```python
prime = [0, 0] + [1] * 999999
for j in range(2, 1001):
if prime[j] == 1:
for k in range(j * 2, 1000001, j):
prime[k] = 0
prime[2] = 0
```
<br>
> **조건**
> 1. 각 테스트 케이스는 짝수 정수 n 하나로 이루어져 있다. (6 <= n <= 1000000)
> 2. n = a + b 형태로 출력하되, a와 b는 홀수 소수이다. 
> 3. n을 만들 수 있는 방법이 여러 가지라면 b - a가 최대가 되도록 출력한다. …

21-xxubin04

---

gjsk132/DP/2156 포도주 시식.py
gjsk132/README.md

[백준 2156 : 포도주 시식](https://www.acmicpc.net/problem/2156)
40분
🎯 문제 이해
---
**알고리즘 분류 : DP**
이 문제를 처음 봤을 땐, 무작정 결과값을 크게하는 것만 생각할 수 있는데, 이전의 마시는 경우와 아닌 경우를 생각하고, 이후에 갈 수 있는 지점을 생각하다 보면 DP의 점화식이 복잡해지거나 바로 이전 값만을 쓰는게 아니기 때문에 값이 중복이 될 수도 있다.
그래서 약간 다르게 생각해줬다.
안 마시는 포도주를 가장 적게하면 되지 않을까하는 생각으로 코드를 짜니까 조금 더 쉽게 구할 수 있었다.
<image src="https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/7208267f-12fe-481b-9464-542dd35de31d" width=80%>
위 이미지 과정에 맞춰 코드를 짜주면 된다.
🔍코드 설명
---
``wine`` : 포도주의 수
``amount`` : 각 포도주의 양
``total`` : 모든 포도주의 양
포도주의 수와 각 포도주의 양을 입력받고, 총 포도주의 양 변수에 저장해둔다.
>**총 포도주 양을 저장하는 이유?**
>마지막에 총량에서 가장 적은 양을 피하는 값을 빼야한다.
>하지만 최솟값을 구하고 나면 ``amount``에는 이미 값이 여러 개가 중복으로 더해진 상태이기 때문에 미리 더해준다.
```py
wine = int(input())
amount = [int(input()) for i in range(wine)]
total = sum(amount)
```
**핵심 …

15-gjsk132

---

gjsk132/Prefix Sum/11660 구간 합 구하기 5.py
gjsk132/README.md

[백준 11660: 구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
30분
🎯 문제 이해
---
**알고리즘 분류 : 누적합 (Prefix Sum)**
>**누적합?**
>순서대로 정렬된 값들을 차례로 더해가면서 **현재까지의 합을 계속 누적**하는 개념
>
>반복문을 사용하여 특정 구간의 인덱스를 하나씩 더해가는 방식의 시간 복잡도 : O(n^2)
>**누적합을 활용하는 방식은 시간 복잡도 : O(n)**
>
>누적합이 훨씬 효율적인 걸 알 수 있다.
아래와 같은 방법으로 누적합을 구해준다.
<image src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/ffe4e148-c77c-4af0-8e2b-4f387034cd50" width=500>
그리고 특정 구간에서의 누적합은 각 인덱스에 저장된 누적합의 차를 이용해서 구할 수 있다.
여기서 2번 빼주는 구간이 생기므로 그 부분의 1번 더해야한다.
<image src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/41c765c5-d1b0-44df-9608-7a698437de2d" width=500>
``[ x, y ]`` : 처음부터 현재 위치까지의 누적합이 저장되어 있는 곳
🔍코드 설명
---
``size`` : ``table``의 크기
``order`` : 주어진 구간의 수
``table`` : (1, 1)부터 해당 인덱스까지의 누적합
각 변수, 배열에 입력값을 받는다.
```py …
```

16-gjsk132

---

xxubin04/README.md
xxubin04/Sieve of Eratosthenes/1124_언더프라임.py

2024-01-22 1124번_언더프라임
[1124번: 언더프라임](https://www.acmicpc.net/problem/1124)
<br>
30분
<br>
주어진 범위 내의 언더프라임 개수를 구하자.
<br>
> 언더프라임 = 소인수분해해서 구한 소수들의 길이가 소수인 수
<br>
Ex)
7 -> 1 x 7 (소수 1개) -> 언더프라임 X
8 -> 2 x 2 x 2 (소수 3개) -> 언더프라임 O
<br>
```python
a, b = map(int, input().split())
primeCheck = [0, 0] + [1] * (b-1)
primes = []
for i in range(2, b+1):
if primeCheck[i] == 0:
continue
for j in range(i*2, b+1, i):
primeCheck[j] = 0
primes.append(i)
```
- a <= X <= b 구간의 수에서 언더프라임을 구해준다.
- 에라토스테네스의 체를 이용하여 primes에 소수들을 넣어준다.
- primeCheck에서 i가 1이면 소수이므로 primeCheck에서 i의 배수들을 전부 0 처리해주고 primes에 i를 추가한다.
- 범위에서 전부 확인해주면, prime은 소수들로 이루어지게 된다.
<br>
```python
ans = 0
for p in range(a, b+1):
cnt = 0
for k in primes:
if p == 1:
break
while p % k == 0:
p /= k
cnt += 1
if cnt in primes:
ans += 1
print(ans) …
```

22-xxubin04

---

Dolchae/DP/11060 점프 점프.py
Dolchae/README.md

[11060 점프 점프](https://www.acmicpc.net/problem/11060)
50분 + α
1xN 크기의 미로에서 각 칸에 쓰여 있는 정수 이하만큼 한 번에 점프할 수 있을 때 가장 왼쪽에서 오른쪽으로 가는 최소 점프 횟수를 구하는 문제이다.
<br>
```python
jump = list(map(int, input().split()))
dp = [n+1] * n
dp[0] = 0
```
- 미로의 크기 n과 각각의 칸에 쓰여있는 수들을 jump 리스트에 저장한다.
- dp 리스트는 각 위치까지의 최소 점푸 횟수를 저장한다. 초기값은 n+1로 저장해 후의 if문에서 도달할 수 없는 케이스를 구별할 수 있도록 한다.
- dp[0]은 시작 위치이므로 0으로 초기화한다.
<br>
```python
for j in range(1, jump[i]+1):
if i+j < n:
dp[i+j] = min(dp[i]+1, dp[i+j])
```
- i는 현재 위치를 나타내고, 1부터 jump[i]까지 반복하며 각 위치로 점프할 수 있는지 확인한다.
- i+j가 n보다 작다면 범위를 넘어가지 않아 점프할 수 있음을 나타내므로 dp[i]+1, dp[i+j] 중 작은 값을 dp[i+j]에 저장한다.
- dp[i]+1는 현재 위치까지의 최소 점프 횟수에 1을 더한 값이고, dp[i+j]는 현재 위치로부터 j만큼 점프해 도달하는 위치의 최소 점프 횟수이다. 
<br>
```python
if dp[n-1] …
```

23-Dolchae

---

xxubin04/README.md
xxubin04/그리디/2872_도서관.py

2024-01-25 2872번_우리집엔 도서관이 있어
[2872번 : 우리집엔 도서관이 있어](https://www.acmicpc.net/problem/2872)
<br>
1시간
<br>
쌓여진 책을 오름차순대로 쌓으려면 몇 번 책을 옮겨야 하는지 알아내는 문제이다.
단, 책을 옮길 때는 맨 위에만 올릴 수 있다. (중간에 끼워넣을 수 없다.)
<br>
> 책 3권이 위에서부터 `3 2 1`으로 쌓여있다면, 오름차순인 `1 2 3`으로 쌓기 위해서는 2를 맨 위로 올려 `2 3 1`을 만들어준다. 
> 그러고 나서 1을 맨 위로 올려 `1 2 3`으로 만들어줄 수 있으므로 2번만에 책을 정렬할 수 있다.
> 
> 3     ....     2       ....     1
> 2    ->     3    ->    2
> 1     ....       1      ....      3
<br>
<details>
<summary>첫 번째 도전</summary>
<div markdown="1">
```python
books = list(int(input()) for _ in range(int(input())))
cnt = 0
for i in range(len(books), 1, -1):
if books.index(i) > books.index(i-1):
continue
else:
books.remove(i-1)
books.insert(0, i-1)
cnt += 1
print(cnt)
```
</div>
</details>
<br>
처음에 규칙을 고민해보았을 때는 …

23-xxubin04

---

xxubin04/DP/1495_기타리스트.py
xxubin04/README.md

2024-01-29 1495번_기타리스트
[1495번 : 기타리스트](https://www.acmicpc.net/problem/1495)
<br>
1시간 30분
<br>
가능한 마지막 곡의 볼륨 중 최댓값을 구해야 한다. 
`예제 1`을 예로 들어 이해하면 다음과 같다.
`곡의 개수 num = 3` / `시작 볼륨 start = 5` / `볼륨의 최댓값 maximum = 10`
`곡의 볼륨 리스트 volumes = 5, 3, 7`
<br>
<br>
> 현재의 볼륨이 P이고 i번째 곡을 연주하기 전이라면,  곡을 연주하고 나서 도출될 수 있는 볼륨은 `P - volumes[i]` 와 `P + volumes[i]` 이다. 
> 즉, 곡의 볼륨은 현재의 볼륨에서 빼거나 더하는 경우만 가능하다.
<br>
<details>
<summary>메모리 초과 코드</summary>
<div markdown="1">
```python
num, start, maximum = map(int, input().split())
volumes = list(map(int, input().split()))
dp = [[start]] + [[] for _ in range(num)]
for i in range(num):
for j in dp[i]:
if i < num and 0 <= j - volumes[i] <= maximum:
dp[i+1].append(j - volumes[i])
if i < num and 0 <= j + volumes[i] <= maximum:
dp[i+1].append(j …
```

24-xxubin04

---

Dolchae/README.md
Dolchae/수학/2108 통계학.py

[2108 통계학](https://www.acmicpc.net/problem/2108)
45분
주어진 값들에 대한 산술 평균, 중앙값, 최빈값, 범위를 구해 출력하는 문제이다. 
- 주어진 값의 개수는 항상 홀수이다.
- 최빈값이 여러 개일 경우 두 번째로 작은 수를 출력한다.
<br>
```python
import sys
input=sys.stdin.readline
num_list = []
i = int(input())
num_list.append(i)
num_list.sort()
print(round(sum(num_list)/n)) #산술평균
print(num_list[n//2]) #중앙값
```
- 입력 받을 값의 개수를 n에 저장하고 num_list에 조작할 값들을 저장해 정렬한다.
- 산술평균과 중앙값을 각각 출력한다.
- 반올림을 하기 위해 round 함수를 써주었다.
- n이 항상 홀수이기 때문에 중앙값을 바로 n//2로 처리해준다.
<br>
```python
dic = {}
for i in num_list:
if i in dic.keys():
dic[i] += 1
else:
dic[i] = 1
max_num = max(dic.values())
max_list = []
for i in dic:
if max_num == dic[i]:
max_list.append(i)
```
최빈값을 구하기 위한 딕셔너리이다. 
- key에는 입력받은 값을 value에는 그 숫자의 등장 횟수를 저장한다.
- max_num에 가장 큰 등장 횟수를 저장해 …

24-Dolchae

---

gjsk132/README.md
gjsk132/Stack/1698 옥상 정원 꾸미기.py

[백준 1698 : 옥상 정원 꾸미기](https://www.acmicpc.net/problem/1698)
1시간 40분
🎯 문제 이해
---
**알고리즘 분류 : 자료구조 - 스택 (Stack)**
>문제 : 오른쪽에 자신보다 같거나 큰 건물이 나오기 전까지의 건물 수 구하기
단순히 한 건물에서 다음 같거나 큰 건물이 나올 때까지 탐색하는 경우, 시간 초과가 난다.
실제로, 시간 초과가 떴다...
그래서 볼 수 있는 건물의 수를 합치는 방법을 생각해냈다.
쉽게 설명하자면...
자신의 **왼쪽 건물이 자신의 건물보다 크다면**, **내가 볼 수 있는 건물은 왼쪽 건물 또한 볼 수 있다**는 걸 사용하였다.
만약 왼쪽 건물에 가려졌다면, 그 너머에 있는 건물들이 왼쪽 건물을 볼 수 있냐 없냐에 따라 자신의 건물을 볼 수 있는지도 결정난다.
따라서, 왼쪽 건물에 합쳐준다.
🔍코드 설명
---
``building`` : 건물의 높이와 볼 수 있는 건물 수
``n`` : 건물 수
우선 입력된 값을 받아준다.
```py
building = [[int(input()),0] for _ in range(n)]
```
**핵심 코드**
```py
top = n - i - 1
while top:
if building[top][0] < building[top-1][0]:
building[top-1][1] += building[top][1] + 1
cnt += building[top][1]
building.pop(top)
break
else:
top -= 1
``` …

17-gjsk132

---

9-kyo-hwang/Disjoint Set/2023 KAKAO BLIND RECRUITMENT 표 병합.cpp
9-kyo-hwang/README.md

[2023 KAKAO BLIND RECRUITMENT 문제 5 - 표 병합](https://school.programmers.co.kr/learn/courses/30/lessons/150366)
2시간 정도?
표 편집 프로그램을 작성한다. 표의 크기는 50 × 50으로 고정되어있고 초기에 모든 셀은 비어 있다. 각 셀은 문자열 값을 가질 수 있다.
프로그램은 다음과 같은 명령어를 지원한다.
1. ```"UPDATE r c value"```
- (r, c) 위치의 셀을 선택해 값을 value로 바꾼다.
2. ```"UPDATE value1 value2"```
- value1을 값으로 가지고 있는 모든 셀을 선택해 값을 value2로 바꾼다.
3. ```"MERGE r1 c1 r2 c2"```
- (r1, c1) 위치의 셀과 (r2, c2) 위치의 셀을 선택하여 병합한다. 이 때 선택한 두 위치의 셀이 같은 셀일 경우 무시한다.
- 선택한 두 셀은 서로 인접하지 않을 수도 있는데, 이 경우 (r1, c1) 위치의 셀과 (r2, c2) 위치의 셀만 영향을 받으며 그 사이에 위치한 셀들은 영향을 받지 않는다.
- 두 셀 중 한 셀이 값을 가지고 있을 경우 병합된 셀은 그 값을 가지게 되며, 두 셀 모두 값을 가지고 있을 경우 병합된 셀은 (r1, c1) 위치의 셀 값을 가지게 된다.
- 이후 (r1, c1) 와 (r2, c2) 중 어느 위치를 선택하여도 병합된 셀로 접근한다.
4. ```"UNMERGE r c"```
- (r, c) 위치의 셀을 선택하여 해당 셀의 모든 병합을 해제한다.
- 선택한 셀이 포함하고 …

23-9kyo-hwang

---

gjsk132/Implementation/12904 A와 B.py
gjsk132/README.md

[백준 12904 : A와 B](https://www.acmicpc.net/problem/12904)
20분
🎯 문제 이해
---
**알고리즘 분류 : 구현**
> 문제 설명
> (문자열 그대로 + A추가) / (문자열 반대로 + B추가)
> 위 2개 중에 하나를 선택하여 원하는 문자열 만들기
문자열을 하나씩 붙여가며 목표와 비교해서 원하는 결과를 만드는 방법이 가장 먼저 떠오지만 코드를 짜기에는 뭔가 난이도가 올라간다.
약간만 다르게 생각하면 훨씬 쉽고 간단하게 문제를 해결할 수 있다.
문제를 다시 살펴보면, 이 문제의 문자를 추가하는 두 가지 조건은 공통적으로 문자열을 그대로 두거나 뒤집은 후, **문자열 제일 끝에 문자가 추가**한다.
이걸 생각하면, 원하는 문자열을 처음 주어진 문자열로 만드는 편이 훨씬 간단하다는 것을 알 수 있다.
왜냐하면, **마지막 문자를 보면 문자열이 뒤집힌 것인지 아닌지를 알 수 있기 때문**이다.
**ex.**
BABA와 같이 **마지막 문자가 A**인 경우
이전에는 **BAB**라는 걸 알 수 있다.
BAAB와 같이 **마지막 문자가 B**인 경우
이전에는 **BAA를 뒤집은 AAB**라는 걸 알 수 있다.
🔍코드 설명
---
``target`` : 처음 입력된 문자열
``words`` : 결과적으로 만들고자 하는 문자열
우선 두 변수를 입력받는다.
```py
target = input()
words = list(input())
```
**핵심 코드**
문자를 추가하는 과정만 있기 때문에, 문자열의 길이로 추가될 문자의 수를 알 수 있다.
만약 ``pop``해서 나온 …

18-gjsk132

---

xxubin04/README.md
xxubin04/구현/13. Roman_to_Integer.py

2024-02-01 13_Roman to Integer
[13. Roman to Integer](https://leetcode.com/problems/roman-to-integer/)
<br>
20분
<br>
주어지는 로마자 문자열을 숫자로 변환하여 반환하는 문제이다.
```python
dic1 = {'I':1, 'V':5, 'X':10, 'L':50, 'C':100, 'D':500, 'M':1000}
dic2 = {'IV':4, 'IX':9, 'XL':40, 'XC':90, 'CD':400, 'CM':900}
```
문제에서 주어지는 로마자는 한 글자로 이루어진 것과 두 글자로 이루어진 것 2가지가 있다.
이에 주의하여 문제를 풀면 된다.
<br>
```
total = 0
dic1 = {'I':1, 'V':5, 'X':10, 'L':50, 'C':100, 'D':500, 'M':1000}
dic2 = {'IV':4, 'IX':9, 'XL':40, 'XC':90, 'CD':400, 'CM':900}
check = [0 for _ in range(len(s))]
```
- dic1에는 한 글자 로마자와 그에 해당하는 값을 딕셔너리 형태로 저장한다.
- dic2에는 두 글자 로마자와 그에 해당하는 값을 딕셔너리 형태로 저장한다.
- check는 로마자를 방문하였는지의 여부를 확인해주기 위해서 만들어준다.
<br>
```python
for i in range(len(s)):
if check[i] != 0:
continue
if s[i:i+2] in dic2:
total += dic2[s[i:i+2]] …
```

25-xxubin04

---

Dolchae/DP/1535 안녕.py
Dolchae/README.md

[1535 안녕](https://www.acmicpc.net/problem/1535)
50분
체력이 100이고 기쁨은 0에서 시작할 때, 주어진 각각의 사람들에게서 받을 수 있는 기쁨과 써야하는 체력이 주어질 때 최대 기쁨을 출력하는 문제이다.
<br>
```python
import sys
stamina = [0]+list(map(int,input().split()))
joy = [0] + list(map(int,input().split()))
dp = [[0]*101 for _ in range(n+1)]
```
사람의 수 n과 체력 stamina, 기쁨 joy를 입력받고 dp 리스트를 만든다.
- 체력과 기쁨 리스트의 0번째에는 0을 넣어 후의 인덱스 조절에 용이하도록 한다.
- dp 리스트는 체력의 범위인 0~100, 사람 수의 범위인 n으로 설정한다.
<br>
```python
for i in range(1,n+1):
for j in range(1,101):
if stamina[i] <= j:
dp[i][j] = max(dp[i-1][j], dp[i-1][j-stamina[i]] + joy[i])
else:
dp[i][j] = dp[i-1][j]
print(dp[n][99])
```
- i는 현재까지 고려한 사람의 수, j는 체력 소모량을 나타낸다.
- 현재 고려 중인 체력 소모량이 j보다 작거나 같다면 인사할 수 있다.
- dp[i][j]는 i번째 사람까지 고려했을 때, 체력 소모량이 j일 때 얻을 수 있는 최대 기쁨이다. …

25-Dolchae

---

Dolchae/README.md
Dolchae/구현/18110 solved.ac.py

[18110 solved.ac](https://www.acmicpc.net/problem/18110)
1시간
solved.ac가 문제의 난이도를 결정하는 방식을 구현하는 문제이다.
1. 의견이 아무것도 없다면 난이도는 0이다.
2. 의견이 하나 이상 있다면 난이도는 모든 사람의 의견의 30% 절사평균이다.
<br>
```python
import sys
def my_round(val):
if val - int(val) >= 0.5:
return int(val)+1
else:
return int(val)
```
반올림 처리를 해주는 my_round 함수이다.
- 소수점 첫째자리가 5 이상이면 1 올려주고, 그렇지 않다면 int로 바꿔 버림해준다.
<br>
```python
n = int(sys.stdin.readline().strip())
if n:
level = []
level.append(int(sys.stdin.readline().strip()))
level.sort()
nn = my_round(n*0.15)
if nn > 0:
print(my_round(sum(level[nn:-nn])/len(level[nn:-nn])))
else:
print(my_round(sum(level)/len(level)))
else:
print(0)
```
의견 개수 n을 입력받고 n이 1 이상이면 다음을 수행하고, 0이라면 print(0)을 한다.(else문)
- 난이도 의견을 level 리스트에 저장하고 오름차순으로 정렬한다.
- n에 대한 …

26-Dolchae

---

xxubin04/README.md
xxubin04/Sieve of Eratosthenes/4948_베르트랑 공준.py

[4948_베르트랑 공준](https://www.acmicpc.net/problem/4948)
<br>
40분
<br>
> 베르트랑 공준 = n보다 크고, 2n보다 작거나 같은 소수는 적어도 하나 존재
각 테스트 케이스에 대해, **n보다 크고 2n보다 작거나 같은 소수의 개수**를 출력하자.
<br>
- 제한 : 1 <= n <= 123,456
```python
primes = [0, 0] + [1] * (123456**2-1)
for i in range(2, 123455):
if primes[i] == 1:
for j in range(2*i, (123456**2-1), i):
primes[j] = 0
```
무식하게 위와 같이 달려들었더니 당연하게도 **메모리초과**가 났다.
굳이 제한된 범위까지의 소수를 전부 구해둘 필요가 있을까? 
<br>
```python
while (num := int(input())) != 0:
if num in [1, 2]:
print(1)
```
드디어 [바다코끼리](https://int-i.github.io/python/2020-05-29/python-walrus-operator/)를 써먹었다! 
num이 0이 아니라면 계속 while문을 순회하게 된다.
<br>
num이 1이거나 2인 경우는 1을 출력해준다. 
- num=1 : `for i in range(2, int((num*2)**0.7)`에서 `range(2, 1)`이 되므로 ~~이상해진다.~~
- 이상해진 것 같아서 따로 print(1)해주었지만, 금방 확인해본 결과 결과값이 잘 나온다. 굳이 나눠서 써줄 필요 …

26-xxubin04

---

gjsk132/Knapsack Problem/12865 평범한 배낭.py
gjsk132/README.md

[백준 12865 : 평범한 배낭](https://www.acmicpc.net/problem/12865)
1시간
🎯 문제 이해
---
**알고리즘 분류 : Knapsack Problem(DP)**
배낭에 넣을 수 있는 무게에는 한계가 있다.
그 한계 내에서 짐의 무게를 고려하여 짐들을 조합해서 넣어야 한다.
그 중에서도 배낭에 담은 짐들의 총 가치가 가장 큰 경우를 선택해야 한다.
<image src ="https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/0441a6fa-22bf-4b04-a33b-856e74b91167" wight=100>
>위와 같은 상황에서는
>각각 하나씩 담거나 물과 손전등을 같이 담는 경우가 있다.
>그 중에서도 물과 손전등을 담는 경우가 가치가 8+6 으로 가장 높다.
나는 그중에서도 DP Bottom-Up 방법을 사용하여 문제를 풀었다.
🔍코드 설명
---
``loads`` : 총 짐의 수
``bag`` : 배낭에 넣을 수 있는 무게 제한
``dp`` : 각 무게 당 배낭에 넣은 짐의 총 가치 ( 최댓값 )
우선 입력을 받고, 짐의 수 만큼 배열을 만들어준다.
```py
loads, bag = map(int,input().split())
dp = [[0 for i in range(bag+1)] for _ in range(loads+1)]
```
**핵심 코드**
짐을 하나씩 받아가면서 dp에 차례로 저장할 것이다.
짐의 무게와 가치를 입력받는다.
짐의 무게 이상의 배낭에만 해당 짐을 넣을 수 있기 때문에
``p``(배낭에 …

20-gjsk132

---

9-kyo-hwang/Brute Force/조이스틱.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Tree/2023 KAKAO BLIND RECRUITMENT 표현 가능한 이진트리.cpp

[조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
거의 3시간
- 레벨 2 -> 레벨 2 아닌 것 같음
- 그리디 -> 완전탐색임
영어 대문자로 이루어진 문자열이 주어진다. 우리는 조이스틱을 움직이는 횟수를 최소로 해 주어진 문자열을 만들어야 한다. 조이스틱이 할 수 있는 동작은 다음과 같이 4가지다.
▲ - 다음 알파벳
▼ - 이전 알파벳 (A에서 아래쪽으로 이동하면 Z로)
◀ - 커서를 왼쪽으로 이동 (첫 번째 위치에서 왼쪽으로 이동하면 마지막 문자에 커서)
▶ - 커서를 오른쪽으로 이동 (마지막 위치에서 오른쪽으로 이동하면 첫 번째 문자에 커서)
예를 들어 "JAZ"를 만들고자 하면, "AAA"에서 
- 첫 번째 위치에서 조이스틱을 위로 9번 조작하여 J로 변경한다.
- 조이스틱을 왼쪽으로 1번 조작하여 커서를 마지막 문자 위치로 이동시킨다.
- 마지막 위치에서 조이스틱을 아래로 1번 조작하여 Z로 변경한다.
따라서 11번 이동시켜 "JAZ"를 만들 수 있고, 이때가 최소 이동이다.
고려해야 할 건 1. 상하 이동 2. 좌우 이동이다.
상하 이동은 쉽게 알 수 있다. A ~ Z까지 26개의 알파벳이 있는데, A쪽에 가까운 절반은 위로 올리면 되고 Z쪽에 가까운 절반은 아래로 내리면 된다.
문제는 좌우 이동인데, 그리디 카테고리에 있길래 당연히 그리디하게 접근했다. 떠올린 방식은 현재 위치에서 좌, 우에 A가 아닌 문자가 가까이 있는 쪽으로 이동하는 거였다.
예시의 "JAZ"에서 바로 알 수 있는데, J를 A로 바꾸고 나면 …

25-9kyo-hwang

---

xxubin04/README.md
xxubin04/수학/2885_초콜릿 식사.py

2024-02-08 2885_초콜릿 식사
[2885번: 초콜릿 식사](https://www.acmicpc.net/problem/2885)
<br>
40분 + α
<br>
> K개의 정사각형 초콜릿을 갖기 위해서 구매해야 하는 초콜릿의 크기와 쪼개야 하는 최소 횟수를 구해야 한다.
<br>
**조건**
1. 막대 초콜릿은 정확히 절반으로만 나눌 수 있다. (N길이의 막대 초콜릿 -> N/2길이의 막대 초콜릿 2개)
2. 초콜릿의 크기는 항상 2의 제곱 형태이다. (1, 2, 4, 8, 16, ...)
3. 한 조각이 K개일 필요 없이, 여러 조각을 합쳤을 때 K개이면 된다.
<br>
<br>
```python
square = int(input())
size = 1
while size < square:
size *= 2
```
<br>
`square`에 만들어야 하는 정사각형의 크기를 입력받는다.
상근이가 구매해야하는 가장 작은 초콜릿의 크기인 `size`를 구하는 과정은 다음과 같다.
1부터 시작해서 square보다 size가 커지기 전까지 2를 곱해주면 된다. **초콜릿의 크기는 2의 제곱**(1, 2, 4, 8, ...)이면서 **가장 작은 초콜릿의 크기**를 구해야하므로 size를 넘지 않는 2의 제곱을 구하면 되는 것이다.
<br>
```python
i = size
cnt = 0
if square == size:
print(size, 0)
```
<br>
**| square = size**
`i` = size의 수와 같게 설정 (마지막에 size를 출력해야 하므로 size변수는 변화시키면 안되어서 따로 …

27-xxubin04

---

Dolchae/README.md
Dolchae/정렬/1302 베스트셀러.py

[1302 베스트셀러](https://www.acmicpc.net/problem/1302)
20분
책의 제목이 입력으로 들어올 때 가장 많이 팔린 책의 제목을 출력한다.
- 많이 팔린 책이 여러 개일 경우에는 사전 순으로 앞서는 제목을 출력한다.
<br>
```python
import sys
books = {}
now = input()
if now in books.keys():
books[now] += 1
else:
books[now] = 1
```
- 팔린 책의 개수 n과 책의 제목과 그 책의 판매량을 저장할 딕셔너리 books를 만들어 입력받는다.
<br>
```python
max_value = max(books.values())
max_keys = [key for key, value in books.items() if value == max_value]
max_keys.sort()
print(max_keys[0])
```
- max_value에 가장 큰 value 값(가장 많은 판매량 값)을 저장하고 이를 이용해서 max_keys에 가장 많이 팔린 책을 리스트로 저장한다.
- 책이 여러 개인 경우 사전 순으로 가장 앞서는 제목을 출력해야 하므로 정렬해준 뒤 가장 앞의 값을 출력해준다.
<br>
```python
import sys
books = {}
now = input()
if …
```

27-Dolchae

---

gjsk132/README.md
gjsk132/Sort/좌표 압축.txt

[백준 18870 : 좌표 압축](https://www.acmicpc.net/problem/18870)
20분
🎯 문제 이해
---
> **문제**
> 좌표의 총 수와 좌표들이 입력된다.
> 입력된 좌표들을 압축한 결과를 출력한다.
좌표 압축 예시
|입력|2|4|-10|4|-9|
|---|---|---|---|---|---|
|출력|2|3|0|3|1|
입력되는 값을 중복이 없이 정렬하면, -10, -9, 2, 4 이다.
이 순서대로 각 값에 0, 1, 2, 3이라는 값을 넣어주면 표의 출력과 같은 모습인 것을 알 수 있다.
**전체적인 풀이과정**
1. 입력된 숫자들을 리스트로 받는다.
2. 숫자 리스트를 집합을 사용해서 중복을 제거해주고, 정렬해준다.
3. 딕셔너리를 이용해서 정렬한 집합에서 몇 번째에 있는지 정의한다.
4. 맨 처음 입력된 숫자 리스트를 순회하면서, key에서 value로 바꿔준다.
5. 변경된 리스트를 출력해준다.
**집합을 사용한 이유?**
자동으로 중복되는 값이 사라지기 때문에 사용한다.
**딕셔너리를 사용한 이유?**
같은 숫자가 여러 번 반복해서 들어갈 때, 그때마다 오름차순으로 정렬된 집합에서 몇 번째에 있는지 탐색하면 복잡해진다.
어짜피 한 종류의 숫자는 한 숫자로 바뀌기 때문에 딕셔너리로 바뀔 값을 정해주고, 전체 리스트를 순회해서 값을 바꿔준다.
🔍코드 설명
---
위에서 이야기한 순서대로 진행한다.
1. 입력되는 값들을 리스트로 받는다.
```py
cnt = int(input())
origin = list(map(int,input().split()))
```
2. 숫자 …

23-gjsk132

---

Dolchae/README.md
Dolchae/구현/13414 수강신청.py

[13414 수강신청](https://www.acmicpc.net/problem/13414)
40분
주어진 방법에 따른 수강신청 시스템에서 수강신청에 성공한 인원을 출력하는 문제이다. 
1. 수강신청 버튼 활성화 된 후, 버튼을 누른 순서대로 대기목록에 들어간다.
2. 이미 대기목록에 있는 상태에서 다시 수강신청을 누르면 대기목록의 맨 뒤로 밀려난다.
3. 잠시 후 수강신청 버튼 비활성화 되면, 수강 가능 인원에 맞춰 가장 앞의 학생부터 수강신청이 완료된다. 
<br>
```python
import sys
students_num, signup_num = map(int,input().split())
signup = []
for _ in range(signup_num):
now = input()
if now in signup:
signup.remove(now)
signup.append(now)
else:
signup.append(now)
for i in range(students_num):
print(signup[i])
```
입력받는 모든 정보를 리스트로 받고 조작하는 방식으로 접근했다가 바로 시간초과가 났다. 그래서 어떻게 할까 하다가 알고리즘 분류를 보았더니 **해시를 사용한 집합과 맵**이 있어서, 딕셔너리를 이용해 다시 구현해보았다.
<br>
```python
import sys
signup_num, students_num = map(int,input().split())
signup = {}
for i in …
```

31-Dolchae

---

Dolchae/README.md
Dolchae/구현/13414 수강신청.py
Dolchae/그리디/2012 등수 매기기.py

[2012 등수 매기기](https://www.acmicpc.net/problem/2012)
30분?
주어지는 예상 등수에 따라 불만도의 합을 최소로 만드는 문제이다.
- 이때 등수를 매길 때는 동석차가 없어야 한다.
- 불만도 = | 학생의 예상 등수 - 실제 등수 | (차이)
<br>
**예제 1**
(예상)  ->  (실제)
1       ->    1
1        ->   2
2        ->   3
3        ->   4
5        ->   5
실제 등수가 2,3,4등인 사람의 불만도가 각각 +1이 되어 총 불만도는 3이 출력된다.
```python
import sys
expected_rank = []
ans = 0
expected_rank.append(int(input()))
expected_rank.sort()
```
학생 수 n, 예상 등수 expected_rank를 입력받고 예상 등수는 오름차순 정렬해준다. ans는 불만도의 총합으로, 후에 출력할 값이다.
<br>
```python
ans += abs(expected_rank[i] - (i+1))
print(ans)
```
n만큼 for문을 반복하며 불만도(ans)에 (예상 등수 - 실제 등수)의 절댓값을 더해주고 출력한다.
<br>
```python
import sys
expected_rank = …
```

32-Dolchae

---

9-kyo-hwang/README.md
9-kyo-hwang/Shortest Path/2022 KAKAO TECH INTERNSHIP 코딩 테스트 공부.txt

[2022 KAKAO TECH INTERNSHIP 코딩 테스트 공부](https://school.programmers.co.kr/learn/courses/30/lessons/118668)
거의 4시간...
코딩 테스트 문제를 풀기 위해서는 알고리즘에 대한 지식과 코드를 구현하는 능력이 필요하다. 이를 각각 알고력, 코딩력이라 하자. 이들은 각각 0 이상의 정수로 표현된다. 
예를 들어, 현재 알고력이 15, 코딩력이 10이라고 가정해보자.
- A라는 문제가 알고력 10, 코딩력 10을 요구한다면 A 문제를 풀 수 있다.
- B라는 문제가 알고력 10, 코딩력 20을 요구한다면 코딩력이 부족하기 때문에 B 문제를 풀 수 없다.
풀 수 없는 문제를 해결하기 위해서는 알고력과 코딩력을 높여야 한다. 다음과 같은 방법으로 높일 수 있다.
- 1의 시간을 들여 알고력 1을 높인다.
- 1의 시간을 들여 코딩력 1을 높인다.
- 현재 풀 수 있는 문제 중 하나를 풀어 알고력과 코딩력을 높인다. 각 문제마다 문제를 풀면 올라가는 알고력과 코딩력은 정해져 있다.
- 문제를 하나 푸는 데는 문제가 요구하는 시간이 필요하며, 같은 문제를 여러 번 푸는 것이 가능하다.
주어진 모든 문제들을 풀 수 있는 알고력과 코딩력을 얻는 최단시간을 return 하도록 solution 함수를 작성하라.
처음 지문을 봤을 때, 한창 배낭 문제가 유행하던 시기라 뭔가 오버랩 돼보였다. "아 씁 DP라고? 나 DP 못하는데..." 하면서 뚫어져라 쳐다봤다.
이 때 눈에 띈 게 "최단시간"이었다. 현재 주어진 (알고력, 코딩력)에서 (목표 알고력, …

32-9kyo-hwang

---

gjsk132/Greedy/15903 카드 합체 놀이.py
gjsk132/README.md

[백준 15903 : 카드 합체 놀이](https://www.acmicpc.net/problem/15903)
20분
🎯 문제 이해
---
**알고리즘 유형 : 그리디 (greedy)**
> **문제 요약**
> 주어진 카드에는 자연수가 쓰여져 있다.
> 자연수 카드 중에서 2개를 더한다.
> 더한 값을 이전의 값에 덮어준다.
> **카드가 합쳐지는 횟수가 이후에,  카드의 총 합이 가장 작은 수**를 구한다.
>
> 예시
> 주어진 카드 : 2, 3, 6
> 합체 > 가장 작은 ( 2, 3 ) > 2 + 3 = 5
> 1회 합체한 카드 : 5, 5, 6
> 결과 : 5 + 5 + 6 = 16
**문제 접근**
합체하는 과정을 생각해보면, 선택된 자연수가 한 번씩 더해진다고 생각하면 된다.
선택 숫자 : 2, 3
선택한 수의 합 : 5
결과 : 2+3, 3+2
결과의 합 : 10
이 점을 생각했을 때 합체 후 카드의 총 합이 가장 작으려면, 
매 단계마다 가장 작은 두 자연수를 합치면 된다는 것을 알 수 있다.
**그리디 알고리즘 접근**
단계에서 최적( 가장 작은 두 자연수 )의 값을 매번 선택한다는 점에서 그리디 알고리즘을 사용하였다.
**힙 자료구조 접근**
매번 갱신되는 숫자의 리스트 일일히 작은 값 2개를 구하는 방법도 있지만 생각만 해도 복잡하다.
가장 작은 자연수 2개를 쓴다는 점에서, 힙을 사용해주면 훨씬 수월하게 풀 수 있다.
🔍코드 설명
---
`card_cnt` : 카드의 수
`merge_cnt` : 카드를 합치는 횟수
`card_num` : 카드의 수를 기억하는 힙 (`heap`) …

24-gjsk132

---

xxubin04/README.md
xxubin04/해시맵/11101_꿍의 여친 만들기.py

[11101번: 꿍의 여친 만들기](https://www.acmicpc.net/problem/11101)
<br>
40분 + α
<br>
문제를 이해하는 것도 좀 걸린 문제다.
`intelligent:0,cultivated:4,welldressed:2,motorcycleowner:3,rude:8,rich:100`
위와 같이 각각의 조건에 해당하는 시간이 나오고 
`intelligent&cultivated&welldressed|motorcycleowner&rude|rich`
& : and
| : or
이므로 &로 이루어진 조건들에서 가장 많이 걸리는 시간들만 |끼리 비교해주면 된다.
<br>
오늘 개강을 했더니 힘들어서 좀 쉬운 문제를 풀고 싶었는데 노린 건 아니지만 정답률 85% 문제를 풀게 되었다. 
풀고 놀 생각으로 도전했는데 생각보다 안 풀리더라...
사실, 아무리 봐도 틀린 부분이 안보이는데 계속 틀렸다고 떠서 그냥 PR 올리게 되었습니다... 죄송합니다..🙇🏻‍♀️
<br>
```python
end = 1001
for i in range(n := int(input())):
conditions = {}
need = list(input().split(','))
for n in need:
a, b = n.split(':')
conditions[a] = int(b)
cal1 = list(input().split('|'))
cal2 = []
for j in cal1:
cal2.append(nList := list(j.split('&')))
ans = []
cal1 …
```

33-xxubin04

---

gjsk132/Greedy/야근 지수.py
gjsk132/README.md

[프로그래머스 : 야근 지수](https://school.programmers.co.kr/learn/courses/30/lessons/12927#)
30분
🎯 문제 이해
---
**알고리즘 유형 : 그리디 (Greedy)**
> **문제 요약**
> 야근 피로도 : 남은 작업의 제곱의 합
> 1시간 동안 작업량 1을 처리할 수 있다.
> 야근 피로도가 최소가 되도록한다.
> 
> 예시
> 남은 작업량이 [ 3, 2, 1 ] 일 때, 야근 피로도는
> 3^2 + 2^2 + 1^2 = 9 + 4+ 1 = 14 이다.
문제를 푸는 방법은 간단합니다.
특정한 수 만큼 작업량을 감소시켰을 때, 제곱이 최소가 되어야하기 때문에
항상 가장 큰 값을 1씩 차감해주면 됩니다.
위 방법에서, 항상(매순간) 가장 큰 값을 빼준다에서 우선순위 큐를 사용한 그리디 알고리즘을 사용하면 되는 것을 알 수 있습니다.
🔍코드 설명
---
`works` : 남은 작업량을 담은 리스트
`n` : 남은 시간
일단 총 작업량이 남은 시간보다 작다면 바로 0을 반환해줍니다.
```py
if n >= sum(works):
return 0
```
이때까지 사용했던 heapq는 항상 가장 작은 값을 pop해줬기 때문에, 가장 큰 값을 빼주어야하는 경우에는 모든 값을 -로 만들어서 가장 큰 값이 가장 작은 값이 되도록 해줍니다.
```py
works = [-w for w in works]
```
그리고 n이 0이 될 때까지, 가장 작은 값을 빼주고 +1 하여 push 해주고, n도 -1 하면 됩니다.
( 만약 pop한 값이 0 이라면, n은 그대로 둔 …

26-gjsk132

---

Dolchae/README.md
Dolchae/수학/1641 영식이의 손가락.py
Dolchae/정렬/1431 시리얼 번호.py

[1641 영식이의 손가락](https://www.acmicpc.net/problem/1641)
50분
다친 손가락이 있는 왼손으로 숫자를 셀 때 셀 수 있는 최대 숫자를 출력하는 문제이고, 이때 다친 손가락의 번호와 셀 수 있는 횟수는 주어진다. 그리고 숫자를 세는 방식은 엄지부터 1이라고 하면, 1-2-3-4-5-4-3-2-1-2-3..순으로 이루어진다.
<br>
처음엔 for문으로 다 해볼까 하다가 어떻게 구현할지도 잘 모르겠고 시간초과 가능성도 있는 것 같아서 일단 냅다 다 써보았다.
<br>
조금 알아보기 힘들 수도 있을 것 같긴 한데😅 어쨌든 규칙이 몇 가지 보였다.
1. 다친 손가락이 1이나 5인 경우 각각 0과 4에서 +8씩 하면 된다.
2. 다친 손가락이 2~4인 경우, 가능한 횟수가 0,2,4,..일 때 다친 손가락의 번호가 커질수록 1 증가한다.(시작점은 +8)
3. 다친 손가락이 2~4인 경우, 가능한 횟수가 1,3,5..일 때 다친 손가락의 번호가 커질수록 1 감소한다.(시작점은 +8)
이 규칙을 토대로 수식을 만들어서 코드로 구현하였다.
<br>
```python
import sys
hurt = int(input().strip())
hurt_max = int(input().strip())
```
hurt는 다친 손가락 hurt_max는 다친 손가락이 셀 수 있는 횟수를 나타낸다.
<br>
```python
if hurt == 1:
ans = hurt_max*8
elif 2<=hurt<=4:
if hurt_max%2 == 0:
ans = …
```

34-Dolchae

---

xxubin04/README.md
xxubin04/그리디/27972_악보는 거들 뿐.py

[27972번: 악보는 거들 뿐🎼](https://www.acmicpc.net/problem/27972)
<br>
1시간
<br>
```python
5
3 1 5 4 2
----------
6
3 1 1 2 1 3
```
문제 이해하는게 꽤나 힘들었다...😑
첫 번째 줄에 음의 개수를 입력받고 두 번째 줄엔 음의 높이를 입력받는다.
> 직전에 친 음의 높이 > 현재 칠 음의 높이 -> 악보에 남긴 앞의 음보다 -1
> 직전에 친 음의 높이 < 현재 칠 음의 높이 -> 악보에 남긴 앞의 음보다 +1
> 직전에 친 음의 높이 = 현재 칠 음의 높이 -> 악보에 남긴 앞의 음과 동일하게
테스트 케이스1을 예시로 이해해보면 다음과 같다.
최대한 가장 작은 음의 높이를 출력해야하므로 최솟값을 구해준다.
<br>
많은 방법을 고민해봤는데 계속 반례가 생겼다. 그래서 블로그에서 아이디어를 겟했다🥲👍
> 연속적으로 증가 혹은 감소하는 정도 = 음의 높이의 최솟값
<br>
```python
input = open(0).readline 
std_up, std_down, max_ans = 0, 0, 0
notes = list(map(int, input().split()))
```
(지금 코드 보니 std_up과 std_down을 반대로 썼네요..😮 PR은 올바르게 쓰겠습니다..!)
음의 개수를 `n`에, 음의 종류들을 `notes`에 입력받는다.
`std_up` : 직전의 음의 높이보다 할 예정인 음의 높이가 높아 +1해주는 변수
`std_down` : 직전의 음의 높이보다 할 예정인 음의 높이가 …

34-xxubin04

---

9-kyo-hwang/Graph Traversal/1520 내리막길.cpp
9-kyo-hwang/README.md

[1520 내리막길](https://acmicpc.net/problem/1520)
20분?
(N x M) 크기의 지도 정보가 주어진다. 지도의 각 칸에는 해당 지점의 **높이** 값이 저장돼있다.
(0, 0) 좌표에서 (N - 1, M - 1) 좌표로 이동하는데 **항상 높이가 더 낮은 지점으로만** 이동하고자 한다. 예를 들어 위 지도의 경우 아래와 같이 3가지 경로가 가능하다.
지도 정보가 주어졌을 때, 항상 내리막길로만 이동하는 경로의 개수를 구하는 프로그램을 작성하라.
일단 딱 보고 떠오른 풀이는 백트래킹이다.
단순히 목표 좌표에 도달했으면 return true / 아니라면 return false가 아닌, 도달했으면 return 1 / 아니라면 return 0을 해서 dfs 함수 호출 결과를 합쳐서 반환하는 것이다.
```py
def dfs(x: int = 0, y: int = 0) -> int:
if x == N - 1 and y == M - 1:  # base case. 목표 좌표에 도달했으면 return 1
return 1
visited[x][y] = True  # 일단은 방문 처리
ans = 0
for dx, dy in offset:
nx, ny = x + dx, y + dy
if out_of_bound(nx, ny) or visited[nx][ny] or board[nx][ny] >= board[x][y]:  # 범위 밖이거나, 방문했거나, 높이가 낮지 않다면
continue  # 가지 않음
ans += dfs(nx, ny)  # dfs 호출 결과를 누적
visited[x][y] = …
```

33-9kyo-hwang

---

gjsk132/Greedy/1911 흙길 보수하기.py
gjsk132/README.md

[백준 1911 : 흙길 보수하기](https://www.acmicpc.net/problem/1911)
25분 정도
🎯 문제 이해
---
**알고리즘 유형 : 그리디(Greedy)**
> **문제 요약**
> 길에 웅덩이가 있다. 웅덩이는 시작과 끝 지점으로 주어진다.
> 이 웅덩이를 정해진 길이의 널빤지를 깔아서 보수한다고 한다.
> 널빤지 수가 최소가 되게 하는 경우를 구하면 된다.
뭔가 처음 이 문제를 보면,
웅덩이 길이를 덮을 정도의 널빤지만 있으면 된다고 생각할 수 있지만
그렇게 시도하면 '틀렸습니다'를 보게 될 것이다.
왜냐하면, 아래와 같이 널빤지와 웅덩이가 주어질 때를 예외로 둘 수 있다.
<image src ="https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/b5c360b9-12e3-4bdb-836d-a965f753e552" width=400>
<image src ="https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/df0ff8ca-6bcc-4026-80e5-bfaceffd97ce" width=400>
만약 웅덩이마다 해주었다면 최소 3개의 널빤지를 사용할 것이다.
하지만 널빤지가 다음 웅덩이에 영향을 줄 수 있어 널빤지를 깔 때마다
어느 위치까지 가려줄 수 있는지를 알고 해당 위치부터 널빤지를 깔아주면 된다.
만약 10부터 15까지 웅덩이가 있고, 이전에 깐 널빤지가 12까지 갈렸다면
사실상 웅덩이가 12에서 시작해서 15에 끝난다고 생각하고 해주면 최소로 사용한 널빤지의 …

27-gjsk132

---

Dolchae/README.md
Dolchae/브루트포스/1182 부분수열의 합.py

[1182 부분수열의 합](https://www.acmicpc.net/problem/1182)
30분
N개의 정수로 이루어진 수열의 부분수열 중, 그 수열의 원소를 다 더한 값이 S가 되는 경우의 수를 구하는 문제이다.
<br>
```python
import sys
from itertools import combinations
n, target = map(int,input().split())
num_list = list(map(int,input().split()))
ans = 0
```
n은 수열의 원소의 개수, target은 문제에서의 S(이 값과 합이 같다면 카운팅해야하는 값)를 나타낸다. num_list는 입력받은 수열을 저장하고 ans는 나중의 출력할 target이 되는 부분수열의 개수이다.
<br>
```python
for i in range(1,n+1):
now_list = list(combinations(num_list,i))
for j in range(len(now_list)):
now = sum(now_list[j])
if now == target:
ans += 1
print(ans)
```
- i는 원소의 개수를 나타내며 1~n까지 변경된다.
- now_list에 num_list의 부분수열 중 원소의 개수가 i인 수열들을 저장한다.
- j for문에서 now_list의 부분수열 하나하나를 보며 부분수열 중 target과 now(now_list 부분수열의 총합)이 같다면 ans를 1 더해준다.
- 마지막으로 ans를 출력해준다.
<br> …

35-Dolchae

---

xxubin04/README.md
xxubin04/정렬/프로그래머스 - 가장 큰 수.py

[프로그래머스 코테 연습 - 가장 큰 수](https://school.programmers.co.kr/learn/courses/30/lessons/42746?language=python3)
<br>
30분
<br>
`numbers`에 주어지는 숫자들을 조합하여 가장 큰 수를 만드는 문제이다.
Test Case 2
```python
[3, 30, 34, 5, 9]
9534330
```
간단하게 숫자들의 맨 처음 부분이 큰 수부터 정렬하면 해결될 것이라 생각했다.
하지만, 테스트 케이스 2에서는 그에 대한 반례를 제시한다.
맨 앞의 수가 같은 숫자인 `3, 30, 34`가 문제이다.
가장 큰 수로 만들려면 `34 | 3 | 30`으로 붙여주어야 한다.
아이디어가 떠오르지 않아 [블로그](https://esoongan.tistory.com/103)를 참고하였습니다..
문제에서 `numbers`의 원소는 1000이하라는 조건을 주는데, 이는 매우 중요하다. 
최소 한 자릿수 이상 세 자리 이하의 수가 주어지므로 각각의 문자열에 3을 곱해보면 된다.
**34 3** | 4 34  -> 343
**3 3 3** | -> 333
**30 3** | 0 30   -> 303
즉, 34, 3, 30 순서대로 나열하는 것이 가장 큰 수를 도출해낼 수 있다.
<br>
```python
def sort(nList):
for i in range(len(nList)):  # nList의 요소들을 string으로 형변환
nList[i] = str(nList[i])
nList.sort(reverse = True)  # 역순으로 …
```

37-xxubin04

---

gjsk132/Divide And Conqouer/2630 색종이 만들기.py
gjsk132/README.md

[백준 2630 : 색종이 만들기](https://www.acmicpc.net/problem/2630)
20분
🎯 문제 이해
---
**알고리즘 유형 : 분할정복(Divide And Conquer)**
>**문제 요약**
> 2, 4, 8, 16, 32, 64, 128 크기의 색종이 정보가 들어오면
> 0 또는 1로만 되어있는 정사각형으로 나누어 그 수를 각각 구하면 되는 문제이다.
> 그 예시로 아래의 이미지를 참고하면 된다.
> <img src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/606b2b39-62f7-4f23-8f08-834e984784d6" width=250>
> 
> 하얀색 색종이 : 9 / 파란색 색종이 : 7
<details>
<summary>분할 정복이란?</summary>
<div markdown="1">
엄청나게 크고 방대한 문제를 조금씩 나눠가면서 용이하게 풀 수 있는 문제 단위로 나눈 다음 그것을 다시 합쳐서 해결하는 개념이다.
위 이미지와 같이
> 상단에서 **분할**
> 중앙에서 **정복(해결)**
> 하단에서 **조합**
3가지 형태로 도식화 할 수 있다.
분할정복은  **재귀**를 사용하여 구현할 수 있다.
```py
function F(x):
if F(x)가 해결 가능하도록 단순화 된 경우:
return F(x)를 계산한 값
else:
x를 원하는 수로 분할 ( ex. x1, x2 )
x를 분할한 값들을 모두 다시 호출 (ex. F(x1), F(x2))
return 분할한 값들의 결과를 반환 (ex. …
```

29-gjsk132

---

xxubin04/DP/11568_민균이의 계략.py
xxubin04/README.md

[백준 11568번: 민균이의 계략😈](https://www.acmicpc.net/problem/11568)
<br>
1시간 +  α
<br>
> 순증가되는 부분의 최대 길이를 출력하는 문제이다.
```python
5
8 9 1 2 10
--------------
8
5 4 3 2 1 6 7 8
```
<br>
DP... 어렵다..!! 블로그를 좀 참고하였습니다...🥹
<br>
```python
N = int(input())
cards = list(map(int, input().split()))
dp = [1] + [0] * (N - 1)
for i in range(1, N):
MAX = 0
for j in range(i):
if cards[j] < cards[i]:
MAX = max(MAX, dp[j])
dp[i] = MAX + 1
print(max(dp))
```
i = 1, 2, 3, ..., N
j = 1, 2, 3, ..., N
<br>
i = K라고 한다면, j는 0 ~ (K-1)을 순회하게 된다.
```python
if cards[j] < cards[i]:
MAX = max(MAX, dp[j])
dp[i] = MAX + 1
```
> 인덱스 j인 카드가 인덱스 i인 카드보다 작은 경우 == 순증가
위와 같은 경우에는, MAX를 갱신해준다. 위의 경우에 해당하지 않는 경우에는 1을 추가하면 안되므로 갱신해주지 않는다.
이러한 과정을 반복하게 되면, dp의 각각의 인덱스에 MAX값이 저장되어있다.
그러므로, dp에서의 최댓값이 최대 순증가 길이와 …

38-xxubin04

---

Dolchae/README.md
Dolchae/힙/1927 최소 힙.py

[1927 최소 힙](https://www.acmicpc.net/problem/1927)
50분
입력값이 0이라면 배열에서 가장 작은 값을 출력 후 배열에서 삭제하고, 
입력값이 자연수라면 배열에 x 값을 추가하는 과정을 n만큼 반복하는 문제이다.
<br>
자료는 [이 블로그](https://innovation123.tistory.com/111)에서 가져왔습니다!
<br>
최소 힙은 부모 노드의 key가 자식 노드의 key보다 작거나 같은 완전 이진트리이다. 
- 최소 힙에서 값을 삽입 할 때는 트리의 가장 끝에 삽입한 뒤, 부모 노드와 key값을 비교해 작을 경우 자리를 교체하는 방식을 반복한다.
<br>
- 최소 힙에서 값을 삭제할 때는 최상위 노드를 삭제하고 그 자리에 가장 마지막 위치의 노드를 가져온다. 그리고 삽입과 반대로 좌우 노드와 비교했을 때 가져온 노드가 더 크다면 자리를 교체하는 방식을 반복한다.
<br>
```python
import sys
import heapq
heap_que = []
```
`n`: 연산의 개수
`heap_que`: 연산에 사용될 리스트
<br>
```python
now = int(input())
if now == 0:
if len(heap_que)==0:
print(0)
else:
print(heapq.heappop(heap_que))
else:
heapq.heappush(heap_que,now)
```
`now`에 연산할 정수를 입력 받는다.
- …

38-Dolchae

---

Dolchae/README.md
Dolchae/힙/11286 절댓값 힙.py
Dolchae/힙/1927 최소 힙.py

[11286 절댓값 힙](https://www.acmicpc.net/problem/11286)
_구교황 선배님 추천 문제😎_
50분
n만큼 다음 연산을 진행한다.
1. 입력값이 0이라면 현재 힙에서 절댓값이 가장 작은 값을 출력하고 힙이 비어있다면 0을 출력한다.
2. 입력값이 0이 아니라면 heap에 저장한다.
<br>
```python
import sys
import heapq
heap = []
for _ in range(n := int(input())):
now = int(input())
if now == 0:
if heap:
print(heapq.heappop(heap)[1])
else:
print(0)
else:
heapq.heappush(heap, (abs(now),now))
```
계에속 헤매다가 튜플을 사용하는 블로그를 보고 바로 튜플을 적용해서 구현했다. 
- 튜플은 (절댓값, 원래값)으로 구성되어있고 입력값 `now`가 0이 아니라면 튜플로 값을 저장한다.
- `now`가 0이고 `heap`이 비어있지 않다면 (튜플의 첫 번째 요소인 절댓값을 기준으로 최소 힙이 유지되므로) 튜플의 두 번째 요소인 원래값을 출력한다.
- `now`가 0이고 `heap`이 비어있다면 0을 출력한다.
```python
import sys
import heapq
heap = []
for _ in range(n := int(input())):
now = int(input())
if now == 0:
if heap: …
```

39-Dolchae

---

9-kyo-hwang/Divide and Conquer/18291 비요뜨의 징검다리 건너기.cpp
9-kyo-hwang/Greedy/2212 센서.cpp
9-kyo-hwang/Greedy/8980 택배.cpp
9-kyo-hwang/README.md

[18291 비요뜨의 징검다리 건너기](https://www.acmicpc.net/problem/18291)
20분 + 아예 모르는 부분이라 생각해서 검색해봄
길이가 $1 \le N \le 10^9$인 일직선 상에서, 1번 위치에서 출발해 N번 위치로 이동하고자 한다. 단 다음과 같은 규칙이 적용된다.
- 임의의 정수 $1 \le X \le N$에 대해, 현재 위치 $i$번에서 $i + X$ 위치로 이동할 수 있다.
- N번 위치로 **정확히** 이동해야 한다. N번을 지나쳐서는 안된다.
예를 들어, 1번 위치에서 4번 위치로 이동하고자 하면 다음과 같은 4가지 방법으로 이동할 수 있다.
- 1 -> 2 -> 3 -> 4
- 1 -> 2 -> 4
- 1 -> 3 -> 4
- 1 -> 4
테스트 케이스 개수 T가 주어진 후, 각 테스트 케이스마다 일직선 길이 N이 주어진다. 
각 테스트 케이스마다 규칙을 만족하면서 N번 위치로 이동하는 경우의 수를 $10^9 + 7$로 나눈 나머지를 출력하는 프로그램을 작성하라.
한 번 여러가지 N에 대해 경우의 수를 구해보자.
1. N = 1: 시작 위치 = 도착 위치이므로 답은 1
2. N = 2: 1 -> 2로 가는 경우의 수 밖에 없으므로 답은 1
3. N = 3: 1 -> 2 -> 3 & 1 -> 3 2가지 경우의 수가 존재한다. 답은 2
4. N = 4: 문제 설명과 같다. 답은 4
5. N = 5: 다음과 같이 8가지 경우가 나온다.
- 1 -> 2 -> 3 -> 4 -> 5
- 1 -> 2 -> 3 -> 5
- 1 -> 2 -> 4 -> 5
- 1 -> 3 -> …

39-9kyo-hwang

---

9-kyo-hwang/Divide and Conquer/18291 비요뜨의 징검다리 건너기.cpp
9-kyo-hwang/Greedy/2212 센서.cpp
9-kyo-hwang/Greedy/8980 택배.cpp
9-kyo-hwang/README.md

[8980 택배](https://acmicpc.net/problem/8980)
1시간 넘기고 블로그를 봐버렸다...ㅜ
위 그림과 같이 본부에서 출발하여 1번 마을부터 마지막 마을까지 오른쪽으로 가면서 마을에 있는 물건을 배송한다. 각 마을은 배송할 물건들을 박스에 넣어 보내며, 본부에서는 박스를 보내는 마을번호, 박스를 받는 마을번호와 보낼 박스의 개수를 알고 있다.
용량 제한이 있는 이 트럭 한 대를 이용해 다음 조건을 만족해야 할 때, 
- 박스를 트럭에 실으면, 이 박스는 받는 마을에서만 내린다.
- 트럭은 지나온 마을로 되돌아가지 않는다.
- 박스들 중 일부만 배송할 수도 있다.
배송할 수 있는 **최대 박스 개수**를 구하는 프로그램을 작성하라.
문제 설명에 있는 예시를 보고 "각 마을에 있는 택배를 가능한 많이 담도록 하면 되는건가?" 싶어서 그렇게 작성해봤는데 바로 2번 테스트 케이스에서 빠꾸먹었다.
트럭 용량이 60이고 택배 정보가 아래와 같을 때
보내는 마을 | 받는 마을 | 박스 개수
-- | -- | --
1 | 2 | 30
1 | 6 | 40
2 | 5 | 70
3 | 4 | 40
5 | 6 | 60
마을에 도착할 때마다 가능한 많이 담을 경우
- 1번 마을에서 (2, 30), (6, 30) 담음 -> +60
- 2번 마을에서 (2, 30) 내리고 (5, 30) 담음 -> +30
- 3번 마을에서는 용량 부족으로 못담음
- 4번 마을에서는 담을 것도 내릴 것도 없음
- 5번 마을에서 (5, 30) 내리고 (6, 30) 다음 -> +30
- 6번 마을에서 (6, 30), (6, 30) …

38-9kyo-hwang

---

xxubin04/README.md
xxubin04/수학/1484.cpp

[백준 1484번 : 다이어트🏋🏻‍♂️](https://www.acmicpc.net/problem/1484)
<br>
1시간 + α
<br>
> **G = (현재 몸무게)^2 - (기억하는 몸무게)^2**
1. 현재 몸무게 > 기억하는 몸무게
2. 현재 몸무게, 기억하는 몸무게, G = 자연수
위의 조건을 만족하는 현재 몸무게가 될 수 있는 경우를 전부 출력하는 문제이다.
<br>
시간초과로 애쓰다가 Chat GPT의 힘을 좀 빌렸습니다...🥹😂
python으로는 시간초과를 해결하지 못할 것 같아서 c++로 도전해보았습니다..!
<br>
```cpp
#include <iostream>
#include <algorithm>
using namespace std;
int main() {
vector<int> ans;
int G;
cin >> G;
for (int k = 1; k <= G; k++) {
if (G % k == 0) {
int j = G / k;
int i = k;
if (j > i && (j+i) % 2 == 0 && (j-i) % 2 == 0)
ans.push_back((j+i) / 2);
}
}
if (ans.size() > 0) {
sort(ans.begin(), ans.end());
for (int a = 0; a < ans.size(); a++)
cout << ans[a] << endl;
} else
cout << -1 << endl;
return 0;
}
```
`G = (현재 몸무게)^2 - (기억 몸무게)^2` 이므로 현재 몸무게는 최대 G를 넘어설 수 …

41-xxubin04

---

9-kyo-hwang/Divide and Conquer/18291 비요뜨의 징검다리 건너기.cpp
9-kyo-hwang/Dynamic Programming/7579 앱.cpp
9-kyo-hwang/Greedy/2212 센서.cpp
9-kyo-hwang/Greedy/8980 택배.cpp
9-kyo-hwang/README.md

[7579 앱](https://acmicpc.net/problem/7579)
1시간 조금 넘긴 듯
N개의 앱 $A_1, A_2, ..., A_N$이 활성화 되어 있다. 각각의 앱 $A_i$는 $m_i$ 바이트만큼 메모리를 사용한다. 또한 앱 $A_i$를 비활성화 한 후 재실행 할 때 추가적으로 $c_i$만큼의 비용이 든다.
새로운 앱 B를 실행하고자 하는데, 추가로 M byte 이상의 메모리가 필요하다. 그러기 위해 현재 활성화된 앱 $A_1, A_2, ..., A_N$ 중 몇 개를 비활성화 해야 하는데, **비활성화 했을 때 드는 비용 $c_i$의 합이 최소가 되는** 조합을 찾아야 한다.
필요한 메모리 M byte를 확보하기 위한 앱 비활성화의 최소 비용을 찾아 출력하는 프로그램을 작성하라.
이 문제는 DP 알고리즘에서 대표 유형인 **배낭 문제**의 변형이다. 
처음에는 **각 메모리 사용량 별 최소 비용**으로 생각해서 DP 테이블을 만들어보려고 했는데, M과 $m_i$가 최대 10,000,000까지 입력으로 들어온다. 앱 개수가 최대 100개이니, 최악의 경우 이를 DP 테이블로 만들면 100 x 10,000,000 = 10억개의 공간과 시간복잡도가 들 것이라 예상되어 "이건 아닌 것 같은데..." 하고 폐기했다.
그래서 고민을 더 해 본 결과, **각 비용 별 최대 메모리 사용량**으로 잡으면 될 것 같다라는 생각이 들었다. 이 경우 각각의 비용 $c_i$가 최대 100이므로, 전부 다 더해도 최대값이 10,000이라 100 x 10,000 = 1,000,000으로 할 만하다는 생각이 들었다. …

40-9kyo-hwang

---

xxubin04/Binary Search/4454_상근이의 여자친구.py
xxubin04/README.md

[백준 4454번: 상근이의 여자친구](https://www.acmicpc.net/problem/4454)
<br>
1시간
<br>
초등학생때 배우는 거속시 공식을 떠올려야 한다.
> `av^4 + bv^3 + cv^2 + dv` = 한 시간동안 소모되는 기름의 양
> 여자친구에게 도달하는데까지 걸리는 시간 = 거리 / 속력
> t = 차에 있는 기름의 양, m = 여자친구와 상근이 사이의 거리
즉, `av^4 + bv^3 + cv^2 + dv` x 걸리는 시간 < t 인 조건을 만족하는 **최대 속력인 v**를 구하면 된다.
<br>
험난했습니다... 블로그와 지피티 선생님께 조언을 좀 구하였습니다...👍
<br>
```python
def max_velocity(a, b, c, d, m, t):
start = 0;
end = 1000000
MAX = 0
for i in range(500):
mid = (start + end) / 2
distance = (a * mid ** 3 + b * mid ** 2 + c * mid + d) * m
if distance <= t:
MAX = max(MAX, mid)
start = mid
else:
end = mid
return MAX
while True:
try:
a, b, c, d, m, t = map(float, input().split())
result = max_velocity(a, b, c, d, m, t)
print("%.2f" % (int(result * 100) / 100))
except:
break
``` …

40-xxubin04

---

xxubin04/Heap/1374_강의실.py
xxubin04/README.md

[백준 1374번 : 강의실](https://www.acmicpc.net/problem/1374)
<br>
2시간 + α
<br>
예전에 나영 선배님이 푸신 [회의실 배정](https://github.com/AlgoLeadMe/AlgoLeadMe-3/pull/67) 이 생각이 나서 기억을 떠올려서 도전해보았다. 
사진이 눈이 좀 아프게 보이네요..허허..
강의의 시작 시각과 종료 시각이 주어지는데, 제 시간에 모든 강의가 진행될 수 있도록 하는 강의실의 최소 개수를 구해야 한다.
단, 하나의 시각에 하나의 강의실은 하나의 강의만 진행할 수 있다.
<br>
heapq를 안쓰고 이중 for문으로 풀려고 하니 계속 시간초과도 나고 틀렸다...ㅎㅎ
Chat GPT의 힘을 빌렸더니 진짜 이렇게도 풀 수 있구나 싶었습니다...👍
<br>
```python
import heapq
ans = 0
time_table = []
for i in range(N := int(input())):
num, start, end = map(int, input().split())
time_table.append((start, end))
time_table.sort()  
```
`time_table`에 (start, end) 형태로 시작 시간, 종료 시간을 입력받고 시작 시간을 기준으로 오름차순으로 정렬해준다.
<br>
```python
end_times = [] 
for start, end in time_table:
while end_times and end_times[0] <= start: …
```

39-xxubin04

---

9-kyo-hwang/Divide and Conquer/18291 비요뜨의 징검다리 건너기.cpp
9-kyo-hwang/Dynamic Programming/7579 앱.cpp
9-kyo-hwang/Greedy/8980 택배.cpp
9-kyo-hwang/Minimum Spanning Tree/17472 다리 만들기 2.cpp
9-kyo-hwang/Prefix Sum/2015 수들의 합 4.cpp
9-kyo-hwang/README.md

[17472 다리 만들기 2](https://acmicpc.net/problem/17472)
6시간(휴...)
다음 이미지와 같이 N x M 격자에 색칠된 영역이 존재한다.
이 영역들을 다음과 같이 다리를 놓아 모두 연결시키고자 한다.
이 때, 이 연결하는 다리들은 반드시 직선이어야 하며 길이가 2 이상이어야 하고, 방향이 가로인 다리는 다리의 양 끝이 가로 방향으로/방향이 세로인 다리는 다리의 양 끝이 세로 방향으로 섬과 인접해야 한다. 다음 이미지들은 올바르게 연결되지 않은 다리 예시이다.
격자 정보가 주어졌을 때, **모든 섬을 연결하는 다리 길이의 최솟값**을 구하는 프로그램을 작성하라.
제한
- $1 \le N, M \le 10$
- $3 \le NM \le 100$
- $2 \le$ 섬 개수 $\le 6$
크게 3단계를 거쳐 풀이를 진행한다.
1. 영역에 번호 매기기
2. 영역 간 다리 만들기
3. 만들어진 다리에 대해 최소 스패닝 트리를 적용해 최소 길이 합 구하기
일반적인 최소 스패닝 트리 - 크루스칼 알고리즘의 경우, (출발 노드, 도착 노드, 거리)를 엣지로 묶은 뒤 사이클이 이루지 않도록 유지하며 거리가 짧은 순으로 엣지를 취한다.
하지만 이 문제는 격자 내 일정 "영역"이 노드이기 때문에, 영역 별로 번호를 매기는 작업이 필요하다. 즉 아래 이미지와 같이 영역 별로 공통된 번호를 기록하고자 한다.
```py
def dfs(x: int, y: int):
visited[x][y] = True
graph[x][y] = node_number
islands.append((x, y, …
```

42-9kyo-hwang

---

gjsk132/Bellman Ford/11657 타임머신.py

[백준 11657 : 타임머신](https://www.acmicpc.net/problem/11657)
25분
>태규님의 엄청난 알고리즘 강의로 완벽(?) 습득해서 거의 막힘없이 풀었습니다.
🎯 문제 이해
---
**알고리즘 유형 : 벨만-포드 (Bellman-Ford)**
<details>
<summary>🔍벨만-포드 알고리즘 이해하기 (Bellman-Ford)</summary>
<div markdown="1">
---
</div>
</details>
>**문제 이해**
N개의 노드가 M개의 간선으로 연결되어 있다.
간선은 가중치가 있다. ( 음수 존재 )
1번 노드에서 각 노드로 가는 최단 거리를 구해라
>
>( 값을 특정할 수 없다면 -1을 출력하고 )
( 노드가 연결되어 있지 않다면 해당 도시만 -1로 출력한다. ) 
일단 음수 가중치가 있다는 점과 값을 특정할 수 없는( 무한 사이클 )이 존재하므로 벨만-포드 알고리즘을 사용하는 것을 바로 알 수 있다.
**풀이 과정**
벨만-포드 알고리즘을 사용하여 모든 노드와 연결된 모든 간선을 확인하는 과정을 N-1번 한 것과 N번 한 것을 비교한다.
만약 두 개가 다르다면 무한 사이클이 존재하기 때문에 값을 특정할 수 없으므로 -1을 출력하고 종료한다.
결과가 같다면 각 노드까지의 최단 거리를 출력한다.
( 하지만 맨 처음과 결과가 같다면(INF) -1을 출력한다. )
🔍코드 설명
---
`city` : 도시의 수 (노드 수)
`path_cnt` : 버스 노선의 수 (간선 수)
`path` : 노선 정보를 저장 ( `path[시작 노드] = (도착 노드, …

30-gjsk132

---

gjsk132/Divide And Conqouer/1074 Z.txt
gjsk132/README.md

> 저번 분할 정복 복습 겸 추천해주신 문제 풀어봤습니다.
[백준 1074 : Z](https://www.acmicpc.net/problem/1074)
40분
🎯 문제 이해
---
**알고리즘 유형 : 분할 정복 ( Divide and Conquer )**
> 문제 요약
아래 이미지를 통해 방문 순서를 알 수 있다. ( Z 모양 )
주어진 위치가 몇 번째에 방문하는지를 알면 되는 문제
><img src = "https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/057b5371-e503-4206-8fc0-14397374d886" width = 150>
문제에 주어진 이미지를 보기만 해도 분할 정복인 것을 알 수 있다.
> 한 정사각형을 4개의 정사각형으로 분리해서 Z 모양으로 방문
재귀를 활용하여 4사분면을 반복해서 탐색해준다.
여기서 주의해야 할 점이 1개 1개 다 탐색하게 되면 시간 초과가 난다. 😞 
그럼 원하는 위치가 있는 부분만 고르면 어떨까?
위 그림과 같이 4분할해서 위치가 포함되는 부분을 한번 더 탐색해주고, 이전에 탐색한 범위의 면적만 더해주는 과정을 거친다.
이렇게 해주면 굳이 하나하나 들어가지 않아도 더 적은 시간에 해결할 수 있게 된다.
🔍코드 설명
---
`n` : 2^n 사이즈의 2차원 배열을 의미
`row`, `col` : 원하는 값의 위치
`z_setting` : z 모양으로 위치를 탐색하는 함수
`cnt` : 원하는 값의 위치를 몇 번째에 탐색하는지 알 수 있는 변수
---
주어진 값을 입력받는다.
```py
n, row, …
```

31-gjsk132

---

gjsk132/Bellman Ford/1865 웜홀.py
gjsk132/README.md

[백준 1865 : 웜홀](https://www.acmicpc.net/problem/1865)
1시간... 이상..?
🎯 문제 이해
---
**알고리즘 유형 : 벨만-포드 (Bellman-Ford)**
일단 음수 가중치가 있는 유향그래프라는 점에서 벨만-포드 알고리즘을 사용해야겠다는 생각이 바로 들었다.
테스트케이스 수 만큼 그래프가 주어진다.
그래프가 시작 지점으로 돌아왔을 때, -가 될 수 있다면 YES를 출력한다.
문제에서는 언제 시작 지점으로 돌아와야 하는지 언급이 없다. 즉 언제든 -가 되면 된다. 따라서 계속 연결된 전체 노드의 값이 줄어드는 무한 사이클이 있다면 시작 노드도 -가 되게 된다.
> 간단히 요약하면 무한 사이클이 있다면 YES를 출력하면 된다.
🔍코드 설명
---
`node` : 노드의 수
`undirected_line` : 무방향(양방향) 간선의 수
`directed_line` : 방향 간선의 수
`line_info` : 간선 정보를 저장하는 리스트
`node1` , `node2` : 무방향 간선에서 사용하는 2개의 노드
`start`, `end` : 방향 간선에서 사용하는 시작과 끝 노드
`weight` : 가중치
`node_info`: 각 노드까지의 거리
`limit`: 한계값
일단 주어진 값들의 내가 원하는 방식으로 저장해보자
주어진 테스트케이스 수에 맞춰서 반복해주고, 노드, 간선들의 수를 입력받는다.
```py
for i in range(int(input())):
node, undirected_line, directed_line = …
```

32-gjsk132

---

gjsk132/Implementation/Trapping Rain Water.py
gjsk132/README.md

[Leetcode : Trapping Rain Water](https://leetcode.com/problems/trapping-rain-water/description/)
50분
🎯 문제 이해
---
> 문제 요약
> <img src="https://github.com/AlgoLeadMe/AlgoLeadMe-3/assets/113815454/213f6cdd-755f-4f7f-b4a7-0cecf1abc577" width=300>
> 위 이미지의 파란 부분과 같이 좌우로 가둬져서 쌓이는 빗물의 양을 구하는 문제이다.
> 높이는 리스트(`height`)로 받는다.  
한 방향으로 가면서, 이전의 높이보다 큰 높이를 만나면 고인 빗물을 총 빗물에 더해주면된다.
하지만 가장 큰 높이 이후에 고인 빗물을 더하기가 어렵다.
따라서 가장 큰 높이의 위치를 기억해둔 뒤, 뒤에서부터 해당 인덱스까지 가면
남은 고인 빗물의 양을 알 수 있다.
🔍코드 설명
---
`rain` : 총 빗물의 양
`tmp` : 다음 더 높은 위치가 나오기 전까지 고이는 빗물의 양 기억
`max_h` : 가장 큰 높이
`max_pos` : 가장 큰 높이의 위치
가장 큰 높이가 나오기 전에 고이는 빗물의 양을 구하는 과정이다.
```py
for p, h in enumerate(height):
if max_h <= h:
max_h = h
rain += tmp
tmp = 0
max_pos = p
else:
tmp += max_h-h
```
만약 더 높은 높이를 만나면 이전의 빗물량을 더해주고, 아니라면 그 칸에 고이는 빗물의 양을 더해준다.
높은 높이를 …

33-gjsk132

---

xxubin04/README.md
xxubin04/수학/16943_숫자 재배치.py

[16943번: 숫자 재배치](https://www.acmicpc.net/problem/16943)
<br>
1시간 30분
<br>
입력받은 A와 B에서 A의 각 자릿수를 조합하여 B보다 작은 최대 수를 출력하는 문제이다.
단, A에 0이 포함되어 있다면, 0100, 0010과 같이 앞의 없어지는 자릿수로 0을 배치할 수 없다.
Ex)
`1234` `3456` 로 A, B가 주어졌다면,
3456보다 작으면서 최대 수는 3421이므로 3421을 출력한다.
<br>
```python
A, B = input().split()
num_A = list(A)
perm_A = list(permutations(num_A, len(A)))
```
A, B에 두 수를 입력받고, num_A에 A의 각 자릿수별로 수를 분리시킨다.
perm_A에 num_A의 수들의 순열을 저장한다.
<br>
```python
ans = -1
for i in perm_A:
i_list = []
for j in i:
i_list.append(j)
if i_list[0] == '0':
continue
if int(''.join(i_list)) < int(B):
ans = max(ans, int(''.join(i_list)))
print(ans)
```
join함수를 쓰려고 하니, 튜플형식에는 쓸 수 없다고 하여 i_list로 리스트 형식 안에 각 수들을 다시 입력해주었다.
만약, 맨 앞의 자릿수가 '0'이라면 검사하지 않고 바로 넘긴다.(없어지는 자릿수의 0은 고려하지 않는다.)
조합한 수가 B보다 작은 경우에는 ans로 최댓값을 갱신해준다.
<br> …

43-xxubin04

---

xxubin04/README.md
xxubin04/Tree/1991_트리 순회.py

백준 1991번 - [트리 순회](https://www.acmicpc.net/problem/1991)
<br>
40분
<br>
- 전위 순회 : ABDCEFG -> 루트 - 왼쪽 자식 - 오른쪽 자식
- 중위 순회 : DBAECFG -> 왼쪽 자식 - 루트 - 오른쪽 자식
- 후위 순회 : DBEGFCA -> 왼쪽 자식 - 오른쪽 자식 - 루트
3가지 순회의 결과를 차례대로 출력하는 문제이다.
<br>
```python
def preorder(r):
if r != '.':
print(r, end="")
preorder(tree[r][0])
preorder(tree[r][1])
def inorder(r):
if r != '.':
inorder(tree[r][0])
print(r, end="")
inorder(tree[r][1])
def postorder(r):
if r != '.':
postorder(tree[r][0])
postorder(tree[r][1])
print(r, end="")
tree = {chr(i):['.', '.'] for i in range(65, 91)}
for j in range(int(input())):
a = input().split()
tree[a[0]][0], tree[a[0]][1] = a[1], a[2]
```
<br>
```python
print(r, end="")
preorder(tree[r][0])
preorder(tree[r][1])
```
- 전위 순회 : 루트 - 왼쪽 자식 - 오른쪽 자식
<br>
```python
inorder(tree[r][0]) …
```

54-xxubin04

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp

[17144 미세먼지 안녕!](https://www.acmicpc.net/problem/17144)
1시간
방의 정보가 $R$ x $C$ 크기의 격자판으로 주어진다. 두 행에 걸쳐 1번 열에 공기청정기가 설치되어 있고, 그 외의 칸 (r, c)에는 미세먼지가 $A_{r, c}$만큼 존재한다.
1초 동안 아래의 일이 순서대로 일어난다.
1. 미세먼지가 확산된다. 확산은 미세먼지가 있는 모든 칸에서 동시에 일어난다.
- (r, c)에 있는 미세먼지는 인접한 네 방향으로 확산된다.
- 인접한 방향에 공기청정기가 있거나, 칸이 없으면 그 방향으로는 확산이 일어나지 않는다.
- 확산되는 양은 $A_{r,c}/5$이고 소수점은 버린다. 즉, $⌊A_{r,c}/5⌋$이다.
- (r, c)에 남은 미세먼지의 양은 $A_{r,c} - ⌊A_{r,c}/5⌋$×(확산된 방향의 개수) 이다.
2. 공기청정기가 작동한다.
- 공기청정기에서는 바람이 나온다.
- 위쪽 공기청정기의 바람은 반시계방향으로 순환하고, 아래쪽 공기청정기의 바람은 시계방향으로 순환한다.
- 바람이 불면 미세먼지가 바람의 방향대로 모두 한 칸씩 이동한다.
- 공기청정기에서 부는 바람은 미세먼지가 없는 바람이고, 공기청정기로 들어간 미세먼지는 모두 정화된다.
T초 후 방에 남아있는 미세먼지의 양을 구하는 프로그램을 작성하라.
왼쪽과 위쪽에 칸이 없기 때문에, 두 방향으로만 확산이 일어났다.
인접한 네 방향으로 모두 확산이 일어난다.
공기청정기가 있는 칸으로는 확산이 일어나지 않는다.
문제를 보자마자 "아 상당히 삼성스러운 문제인데" 싶어서 검색해보니까 역시나 …

55-9kyo-hwang

---

9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/README.md

[월간 코드 챌린지 시즌 3 - 빛의 경로 사이클](https://school.programmers.co.kr/learn/courses/30/lessons/86052)
1시간
각 칸마다 S, L, 또는 R가 써져 있는 격자가 있다. 임의의 격자에서 임의의 방향으로 빛을 쏘는데, 각 칸에는 다음과 같은 특이한 성질이 있다.
- 빛이 "S"가 써진 칸에 도달하면 직진
- 빛이 "L"이 써진 칸에 도달하면 좌회전
- 빛이 "R"이 써진 칸에 도달하면 우회전
- 빛이 격자의 끝을 넘어갈 경우, 반대쪽 끝으로 다시 돌아옴
예를 들어, 2 x 2 크기의 `["SL", "LR"]` 격자가 있다고 하자. (1행, 1열)에서 (2행, 1열) 방향으로 빛을 쏘면, 다음과 같은 경로가 만들어진다.
- (1행, 1열)에서 (2행, 1열)로 빛을 발사
- (2행, 1열)은 "L"칸이므로 좌회전, (2행, 2열)로 향함
- (2행, 2열)은 "R"칸이므로 우회전, (3행, 1열)은 없으므로 (1행, 1열)로 향함
- ...
위와 같이 진행하여 최종적으로 16번째만에 최초 격자로 돌아온다.
이와 같이 격자 내에서 빛이 이동할 수 있는 경로 사이클(빛이 이동하는 순환 경로)이 몇 개 있고, 각 사이클의 길이가 얼마인지 알고자 한다. 예를 들어, 위 격자의 경우 길이가 16인 사이클 1개만 존재한다.
격자의 정보를 나타내는 1차원 문자열 배열 grid가 매개변수로 주어진다. 주어진 격자를 통해 만들어지는 빛의 경로 사이클의 모든 길이들을 배열에 담아 오름차순으로 정렬하여 return 하도록 solution 함수를 완성하라.
기본적으로는 …

53-9kyo-hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Dynamic Programming/17070 파이프 옮기기 1.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp

[17070 파이프 옮기기 1](https://acmicpc.net/problem/17070)
1시간
N x N 크기의 격자판이 있다. 각 칸은 (r, c)로 나타낼 수 있다. 여기서 r은 행 번호, c는 열 번호이고, 행과 열의 번호는 1부터 시작한다. 각 칸은 빈 칸이거나 벽이다.
다음과 같이 2개의 연속된 칸을 차지하는 파이프가 존재한다.
파이프는 →, ↓, ↘ 3가지 방향으로 회전 또는 이동시킬 수 있다. 단, 이 때 파이프는 반드시 빈 칸만 차지해야 한다.
파이프는 놓여진 방향에 따라 다음과 같이 이동할 수 있다. 색칠된 칸은 반드시 빈칸이어야 한다.
1. 가로
2. 세로
3. 대각
최초에 파이프가 (1, 1), (1, 2) 위치에 가로로 존재한다고 할 때, 파이프 한 쪽 끝을 (N, N)으로 이동시키는 방법의 수를 구하는 프로그램을 작성하라.
- 격자 크기: $3 \le N \le 16$
- 집의 상태: 빈칸 0, 벽 1
- (1, 1), (1, 2)는 반드시 빈 칸
- 방법의 수는 항상 1,000,000 이하
다이나믹 프로그래밍의 대표적인 유형인 [행렬 경로 문제](https://youtu.be/j_sdjivoPs8?si=A3dJAzRXc95AmbEL)의 변형이다.
여기서는 1. 대각 방향이 추가되었으며 2. 이동할 때 추가적인 제한 사항이 생겼다는 차이점이 존재한다.
즉 기존에 2차원 배열로 해결되었던 것과 달리, "어느 방향에서 진입했는가"에 대한 정보를 기록하기 위해 3차원 배열로 확장해야 한다.
3가지 방향에 대해 취해야 할 이전 값들을 적절히 필터링해 대입해주면 된다.
```cpp …
```

57-9kyo-hwang

---

9-kyo-hwang/Data Structure/16934 게임 닉네임.cpp
9-kyo-hwang/Data Structure/2019 KAKAO BLIND RECRUITMENT 후보키.cpp
9-kyo-hwang/Data Structure/21944 문제 추천 시스템 Version 2.cpp
9-kyo-hwang/Dynamic Programming/17070 파이프 옮기기 1.cpp
9-kyo-hwang/Graph Traversal/월간 코드 챌린지 시즌 3 - 빛의 경로 사이클.cpp
9-kyo-hwang/README.md
9-kyo-hwang/Simulation/17144 미세먼지 안녕!.cpp
9-kyo-hwang/Tree/15681 트리와 쿼리.cpp
9-kyo-hwang/Trie/14725 개미굴.cpp

1시간
다음과 같은 트리 구조의 개미굴이 존재한다.
이 개미굴의 정보가 다음과 같이 주어진다.
- KIWI BANANA
- KIWI APPLE
- APPLE APPLE
- APPLE BANANA KIWI
공백을 기준으로 왼쪽부터 순서대로 각 층마다 지나온 방에 있는 먹이 이름을 뜻한다.
이 정보를 기반으로 다음과 같이 개미굴 구조를 표현한다.
```
APPLE
--APPLE
--BANANA
----KIWI
KIWI
--APPLE
--BANANA
```
개미굴의 각 층은 "--"로 구분한다. 또 같은 층에 여러 개의 방이 있을 때에는 **사전 순서가 앞서는** 먹이 정보가 먼저 나온다.
먹이 정보 개수 $1 \le N \le 1000$가 주어진다. N개의 줄에 거쳐 먹이 정보 개수 $1 \le K \le 15$와 왼쪽부터 순서대로 각 층마다 지나온 방에 있는 먹이 정보가 주어진다. 먹이 이름 길이는 $1 \le t \le 15$를 만족하며, 알파벳 대문자로만 이루어져 있다.
개미굴의 시각화된 구조를 출력하는 프로그램을 작성하라. 최상위 굴을 포함하여 하나의 굴에서 개미굴이 여러 개로 나뉠 때, 먹이 종류 별로 최대 한 번만 나올 수 있다.
일반적인 트리처럼, 각각의 노드는 1. 데이터와 2. 자식 노드 정보를 들고 있어야 한다. 다만 1. 동일한 층에 있는 노드들은 사전 식 순서로 데이터가 정렬되어야 하며 2. 자식 노드가 여러 개일 수도 있다는 점이다.
따라서 이진검색트리 기반의 Map 자료구조를 사용하는데, 한 번 구조체(클래스)로 래핑해서 사용한다.
```cpp
struct FNode
{ …
```

58-9kyo-hwang
